/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:15:39 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import "RetryStrategyDelegate.h"
 #import "KikStorage.h"
 #import "KikNetwork.h"
 #import "KikUser.h"
 #import "ExponentialBackoffRetryStrategy.h"

@interface AccountManager : NSObject <RetryStrategyDelegate> {
	BOOL _isAuthenticated; 
	NSString* _username; 
	NSString* _jid; 
	NSString* _password; 
	NSString* _passwordDigest; 
	NSString* _email; 
	KikStorage* _storage; 
	KikNetwork* _network; 
	id<AuthorizationHandler> _authHandler; 
	NSString* _pushToken; 
	int _pushState; 
	int _pushRetryCounter; 
	NSObject* _notifyForNewPeopleUpgradeLockObject; 
	ExponentialBackoffRetryStrategy* _notifyForNewPeopleUpgradeRetry; 
	BOOL _processingNotifyForNewPeopleUpgrade; 
}
@property (nonatomic) BOOL isAuthenticated; 				//@synthesize isAuthenticated=_isAuthenticated - In the implementation block
@property (nonatomic,copy,copy) NSString* jid; 
@property (nonatomic,copy) KikUser* me; 
@property (nonatomic,copy) NSString* pushToken; 				//@synthesize pushToken=_pushToken - In the implementation block
@property (nonatomic,copy) NSString* password; 				//@synthesize password=_password - In the implementation block
@property (nonatomic,copy) NSString* passwordDigest; 
@property (assign,nonatomic) BOOL processingNotifyForNewPeopleUpgrade; 				//@synthesize processingNotifyForNewPeopleUpgrade=_processingNotifyForNewPeopleUpgrade - In the implementation block
-(void)authorizationRevoked;
-(void)retryStrategyDidAdviseRetry:(id)arg1;
-(void)onXmppConnected:(id)arg1;
-(void)passwordUpgraded;
-(void)performPushTokenMaintenance;
-(void)loadInstanceVariables;
-(void)onRemoteNotificationWithDeviceToken:(id)arg1;
-(void)onRemoteNotificationWithError:(id)arg1;
-(void)clearPushTokenOnServer;
-(void)setAuthenticationStatus:(BOOL)arg1;
-(void)updateUserProfile;
-(void)processPushTokens;
-(void)performUpgradeOfNotifyForNewPeople;
-(void)setProcessingNotifyForNewPeopleUpgrade:(BOOL)arg1;
-(void)setNotifyNewPeopleEnabled:(BOOL)arg1 success:(id)arg2 expiry:(id)arg3;
-(void)loggedInWithUsername:(id)arg1 email:(id)arg2 password:(id)arg3 jid:(id)arg4 firstName:(id)arg5 lastName:(id)arg6;
-(BOOL)userDetailsAvailable;
-(void)registerForPushToken;
-(void)pushTokenToServer;
-(void)callbackSetPushToken:(id)arg1;
-(void)callbackClearPushTokenOnServer:(id)arg1;
-(id)initWithStorage:(id)arg1 andNetwork:(id)arg2 andAuthorizationHandler:(id)arg3;
-(void)loginWithEmail:(id)arg1 password:(id)arg2 deviceId:(id)arg3 version:(id)arg4 captchaResponse:(id)arg5 callback:(id)arg6;
-(void)registeredAccountWithUsername:(id)arg1 andPassword:(id)arg2 andEmail:(id)arg3 andJID:(id)arg4;
-(void)setMessagePreviewEnabled:(BOOL)arg1 success:(id)arg2 expiry:(id)arg3;
-(void)onAuthenticationSuccess:(id)arg1;
-(void)dealloc;
-(void)reset;
-(void)setup;
@end