/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:44 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <AddressBookXDataProvider.h>
#import <RetryStrategyDelegate.h>

@interface AddressBookXData : NSObject <AddressBookXDataProvider, RetryStrategyDelegate> {
	XDataManager* _xDataManager; 
	ExponentialBackoffRetryStrategy* _retryStrategy; 
	id _callback; 
	BOOL _doCallback; 
	NSObject* _callbackLock; 
}
-(void)retryStrategyDidAdviseRetry:(id)arg1;
-(void)setAddressBookStatus:(BOOL)arg1;
-(void)checkAddressBookStatusWithCallback:(id)arg1;
-(id)initWithXDataManager:(id)arg1;
-(void)cancelCallback;
-(void).cxx_destruct;
@end