/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:44 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol AddressBookXDataProvider
@required
-(void)setAddressBookStatus(BOOL):arg1 ;
-(void)checkAddressBookStatusWithCallback(id):arg1 ;
-(void)setAddressBookStatus(BOOL):arg1 ;
-(void)checkAddressBookStatusWithCallback(id):arg1 ;
@end
