/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:05 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AGImagePickerController : HybridNavigationController {
	id delegate; 
	BOOL shouldChangeStatusBarStyle; 
	BOOL shouldDisplaySelectionInformation; 
	BOOL shouldShowSavedPhotosOnTop; 
	int oldStatusBarStyle; 
	id didFinishBlock; 
	id didFailBlock; 
	unsigned maximumNumberOfPhotos; 
	unsigned minimumNumberOfPhotos; 
	NSArray* toolbarItemsForSelection; 
	NSArray* selection; 
}
@property (assign) BOOL shouldChangeStatusBarStyle; 
@property (assign) BOOL shouldDisplaySelectionInformation; 
@property (assign) BOOL shouldShowSavedPhotosOnTop; 
@property (assign) unsigned maximumNumberOfPhotos; 
@property (assign) unsigned minimumNumberOfPhotos; 
@property (assign,nonatomic) id delegate; 
@property (copy) id didFailBlock; 
@property (copy) id didFinishBlock; 
@property (retain) NSArray* toolbarItemsForSelection; 
@property (retain) NSArray* selection; 
+(id)defaultAssetsLibrary;
+(int)currentInterfaceOrientation;
+(CGPoint)itemTopLeftPoint;
+(unsigned)numberOfItemsPerRow;
+(CGPoint)checkmarkBottomRightPoint;
+(CGSize)checkmarkSize;
+(CGRect)checkmarkRect;
+(CGRect)itemRect;
+(CGPoint)checkmarkTopRightPoint;
+(CGRect)checkmarkFrameUsingItemFrame:(CGRect)arg1;
+(CGSize)itemSize;
-(id)initWithFailureBlock:(id)arg1 andSuccessBlock:(id)arg2;
-(void)setShouldChangeStatusBarStyle:(BOOL)arg1;
-(void)setShouldDisplaySelectionInformation:(BOOL)arg1;
-(void)setShouldShowSavedPhotosOnTop:(BOOL)arg1;
-(void)setToolbarItemsForSelection:(id)arg1;
-(void)setMaximumNumberOfPhotos:(unsigned)arg1;
-(void)setMinimumNumberOfPhotos:(unsigned)arg1;
-(id)initWithDelegate:(id)arg1 failureBlock:(id)arg2 successBlock:(id)arg3 maximumNumberOfPhotos:(unsigned)arg4 shouldChangeStatusBarStyle:(BOOL)arg5 toolbarItemsForSelection:(id)arg6 andShouldDisplaySelectionInformation:(BOOL)arg7;
-(void)setDidFailBlock:(id)arg1;
-(void)setDidFinishBlock:(id)arg1;
-(void)didFinishPickingAssets:(id)arg1;
-(void)didCancelPickingAssets;
-(void)didFail:(id)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(id)init;
-(unsigned)supportedInterfaceOrientations;
-(void)setSelection:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewDidLoad;
-(id)initWithDelegate:(id)arg1;
@end