/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:00:59 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AGIPCGridItem : UIView {
	BOOL selected; 
	ALAsset* asset; 
	unsigned index; 
	UIImageView* thumbnailImageView; 
	UIView* selectionView; 
	UIButton* checkmarkButton; 
	id<AGIPCGridItemDelegate> delegate; 
	BOOL _guiHasBeenSetup; 
}
@property (assign) BOOL selected; 
@property (retain) ALAsset* asset; 
@property (assign) unsigned index; 
@property (assign,nonatomic) id<AGIPCGridItemDelegate> delegate; 
@property (nonatomic,retain) UIButton* checkmarkButton; 
@property (nonatomic,retain) UIImageView* thumbnailImageView; 
@property (nonatomic,retain) UIView* selectionView; 
+(void)resetNumberOfSelections;
+(unsigned)numberOfSelections;
-(void)setupGUI;
-(id)initWithAsset:(id)arg1 andDelegate:(id)arg2 andIndex:(unsigned)arg3;
-(void)previewImageTap;
-(void)setThumbnailImageView:(id)arg1;
-(void)setCheckmarkButton:(id)arg1;
-(void)tap;
-(void)setSelectionView:(id)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(id)init;
-(void)setSelected:(BOOL)arg1;
-(id)initWithAsset:(id)arg1;
-(void)setAsset:(id)arg1;
-(void)setIndex:(unsigned)arg1;
@end