/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:00:59 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AGIPCGridCell : UITableViewCell {
	NSArray* items; 
}
@property (retain) NSArray* items; 
-(id)initWithItems:(id)arg1 reuseIdentifier:(id)arg2;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setItems:(id)arg1;
@end