/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:07:39 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol AuthorizationHandler
@required
-(void)authorize:(id)arg1 ;
-(void)authorizationRevoked;
-(void)authorize:(id)arg1 ;
-(void)authorizationRevoked;
@end
