/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, July 6, 2014 at 2:43:34 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol AuthorizationHandler
@required
-(void)authorize:(id)arg1 ;
-(void)authorizationRevoked;
-(void)authorize:(id)arg1 ;
-(void)authorizationRevoked;
@end
