/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:49 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIAlertViewDelegate
@optional
-(void)alertView(id):arg1 clickedButtonAtIndex(int):arg2 ;
-(void)alertView(id):arg1 didDismissWithButtonIndex(int):arg2 ;
-(void)alertViewCancel(id):arg1 ;
-(BOOL)alertViewShouldEnableFirstOtherButton(id):arg1 ;
-(void)didPresentAlertView(id):arg1 ;
-(void)willPresentAlertView(id):arg1 ;
-(void)alertView(id):arg1 willDismissWithButtonIndex(int):arg2 ;
@end

@protocol BrowserImplementation
@required
-(int)pageMode;
-(BOOL)obscuredByPopup;
-(void)setAutomationAsynchronousOutput(id):arg1 ;
-(void)setStatusBarHidden(BOOL):arg1 transparent(BOOL):arg2 isLight(BOOL):arg3 ;
-(BOOL)canShowPopupCardWithURL(id):arg1 ;
-(void)showSidebar;
-(int)orientationLock;
-(void)setOrientationLock(int):arg1 ;
-(void)performHttpsUpgradeForCardURL(id):arg1 ;
-(void)performRefreshClearingCache(BOOL):arg1 ;
-(void)pageFailed;
-(void)setPageMode(int):arg1 ;
-(void)navigateToUrl(id):arg1 title(id):arg2 icon(id):arg3 clearHistory(BOOL):arg4 ;
-(void)navigateToUrl(id):arg1 requestData(id):arg2 callback(id):arg3 ;
-(void)openExternalUrl(id):arg1 ;
-(void)openWindowWithUrl(id):arg1 callbackPath(id):arg2 callback(id):arg3 ;
-(void)showLoadingSpinner(BOOL):arg1 ;
-(void)pageReady;
-(id)currentUrl;
-(BOOL)isPopup;
-(void)setBrowserViewMode(int):arg1 ;
-(int)browserViewMode;
-(void)closePopup;
-(void)openURL(id):arg1 inPopup(BOOL):arg2 ;
-(void)updateCardTitle(id):arg1 andIconUrl(id):arg2 andMediaTrayIconUrl(id):arg3 andPrivacyPolicy(id):arg4 andTermsOfService(id):arg5 ;
-(void)updateAnonymousPublicKey(id):arg1 privateKey(id):arg2 ;
-(void)stopLoading;
-(int)pageMode;
-(BOOL)obscuredByPopup;
-(void)setAutomationAsynchronousOutput(id):arg1 ;
-(void)setStatusBarHidden(BOOL):arg1 transparent(BOOL):arg2 isLight(BOOL):arg3 ;
-(BOOL)canShowPopupCardWithURL(id):arg1 ;
-(void)showSidebar;
-(int)orientationLock;
-(void)setOrientationLock(int):arg1 ;
-(void)performHttpsUpgradeForCardURL(id):arg1 ;
-(void)performRefreshClearingCache(BOOL):arg1 ;
-(void)pageFailed;
-(void)setPageMode(int):arg1 ;
-(void)navigateToUrl(id):arg1 title(id):arg2 icon(id):arg3 clearHistory(BOOL):arg4 ;
-(void)navigateToUrl(id):arg1 requestData(id):arg2 callback(id):arg3 ;
-(void)openExternalUrl(id):arg1 ;
-(void)openWindowWithUrl(id):arg1 callbackPath(id):arg2 callback(id):arg3 ;
-(void)showLoadingSpinner(BOOL):arg1 ;
-(void)pageReady;
-(id)currentUrl;
-(BOOL)isPopup;
-(void)setBrowserViewMode(int):arg1 ;
-(int)browserViewMode;
-(void)closePopup;
-(void)openURL(id):arg1 inPopup(BOOL):arg2 ;
-(void)updateCardTitle(id):arg1 andIconUrl(id):arg2 andMediaTrayIconUrl(id):arg3 andPrivacyPolicy(id):arg4 andTermsOfService(id):arg5 ;
-(void)updateAnonymousPublicKey(id):arg1 privateKey(id):arg2 ;
-(void)stopLoading;
@end
