/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:01 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIWebViewDelegate.h>
#import <NJKWebViewProgressDelegate.h>
#import <UIActionSheetDelegate.h>
#import <PopupViewHostProvider.h>

@interface BrowserViewController : UIViewController <UIWebViewDelegate, NJKWebViewProgressDelegate, UIActionSheetDelegate, PopupViewHostProvider> {
	id<KikImplementation> _kikImpl; 
	id<PopupViewManagerProvider> _popupManager; 
	UIWebView* _webView; 
	NSString* _cardURL; 
	UINavigationItem* _customNavigationItem; 
	UIBarButtonItem* _backButtonItem; 
	PickerRequest* _pickerRequest; 
	BOOL _isPopup; 
	UIBarButtonItem* _moreBarButtonItem; 
	UIButton* _backButton; 
	UIButton* _shareButton; 
	UIButton* _moreButton; 
	UIView* _topBar; 
	URLUILabel* _addressBar; 
	UILabel* _addressLabel; 
	NJKWebViewProgress* _progressProxy; 
	ProgressBarView* _progressBar; 
}
@property (assign,nonatomic,__weak) id<KikImplementation> kikImpl; 				//@synthesize kikImpl=_kikImpl - In the implementation block
@property (nonatomic,retain) UIWebView* webView; 				//@synthesize webView=_webView - In the implementation block
@property (nonatomic,retain) UIBarButtonItem* moreBarButtonItem; 				//@synthesize moreBarButtonItem=_moreBarButtonItem - In the implementation block
@property (nonatomic,retain) UIView* view; 
@property (assign,nonatomic,__weak) UIButton* backButton; 				//@synthesize backButton=_backButton - In the implementation block
@property (assign,nonatomic,__weak) UIButton* shareButton; 				//@synthesize shareButton=_shareButton - In the implementation block
@property (assign,nonatomic,__weak) UIButton* moreButton; 				//@synthesize moreButton=_moreButton - In the implementation block
@property (assign,nonatomic,__weak) UIView* topBar; 				//@synthesize topBar=_topBar - In the implementation block
@property (assign,nonatomic,__weak) URLUILabel* addressBar; 				//@synthesize addressBar=_addressBar - In the implementation block
@property (assign,nonatomic,__weak) UILabel* addressLabel; 				//@synthesize addressLabel=_addressLabel - In the implementation block
@property (assign,nonatomic) BOOL isPopup; 				//@synthesize isPopup=_isPopup - In the implementation block
@property (nonatomic,retain) NJKWebViewProgress* progressProxy; 				//@synthesize progressProxy=_progressProxy - In the implementation block
@property (nonatomic,retain) ProgressBarView* progressBar; 				//@synthesize progressBar=_progressBar - In the implementation block
-(id)popupViewHostURL;
-(void)allViewsWillPop;
-(void)allViewsDidPop;
-(void)setShareButton:(id)arg1;
-(void)reloadWithReset:(BOOL)arg1;
-(id)initWithWebView:(id)arg1 withKikImpl:(id)arg2 andCardURL:(id)arg3 andPopupManager:(id)arg4 andPickerRequest:(id)arg5;
-(void)attachTopBarToNavItem:(id)arg1;
-(void)setupInterfaceWithIsPopup:(BOOL)arg1;
-(void)setIsPopup:(BOOL)arg1;
-(void)setBackButton:(id)arg1;
-(void)setupProgressProxy;
-(void)willRotateToInterfaceOrientation;
-(void)applicationDidEnterForeground;
-(void)updateAddressLabelWithURL:(id)arg1 andUpdateName:(BOOL)arg2;
-(void)updateBackButtonStateWithWebView:(id)arg1;
-(void)adjustViewFramesToOrientation;
-(void)setupProgressBar;
-(void)switchToWhiteColorScheme;
-(id)constructContentMessage;
-(void)webViewProgress:(id)arg1 updateProgress:(float)arg2;
-(void)backButtonClicked;
-(void)shareButtonClicked;
-(void)moreButtonClicked;
-(void)setKikImpl:(id)arg1;
-(void)setMoreBarButtonItem:(id)arg1;
-(void)setAddressBar:(id)arg1;
-(void)setAddressLabel:(id)arg1;
-(void)setProgressProxy:(id)arg1;
-(void)setProgressBar:(id)arg1;
-(void)dealloc;
-(unsigned)supportedInterfaceOrientations;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)setWebView:(id)arg1;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
-(void)webViewDidStartLoad:(id)arg1;
-(void)webViewDidFinishLoad:(id)arg1;
-(void).cxx_destruct;
-(void)setMoreButton:(id)arg1;
-(void)setTopBar:(id)arg1;
@end