/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:47 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NavigationListener.h>

@interface BrowserPlugin : CardsPlugin <NavigationListener> {
	id<BrowserImplementation> _browser; 
	id<CardDescriptionProvider> _cardDescriptionProvider; 
	NSTimer* _refreshTimer; 
	double _refreshTimeout; 
	BOOL _pageReady; 
	BOOL _isPaused; 
	int _pauseFlags; 
	BOOL _isConcealed; 
	NSString* _linkData; 
	BOOL _hasSetCardInfo; 
	NSString* _currentUrl; 
	NSString* _pendingUrlLoad; 
	BOOL _statusBarVisible; 
	BOOL _statusBarTransparent; 
	BOOL _statusBarLightContent; 
	BOOL _backlightTimeoutEnabled; 
	BOOL _openingFromPush; 
	BOOL _isPopup; 
}
@property (assign,nonatomic,__weak) id<BrowserImplementation> browser; 				//@synthesize browser=_browser - In the implementation block
@property (assign,nonatomic,__weak) id<CardDescriptionProvider> cardDescriptionProvider; 				//@synthesize cardDescriptionProvider=_cardDescriptionProvider - In the implementation block
@property (copy) BOOL isPageReady; 				//@synthesize pageReady=_pageReady - In the implementation block
@property (assign,nonatomic,@dynamic) BOOL isPaused; 
@property (assign,nonatomic,@dynamic) int pauseFlags; 
@property (assign,nonatomic,@dynamic) BOOL isConcealed; 
@property (assign,nonatomic) BOOL isPopup; 				//@synthesize isPopup=_isPopup - In the implementation block
@property (nonatomic,copy) NSString* currentUrl; 				//@synthesize currentUrl=_currentUrl - In the implementation block
@property (nonatomic,copy) NSString* pendingUrlLoad; 				//@synthesize pendingUrlLoad=_pendingUrlLoad - In the implementation block
-(void)shouldLoadUrl:(id)arg1;
-(id)initWithBrowser:(id)arg1 cardDescriptionProvider:(id)arg2;
-(void)requestRefresh;
-(void)setPauseFlag:(int)arg1;
-(void)unsetPauseFlag:(int)arg1;
-(void)updateUrl:(id)arg1;
-(void)setIsConcealed:(BOOL)arg1;
-(id)setOrientationLock:(id)arg1;
-(id)initWithBrowser:(id)arg1 cardDescriptionProvider:(id)arg2 refreshTimeout:(double)arg3;
-(id)setCardInfo:(id)arg1;
-(id)pageLoaded:(id)arg1;
-(id)getOrientationLock:(id)arg1;
-(id)openCard:(id)arg1;
-(id)openExternal:(id)arg1;
-(id)navigationAttempted:(id)arg1;
-(id)refreshPlanned:(id)arg1;
-(id)getLastLinkData:(id)arg1;
-(id)setStatusBarVisible:(id)arg1;
-(id)isStatusBarVisible:(id)arg1;
-(id)isDebugModeEnabled:(id)arg1;
-(id)isPopupMode:(id)arg1;
-(id)performHttpsUpgradeCleanup:(id)arg1;
-(id)openPage:(id)arg1;
-(id)setStatusBarTransparent:(id)arg1;
-(void)appEventActive;
-(void)appEventsOpeningFromPush;
-(id)setBacklightTimeoutEnabled:(id)arg1;
-(void)cancelPendingRefresh;
-(void)updateStatusBar;
-(void)setPendingUrlLoad:(id)arg1;
-(void)setPauseFlags:(int)arg1;
-(void)clearCallThrottling;
-(void)setCardDescriptionProvider:(id)arg1;
-(void)setCurrentUrl:(id)arg1;
-(void)setIsPopup:(BOOL)arg1;
-(id)refresh:(id)arg1;
-(void)setBrowser:(id)arg1;
-(void)dealloc;
-(void)setIdleTimerDisabled:(BOOL)arg1;
-(void).cxx_destruct;
-(void)refreshTimeout;
-(void)setIsPaused:(BOOL)arg1;
@end