/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:43 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CacheItem : NSObject {
	NSString* _token; 
	NSDate* _lastAccess; 
}
@property (nonatomic,retain) NSString* token; 				//@synthesize token=_token - In the implementation block
@property (nonatomic,retain) NSDate* lastAccess; 				//@synthesize lastAccess=_lastAccess - In the implementation block
-(void)setLastAccess:(id)arg1;
-(int)compareByAccess:(id)arg1;
-(id)initWithToken:(id)arg1 andLastAccess:(id)arg2;
-(void).cxx_destruct;
-(void)setToken:(id)arg1;
@end