/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:38 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol CardListDelegate
@required
-(void)cardListViewController(id):arg1 didSelectCard(id):arg2 ;
-(void)cardListViewController(id):arg1 didSelectCard(id):arg2 ;
@end
