/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:30 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MediaTrayApp.h>

@interface CardDescriptor : NSObject <MediaTrayApp> {
	NSString* _url; 
	NSString* _icon; 
	NSDate* _dateAdded; 
	NSDate* _lastAccessed; 
	BOOL _permanent; 
	BOOL _isInSidebar; 
	BOOL _showInSidebar; 
	BOOL _internal; 
	BOOL _hasUpdates; 
	BOOL _updatesSeen; 
	BOOL _isSecure; 
	NSMutableDictionary* _permissions; 
	BOOL _isPinned; 
	int _pinnedOrder; 
	BOOL _visited; 
	BOOL _isDebugMode; 
	NSString* _termsOfServiceLink; 
	NSString* _privacyLink; 
	NSData* _anonymousPublicKey; 
	NSData* _anonymousPrivateKey; 
	NSString* _name; 
	BOOL _queuedUpdatesSeen; 
	BOOL _isWebPage; 
	NSString* _displayUrl; 
	NSString* _mediaTrayIcon; 
	NSString* _webPageURL; 
	NSMutableArray* _backstackEntries; 
}
@property (nonatomic,copy) NSString* url; 				//@synthesize url=_url - In the implementation block
@property (nonatomic,copy) NSString* displayUrl; 				//@synthesize displayUrl=_displayUrl - In the implementation block
@property (nonatomic,@dynamic,copy) NSString* name; 
@property (nonatomic,copy) NSString* icon; 				//@synthesize icon=_icon - In the implementation block
@property (nonatomic,copy) NSString* mediaTrayIcon; 				//@synthesize mediaTrayIcon=_mediaTrayIcon - In the implementation block
@property (nonatomic,copy) NSString* termsOfServiceLink; 				//@synthesize termsOfServiceLink=_termsOfServiceLink - In the implementation block
@property (nonatomic,copy) NSString* privacyLink; 				//@synthesize privacyLink=_privacyLink - In the implementation block
@property (nonatomic,retain) NSDate* dateAdded; 				//@synthesize dateAdded=_dateAdded - In the implementation block
@property (nonatomic,retain) NSDate* lastAccessed; 				//@synthesize lastAccessed=_lastAccessed - In the implementation block
@property (assign,nonatomic) BOOL internal; 				//@synthesize internal=_internal - In the implementation block
@property (assign,nonatomic) BOOL hasUpdates; 				//@synthesize hasUpdates=_hasUpdates - In the implementation block
@property (assign,nonatomic) BOOL updatesSeen; 				//@synthesize updatesSeen=_updatesSeen - In the implementation block
@property (assign,nonatomic) BOOL queuedUpdatesSeen; 				//@synthesize queuedUpdatesSeen=_queuedUpdatesSeen - In the implementation block
@property (assign,nonatomic,@dynamic) BOOL isSecure; 
@property (assign,nonatomic) BOOL isPinned; 				//@synthesize isPinned=_isPinned - In the implementation block
@property (assign,nonatomic) int pinnedOrder; 				//@synthesize pinnedOrder=_pinnedOrder - In the implementation block
@property (assign,nonatomic) BOOL visited; 				//@synthesize visited=_visited - In the implementation block
@property (assign,nonatomic) BOOL isInSidebar; 				//@synthesize isInSidebar=_isInSidebar - In the implementation block
@property (assign,nonatomic) BOOL permanent; 				//@synthesize permanent=_permanent - In the implementation block
@property (nonatomic,@dynamic,copy) BOOL showInSidebar; 
@property (assign,nonatomic) BOOL isDebugMode; 				//@synthesize isDebugMode=_isDebugMode - In the implementation block
@property (nonatomic,copy) NSData* anonymousPublicKey; 				//@synthesize anonymousPublicKey=_anonymousPublicKey - In the implementation block
@property (nonatomic,copy) NSData* anonymousPrivateKey; 				//@synthesize anonymousPrivateKey=_anonymousPrivateKey - In the implementation block
@property (assign,nonatomic) BOOL isWebPage; 				//@synthesize isWebPage=_isWebPage - In the implementation block
@property (nonatomic,copy) NSString* webPageURL; 				//@synthesize webPageURL=_webPageURL - In the implementation block
@property (nonatomic,retain) NSMutableArray* backstackEntries; 				//@synthesize backstackEntries=_backstackEntries - In the implementation block
+(id)memesCard;
+(id)imageSearchCard;
+(id)youtubeCard;
+(id)sketchCard;
+(id)stickerCard;
+(id)topSitesCard;
+(id)funnyPicsCard;
+(id)squaredCard;
+(id)captureCard;
+(id)cardForDictionary:(id)arg1;
-(id)initWithURL:(id)arg1 andName:(id)arg2 andIcon:(id)arg3;
-(id)initWithURL:(id)arg1 andName:(id)arg2 andIcon:(id)arg3 andMediaTrayIcon:(id)arg4;
-(void)setIsWebPage:(BOOL)arg1;
-(void)setIsInSidebar:(BOOL)arg1;
-(void)setWebPageURL:(id)arg1;
-(void)setMediaTrayIcon:(id)arg1;
-(void)setPermanent:(BOOL)arg1;
-(int)appType;
-(id)permissionNames;
-(void)resetPermissions;
-(void)mergeWithCard:(id)arg1;
-(void)setAnonymousPublicKey:(id)arg1;
-(void)setAnonymousPrivateKey:(id)arg1;
-(void)setPrivacyLink:(id)arg1;
-(void)setTermsOfServiceLink:(id)arg1;
-(void)setBackstackEntries:(id)arg1;
-(void)setIsSecure:(BOOL)arg1;
-(int)permissionStateForName:(id)arg1;
-(void)setLastAccessed:(id)arg1;
-(void)setUpdatesSeen:(BOOL)arg1;
-(void)setQueuedUpdatesSeen:(BOOL)arg1;
-(void)setPinnedOrder:(int)arg1;
-(void)setIsDebugMode:(BOOL)arg1;
-(id)initWithURL:(id)arg1 andName:(id)arg2 andIcon:(id)arg3 andMediaTrayIcon:(id)arg4 andInternal:(BOOL)arg5;
-(id)initWithURL:(id)arg1 andName:(id)arg2 andIcon:(id)arg3 andMediaTrayIcon:(id)arg4 andIsPermanent:(BOOL)arg5 andDateAdded:(id)arg6;
-(id)initWithURL:(id)arg1 andName:(id)arg2 andIcon:(id)arg3 andMediaTrayIcon:(id)arg4 andInternal:(BOOL)arg5 andDateAdded:(id)arg6;
-(id)initWithURL:(id)arg1 andName:(id)arg2 andIcon:(id)arg3 andMediaTrayIcon:(id)arg4 andDateAdded:(id)arg5 andLastAccessed:(id)arg6 andIsPermanent:(BOOL)arg7 andIsInSidebar:(BOOL)arg8 andIsSecure:(BOOL)arg9 andPermissions:(id)arg10 andInternal:(BOOL)arg11 andPinned:(BOOL)arg12 andPinnedOrder:(int)arg13 andHasUpdates:(BOOL)arg14 andUpdatesSeen:(BOOL)arg15 andVisited:(BOOL)arg16 andIsDebugMode:(BOOL)arg17 andTOSLink:(id)arg18 andPrivacyLink:(id)arg19 andAnonPublicKey:(id)arg20 andAnonPrivateKey:(id)arg21 andIsWebPage:(BOOL)arg22 andWebPageURL:(id)arg23 andBackstackEntries:(id)arg24;
-(id)initWithURL:(id)arg1 andName:(id)arg2 andIcon:(id)arg3 andInternal:(BOOL)arg4;
-(BOOL)isEqualToCardDescriptor:(id)arg1;
-(id)dictionaryForCard;
-(void)resetPermissionStateForName:(id)arg1;
-(void)setPermissionForName:(id)arg1 allowed:(BOOL)arg2;
-(void)setPermissionForName:(id)arg1 state:(int)arg2;
-(BOOL)hasMediaTrayIcon;
-(void)removeAllBackstackEntries;
-(void)setBackstackEntriesWithURLs:(id)arg1;
-(void)setDisplayUrl:(id)arg1;
-(void)setHasUpdates:(BOOL)arg1;
-(void)setInternal:(BOOL)arg1;
-(void)setIsPinned:(BOOL)arg1;
-(id)appName;
-(id)description;
-(void)setName:(id)arg1;
-(void)setIcon:(id)arg1;
-(void)setUrl:(id)arg1;
-(void).cxx_destruct;
-(void)cleanup;
-(void)setVisited:(BOOL)arg1;
-(void)setDateAdded:(id)arg1;
-(id)iconURL;
-(id)appID;
@end