/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:46 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <RetryStrategyDelegate.h>

@interface CardsSearchManager : NSObject <RetryStrategyDelegate> {
	double _suggestUpdateInterval; 
	double _suggestLastUpdated; 
	NSTimer* _suggestUpdateTimer; 
	NSString* _sessionID; 
	ExponentialBackoffRetryStrategy* _suggestRetryStrategy; 
	NSArray* _suggestedResults; 
	KikStorage* _storage; 
	int _suggestState; 
}
@property (nonatomic,retain) NSArray* suggestedResults; 				//@synthesize suggestedResults=_suggestedResults - In the implementation block
@property (nonatomic,copy) KikStorage* storage; 				//@synthesize storage=_storage - In the implementation block
@property (nonatomic,copy) int suggestState; 				//@synthesize suggestState=_suggestState - In the implementation block
@property (nonatomic,copy) NSString* sessionID; 
-(id)initWithStorage:(id)arg1;
-(void)retryStrategyDidAdviseRetry:(id)arg1;
-(void)search:(id)arg1 withResultCallback:(id)arg2;
-(void)getSuggestedResultsWithResultCallback:(id)arg1;
-(void)clearSuggestions;
-(void)sendSponsoredViewEventWithCampaignID:(id)arg1;
-(void)sendSponsoredClickEventWithCampaignID:(id)arg1;
-(id)searchResultsFromArrayPlist:(id)arg1;
-(void)setSuggestedResults:(id)arg1;
-(void)checkSuggestions;
-(id)searchResultsFromRawArray:(id)arg1;
-(BOOL)deleteRawSearchResultsFromArrayPlist:(id)arg1;
-(void)suggestTimerFired:(id)arg1;
-(void)setSuggestState:(int)arg1;
-(BOOL)saveRawSearchResultsArray:(id)arg1 toPlist:(id)arg2;
-(void)updateSuggestionsWithCallback:(id)arg1;
-(void).cxx_destruct;
-(void)appDidBecomeActive:(id)arg1;
@end