/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:27 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CardDescriptorSorter : NSObject {
}
+(id)sortCardsByDate:(id)arg1;
+(id)sortCardsByPinnedOrder:(id)arg1;
+(id)sortCardsByLastAccessed:(id)arg1;
+(id)sortCardsByName:(id)arg1;
+(id)sortCardsByDateDescending:(id)arg1;
@end