/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:48 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CardsBridgePlugin : CardsPlugin {
	CardsPluginRegistry* _registry; 
	id<CardsBoundEventCallback> _callback; 
}
-(id)namespacedMethodName:(id)arg1;
-(id)initWithPluginRegistry:(id)arg1 callback:(id)arg2;
-(id)requestVersion:(id)arg1;
-(id)requestPlugin:(id)arg1;
-(id)log:(id)arg1;
-(void).cxx_destruct;
@end