/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:06 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PhotoHandler.h>
#import <UIImagePickerControllerDelegate.h>
#import <UIActionSheetDelegate.h>
#import <UIAlertViewDelegate.h>

@interface CardsPhotoHandler : NSObject <PhotoHandler, UIImagePickerControllerDelegate, UIActionSheetDelegate, UIAlertViewDelegate> {
	id _pendingCallback; 
	id _pickerCallback; 
	id _photoCallback; 
	UIViewController* _parentViewController; 
	LoadingSpinnerKikViewController* _spinner; 
	int _maxResults; 
	int _minResults; 
	UIImage* _pendingImage; 
	UIAlertView* _pendingAlertView; 
}
@property (assign,nonatomic,__weak) UIViewController* parentViewController; 				//@synthesize parentViewController=_parentViewController - In the implementation block
-(id)initWithParentController:(id)arg1 spinner:(id)arg2;
-(void)selectPhotosFromSource:(int)arg1 callback:(id)arg2 photoCallback:(id)arg3 atMost:(int)arg4 atLeast:(int)arg5;
-(void)saveImage:(id)arg1 callback:(id)arg2;
-(void)requestSaveToGalleryAccessCallback:(id)arg1;
-(void)takeCameraPhotoCallback:(id)arg1 photoCallback:(id)arg2;
-(void)selectGalleryPhotosCallback:(id)arg1 photoCallback:(id)arg2 atMost:(int)arg3 atLeast:(int)arg4;
-(void)didSaveImage:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void*)arg3;
-(void)alertViewCasdncel:(id)arg1;
-(void)dealloc;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)setParentViewController:(id)arg1;
-(void)imagePickerControllerDidCancel:(id)arg1;
-(void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
-(void).cxx_destruct;
-(void)alertView:(id)arg1 willDismissWithButtonIndex:(int)arg2;
@end