/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:09 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <RetryStrategyDelegate.h>

@interface CardPersistenceManager : NSObject <RetryStrategyDelegate> {
	NSObject<RetryStrategy>* _retryStrategy; 
	SecureXDataManager* _xDataManager; 
	CardManager* _cardManager; 
	CardsPushManager* _cardsPushManager; 
}
@property (nonatomic,copy) SecureXDataManager* xDataManager; 				//@synthesize xDataManager=_xDataManager - In the implementation block
@property (nonatomic,copy) NSObject<RetryStrategy>* retryStrategy; 				//@synthesize retryStrategy=_retryStrategy - In the implementation block
@property (assign,nonatomic,__weak) CardManager* cardManager; 				//@synthesize cardManager=_cardManager - In the implementation block
@property (assign,nonatomic,__weak) CardsPushManager* cardsPushManager; 				//@synthesize cardsPushManager=_cardsPushManager - In the implementation block
+(int)xCardPermissionNameForPermissionName:(id)arg1;
+(int)xCardPermissionStateForCardDescriptorPermissionState:(int)arg1;
+(id)xCardPermissionForCardDescriptor:(id)arg1 permissionName:(id)arg2;
+(id)permissionNameForXCardPermissionName:(int)arg1;
+(int)permissionStateForXCardPermissionState:(int)arg1;
+(id)xCardDescriptorFromCardDescriptor:(id)arg1 token:(id)arg2;
+(id)xCardPinnedListFromCardURLHashArray:(id)arg1;
+(id)cardURLHashArrayFromXCardPinnedList:(id)arg1;
+(id)cardDescriptorFromXCardDescriptor:(id)arg1 token:(id*)arg2;
-(void)retryStrategyDidAdviseRetry:(id)arg1;
-(id)initWithSecureXDataManager:(id)arg1 retryStrategy:(id)arg2;
-(void)setCardManager:(id)arg1;
-(void)setCardsPushManager:(id)arg1;
-(void)xDataSetCardPinnedList:(id)arg1;
-(void)fetchCards;
-(void)xDataAddOrUpdateCard:(id)arg1;
-(void)xDataDeleteCard:(id)arg1;
-(void)xDataDeleteAllCards;
-(id)recordSetFromCardDescriptor:(id)arg1;
-(void)xDataDeletePinnedCardList;
-(void)fetchCardPinnedListWithCallback:(id)arg1;
-(void)fetchCardsDescriptorsWithPinnedURLHashArray:(id)arg1 withCallback:(id)arg2;
-(BOOL)isCardPinned:(id)arg1 withOrder:(int*)arg2 pinnedURLHashArray:(id)arg3;
-(BOOL)cardInflatedFromXData:(id)arg1 isEqualToCardInStorage:(id)arg2;
-(void)xDataDeleteScrambledCard:(id)arg1;
-(void)reset;
-(void).cxx_destruct;
@end