/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:25 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIWebViewDelegate.h>
#import <UIAlertViewDelegate.h>

@interface CardWindowViewController : KikViewController <UIWebViewDelegate, UIAlertViewDelegate> {
	CardsWebView* _webView; 
	NSString* _url; 
	NSString* _targetUrl; 
	BOOL _sslError; 
	id _callback; 
	UIView* _webContainer; 
	UILabel* _urlLabel; 
	UIImageView* _lockIconImage; 
	KikNavigationBar* _navigationBar; 
}
@property (assign,nonatomic,__weak) UIView* webContainer; 				//@synthesize webContainer=_webContainer - In the implementation block
@property (assign,nonatomic,__weak) UILabel* urlLabel; 				//@synthesize urlLabel=_urlLabel - In the implementation block
@property (assign,nonatomic,__weak) UIImageView* lockIconImage; 				//@synthesize lockIconImage=_lockIconImage - In the implementation block
@property (assign,nonatomic,__weak) KikNavigationBar* navigationBar; 				//@synthesize navigationBar=_navigationBar - In the implementation block
@property (nonatomic,copy) id callback; 				//@synthesize callback=_callback - In the implementation block
-(id)initWithUrl:(id)arg1 targetUrl:(id)arg2 callback:(id)arg3;
-(void)updateUrl:(id)arg1;
-(void)callCallbackCancel;
-(void)callCallbackSuccess:(id)arg1;
-(void)setWebContainer:(id)arg1;
-(void)setUrlLabel:(id)arg1;
-(void)setLockIconImage:(id)arg1;
-(void)donePressed:(id)arg1;
-(void)setCallback:(id)arg1;
-(void)dealloc;
-(void)didReceiveMemoryWarning;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(void)setNavigationBar:(id)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
-(void)webViewDidStartLoad:(id)arg1;
-(void)webViewDidFinishLoad:(id)arg1;
-(void).cxx_destruct;
-(void)updateTitle;
@end