/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:48 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CardsSearchResult : NSObject {
	NSString* _url; 
	NSString* _title; 
	NSString* _icon; 
	NSNumber* _isSponsored; 
	NSString* _campaignID; 
}
@property (nonatomic,copy) NSString* url; 				//@synthesize url=_url - In the implementation block
@property (nonatomic,copy) NSString* title; 				//@synthesize title=_title - In the implementation block
@property (nonatomic,copy) NSString* icon; 				//@synthesize icon=_icon - In the implementation block
@property (nonatomic,retain) NSNumber* isSponsored; 				//@synthesize isSponsored=_isSponsored - In the implementation block
@property (nonatomic,copy) NSString* campaignID; 				//@synthesize campaignID=_campaignID - In the implementation block
-(void)setIsSponsored:(id)arg1;
-(void)setCampaignID:(id)arg1;
-(void)setTitle:(id)arg1;
-(void)setIcon:(id)arg1;
-(void)setUrl:(id)arg1;
-(void).cxx_destruct;
@end