/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:53 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CardsWebView : UIWebView {
}
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
@end