/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:29 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol CardContainer
@required
-(id)cardForURL(id):arg1 ;
-(id)addOrUpdateCard(id):arg1 ;
-(void)deleteCardWithURL(id):arg1 ;
-(void)deleteAllCards;
-(id)allCards;
-(id)addOrUpdateCard(id):arg1 withCustomMerge(id):arg2 ;
-(void)deleteCard(id):arg1 ;
-(id)cardForURL(id):arg1 ;
-(id)addOrUpdateCard(id):arg1 ;
-(void)deleteCardWithURL(id):arg1 ;
-(void)deleteAllCards;
-(id)allCards;
-(id)addOrUpdateCard(id):arg1 withCustomMerge(id):arg2 ;
-(void)deleteCard(id):arg1 ;
@end
