/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:29 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CardManager : NSObject {
	id<CardContainer> _cards; 
	NSMutableArray* _webPageURLsToDelete; 
	NSMutableDictionary* _cardWriteLocks; 
	KikStorage* _storage; 
	CardPersistenceManager* _cardPersistenceManager; 
}
@property (nonatomic,copy) KikStorage* storage; 				//@synthesize storage=_storage - In the implementation block
@property (nonatomic,copy) CardPersistenceManager* cardPersistenceManager; 				//@synthesize cardPersistenceManager=_cardPersistenceManager - In the implementation block
-(void)addDefaultCards;
-(id)allRecentCards;
-(id)allPinnedCards;
-(id)cardForURL:(id)arg1;
-(void)addOrUpdateCard:(id)arg1;
-(void)addOrUpdateCard:(id)arg1 xData:(BOOL)arg2 withCustomMerge:(id)arg3;
-(id)initWithCardContainer:(id)arg1 andCardPersistenceManager:(id)arg2 andStorage:(id)arg3;
-(void)authenticationDidChange:(id)arg1;
-(void)upgradeCardsToXData;
-(void)removeMoreCard;
-(void)addPreinstalledCards;
-(BOOL)updateCardForURL:(id)arg1 with:(id)arg2;
-(BOOL)cardHasBeenDowngradedToWebPage:(id)arg1;
-(id)downgradeCard:(id)arg1 toWebPageWithWebPageURL:(id)arg2;
-(id)upgradeCard:(id)arg1 fromWebPageURL:(id)arg2;
-(void)performHttpsUpgradeForCardURL:(id)arg1;
-(id)allKikCardsWithCondition:(id)arg1;
-(id)allPinnedCardsWithCondition:(id)arg1;
-(id)allRecentCardsWithCondition:(id)arg1;
-(void)updatePinnedCardOrder:(id)arg1;
-(id)sortedKikCardURLsWithSortCallback:(id)arg1;
-(id)sortedPinnedCardURLsWithSortCallback:(id)arg1;
-(id)sortedRecentCardURLsWithSortCallback:(id)arg1;
-(void)deleteCardWithURL:(id)arg1;
-(void)cardsFetched:(id)arg1;
-(void)deleteAllCards;
-(id)allNonInternalCardsInSidebar;
-(id)sortedPinnedCardDescriptorList;
-(id)allCards;
-(id)allCardsWithCondition:(id)arg1;
-(void)addOrUpdateCard:(id)arg1 withCustomMerge:(id)arg2;
-(void)deleteCard:(id)arg1 andUpdateXData:(BOOL)arg2;
-(void)deleteCard:(id)arg1;
-(id)allKikCards;
-(void)dealloc;
-(void)reset;
-(void).cxx_destruct;
-(void)setup;
@end