/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:09 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CardWhitelistManager : NSObject {
	NSMutableArray* _whitelistedDomains; 
}
-(id)initWithDefaultCardURLs;
-(void)addWhitelistDomain:(id)arg1;
-(void)addDefaultCardWhitelistURLs;
-(BOOL)isCardDomainWhitelisted:(id)arg1;
-(BOOL)isCardURLWhitelisted:(id)arg1;
-(id)init;
-(void).cxx_destruct;
@end