/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:04:02 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ChallengeProblemSolver : NSObject {
}
-(void)solve:(id)arg1 withOptions:(id)arg2 callback:(id)arg3;
-(id)completeHashCash:(id)arg1 count:(int)arg2;
-(id)completeWordIndexProblem:(id)arg1 atIndex:(int)arg2;
@end