/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:31:21 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Config : NSObject {
	BOOL _isProtected; 
	BOOL useCustomEncryption; 
	unsigned char customEncryptionVersion; 
	NSString* configurationName; 
	NSString* serverName; 
	NSString* xmppDomain; 
	NSString* profilePicsUrl; 
	NSString* clientMetricsUrl; 
	NSString* chunkUploadUrl; 
	NSString* chunkDownloadUrl; 
	NSString* serverPublicKey; 
	NSString* _serverDeviceInfoPublicKey; 
	int _serverDeviceInfoKeyVersion; 
}
@property (nonatomic,copy) NSString* configurationName; 
@property (nonatomic,copy) NSString* serverName; 
@property (nonatomic,copy) NSString* xmppDomain; 
@property (nonatomic,copy) NSString* profilePicsUrl; 
@property (nonatomic,copy) NSString* clientMetricsUrl; 
@property (nonatomic,copy) NSString* chunkUploadUrl; 
@property (nonatomic,copy) NSString* chunkDownloadUrl; 
@property (nonatomic,copy) NSString* serverPublicKey; 
@property (assign,nonatomic) unsigned char customEncryptionVersion; 
@property (nonatomic,copy) NSString* serverDeviceInfoPublicKey; 				//@synthesize serverDeviceInfoPublicKey=_serverDeviceInfoPublicKey - In the implementation block
@property (assign,nonatomic) int serverDeviceInfoKeyVersion; 				//@synthesize serverDeviceInfoKeyVersion=_serverDeviceInfoKeyVersion - In the implementation block
@property (nonatomic) BOOL isProtected; 				//@synthesize isProtected=_isProtected - In the implementation block
@property (assign,nonatomic) BOOL useCustomEncryption; 
+(id)activeConfiguration;
+(id)configForName:(id)arg1;
+(id)piranha;
+(id)beta;
+(void)setActiveConfiguration:(id)arg1;
+(id)availableConfigurations;
+(void)initialize;
+(id)production;
-(void)setServerName:(id)arg1;
-(void)setUseCustomEncryption:(BOOL)arg1;
-(void)setXmppDomain:(id)arg1;
-(void)setConfigurationName:(id)arg1;
-(void)setProfilePicsUrl:(id)arg1;
-(void)setChunkUploadUrl:(id)arg1;
-(void)setChunkDownloadUrl:(id)arg1;
-(void)setClientMetricsUrl:(id)arg1;
-(void)setServerPublicKey:(id)arg1;
-(void)setCustomEncryptionVersion:(unsigned char)arg1;
-(void)setServerDeviceInfoPublicKey:(id)arg1;
-(void)setServerDeviceInfoKeyVersion:(int)arg1;
-(id)init;
-(id)initWithConfig:(id)arg1;
@end