/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:02:01 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol HPGrowingTextViewDelegate
@optional
-(BOOL)growingTextViewShouldBeginEditing:(id)arg1 ;
-(BOOL)growingTextViewShouldEndEditing:(id)arg1 ;
-(void)growingTextViewDidBeginEditing:(id)arg1 ;
-(void)growingTextViewDidEndEditing:(id)arg1 ;
-(BOOL)growingTextView:(id)arg1 shouldChangeTextInRange:()arg2 replacementText:(_)arg3 ;
-(void)growingTextViewDidChange:(id)arg1 ;
-(void)growingTextViewDidChangeText:(id)arg1 ;
-(void)growingTextView:(id)arg1 willChangeHeight:(float)arg2 ;
-(void)growingTextView:(id)arg1 didChangeHeight:(float)arg2 ;
-(void)growingTextViewDidChangeSelection:(id)arg1 ;
-(BOOL)growingTextViewShouldReturn:(id)arg1 ;
@end

@protocol ContentMessageViewDelegate
@required
-(void)contentMessageViewButtonClicked:(id)arg1 ;
-(void)contentMessageViewButtonClicked:(id)arg1 ;
@end
