/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:09 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ContentUploadDescriptor : ContentDescriptor {
	int _chunkCount; 
	int _progressOffset; 
	int _byteOffset; 
	int _uploadOffset; 
	NSString* _mimeType; 
}
@property (assign,nonatomic) int chunkNumber; 
@property (nonatomic,copy) int uploadPosition; 
@property (nonatomic,copy) int chunkCount; 
@property (nonatomic,copy) NSString* mimeType; 				//@synthesize mimeType=_mimeType - In the implementation block
@property (nonatomic,copy) int currentChunkSize; 
@property (nonatomic,copy) int progressBytes; 
@property (nonatomic,copy) float progressPercentage; 
-(id)populateDictionary;
-(_Bool)isUpload;
-(id)initWithContentId:(id)arg1 contentType:(id)arg2 appId:(id)arg3 length:(int)arg4;
-(void)setChunkNumber:(int)arg1;
-(void)updateProgressWithNewBytes:(int)arg1;
-(void)resetUploadOffset;
-(id)initWithDictionary:(id)arg1;
-(void).cxx_destruct;
-(void)setMimeType:(id)arg1;
@end