/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:15:24 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import "UploadManagerDelegate.h"
#import "DownloadManagerDelegate.h"
 #import "UploadManager.h"
 #import "DownloadManager.h"
 #import "FastLRUCache.h"
 #import "OS_dispatch_queue.h"

@interface ContentManager : NSObject <UploadManagerDelegate, DownloadManagerDelegate> {
	Config* _config; 
	KikCredentials* _credentials; 
	id<UploadManager> _uploadManager; 
	id<DownloadManager> _downloadManager; 
	FastLRUCache* _dataCache; 
	FastLRUCache* _metadataCache; 
	NSMutableDictionary* _contentItemCache; 
	//NSObject<OS_dispatch_queue>* _dispatchQueue; 
	KikNetwork* _network; 
	KikStorage* _storage; 
}
-(void)authorize:(id)arg1;
-(void)onPasswordChanged:(id)arg1;
-(id)contentItemForID:(id)arg1;
-(id)resumeUploadForContentWithID:(id)arg1;
-(id)uploadContentWithID:(id)arg1 appID:(id)arg2 data:(id)arg3;
-(id)stubContentItemForKikAPIMessage:(id)arg1;
-(BOOL)contentItemIsUpload:(id)arg1;
-(id)initWithConfig:(id)arg1 credentials:(id)arg2 network:(id)arg3 storage:(id)arg4;
-(void)setupAfterFreshLogin:(BOOL)arg1;
-(void)onNetworkAvailable:(id)arg1;
-(void)checkDefaultsUpgradeWithDataStoragePath:(id)arg1 andMetadataStoragePath:(id)arg2;
-(id)initWithConfig:(id)arg1 credentials:(id)arg2 uploadManager:(id)arg3 downloadManager:(id)arg4 metadataCache:(id)arg5 dataCache:(id)arg6 dispatchQueue:(id)arg7 network:(id)arg8 storage:(id)arg9;
-(id)downloadContentWithID:(id)arg1 appID:(id)arg2 url:(id)arg3;
-(id)contentItemForID:(id)arg1 requireData:(BOOL)arg2;
-(id)internalAppIDs;
-(void)resumeUploading;
-(void)uploadManager:(id)arg1 didUploadContent:(id)arg2;
-(void)uploadManager:(id)arg1 didFailToUploadContent:(id)arg2;
-(void)downloadManager:(id)arg1 didDownloadContent:(id)arg2;
-(void)downloadManager:(id)arg1 didFailToDownloadContent:(id)arg2;
-(void)dealloc;
@end