/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:12 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "ContentDescriptor.h"

@interface ContentDownloadDescriptor : ContentDescriptor {
	NSString* _platform; 
	NSString* _url; 
}
@property (nonatomic,copy,copy) NSString* platform; 				//@synthesize platform=_platform - In the implementation block
@property (nonatomic,copy,copy) NSString* url; 				//@synthesize url=_url - In the implementation block
@property (nonatomic) _Bool isLegacy; 
-(id)populateDictionary;
-(_Bool)isUpload;
-(id)initWithDictionary:(id)arg1;
@end