/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:13 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ContentDescriptor : NSObject {
	NSString* _appId; 
	NSString* _contentId; 
	NSString* _contentType; 
	NSString* _transmission; 
	int _length; 
	float _progress; 
	int _state; 
	int _retries; 
}
@property (nonatomic,copy,copy) NSString* appId; 				//@synthesize appId=_appId - In the implementation block
@property (nonatomic,copy,copy) NSString* contentType; 				//@synthesize contentType=_contentType - In the implementation block
@property (nonatomic,copy,copy) NSString* contentId; 				//@synthesize contentId=_contentId - In the implementation block
@property (nonatomic,copy,copy) NSString* transmission; 				//@synthesize transmission=_transmission - In the implementation block
@property (nonatomic) _Bool isUpload; 
@property (nonatomic) int length; 				//@synthesize length=_length - In the implementation block
@property (assign,nonatomic) int state; 				//@synthesize state=_state - In the implementation block
@property (assign,nonatomic) int remainingRetries; 				//@synthesize retries=_retries - In the implementation block
-(id)initWithContentId:(id)arg1 contentType:(id)arg2 appId:(id)arg3 length:(int)arg4 transmissionType:(id)arg5;
-(id)populateDictionary;
-(void)setRemainingRetries:(int)arg1;
-(id)initWithDictionary:(id)arg1;
-(void)setState:(int)arg1;
@end