/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:46 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ConversationListCell : HybridTableCell {
	KikChat* _chat; 
	KikAPIMessage* _lastMessageContent; 
	NSLayoutConstraint* _iconWidthConstraint; 
	NSLayoutConstraint* _messageLabelLeftConstraint; 
	NSLayoutConstraint* _dateLabelWidthConstraint; 
	NSLayoutConstraint* _separatorLineHeightConstraint; 
	NSLayoutConstraint* _separatorLineTopConstraint; 
	NSLayoutConstraint* _topSeparatorLineHeightConstraint; 
	ProfilePictureImageView* _profilePictureView; 
	UIImageView* _unreadMessageDot; 
	UILabel* _title; 
	UILabel* _date; 
	ChatCellHybridSmileyLabel* _message; 
	UIImageView* _status; 
	UIImageView* _icon; 
	UIView* _separatorLine; 
	NSLayoutConstraint* _separatorLineLeadingConstraint; 
	UIView* _topSeparatorLine; 
}
@property (nonatomic,@dynamic,retain) KikChat* chat; 
@property (nonatomic,retain) ProfilePictureImageView* profilePictureView; 				//@synthesize profilePictureView=_profilePictureView - In the implementation block
@property (nonatomic,retain) UIImageView* unreadMessageDot; 				//@synthesize unreadMessageDot=_unreadMessageDot - In the implementation block
@property (nonatomic,retain) UILabel* title; 				//@synthesize title=_title - In the implementation block
@property (nonatomic,retain) UILabel* date; 				//@synthesize date=_date - In the implementation block
@property (nonatomic,retain) ChatCellHybridSmileyLabel* message; 				//@synthesize message=_message - In the implementation block
@property (nonatomic,retain) UIImageView* status; 				//@synthesize status=_status - In the implementation block
@property (nonatomic,retain) UIImageView* icon; 				//@synthesize icon=_icon - In the implementation block
@property (nonatomic,retain) UIView* separatorLine; 				//@synthesize separatorLine=_separatorLine - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint* separatorLineLeadingConstraint; 				//@synthesize separatorLineLeadingConstraint=_separatorLineLeadingConstraint - In the implementation block
@property (nonatomic,retain) UIView* topSeparatorLine; 				//@synthesize topSeparatorLine=_topSeparatorLine - In the implementation block
+(float)height;
-(void)updateMessageStatus;
-(void)updateMessageLabel;
-(void)updateMessageIcon;
-(void)setProfilePictureView:(id)arg1;
-(void)setUnreadMessageDot:(id)arg1;
-(void)setSeparatorLineLeadingConstraint:(id)arg1;
-(void)setTopSeparatorLine:(id)arg1;
-(void)setTitle:(id)arg1;
-(void)awakeFromNib;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setDate:(id)arg1;
-(void)setIcon:(id)arg1;
-(void)setMessage:(id)arg1;
-(void).cxx_destruct;
-(void)setStatus:(id)arg1;
-(void)setChat:(id)arg1;
-(void)setSeparatorLine:(id)arg1;
@end