/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 120138 AM Mountain Daylight Time
 * Operating System Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol ConversationManagerProvider
@required
-(id)conversationForID:(id)arg1 ;
-(id)createConversationForID:(id)arg1 ;
-(void)sendContentMessage:(id)arg1 toConversation:(id)arg2 ;
-(void)sendTextMessage:(id)arg1 toConversation:(id)arg2 ;
-(void)sendReadReceiptsForConversationID:(id)arg1 ;
-(id)changeConversationID:(id)arg1 toID:(id)arg2 ;
-(BOOL)deleteConversationForID:(id)arg1 ;
-(id)conversationForID:(id)arg1 ;
-(id)createConversationForID:(id)arg1 ;
-(void)sendContentMessage:(id)arg1 toConversation:(id)arg2 ;
-(void)sendTextMessage:(id)arg1 toConversation:(id)arg2 ;
-(void)sendReadReceiptsForConversationID:(id)arg1 ;
-(id)changeConversationID:(id)arg1 toID:(id)arg2 ;
-(BOOL)deleteConversationForID:(id)arg1 ;
@end
