/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:03 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <ConversationListDelegate.h>

@interface ConversationsViewController : HybridViewController <ConversationListDelegate> {
	ToolbarSpinner* _toolbarSpinner; 
	UIView* _noConversationsView; 
	unsigned _cachedNumberOfOpenConversations; 
	UIAlertView* _lowCoverageAlert; 
	UIAlertView* _initialMatchingAlert; 
	UIAlertView* _dontAllowMatchingAlert; 
	BOOL _needToReworkNavigationController; 
	BOOL _canMoveToIgnoredConversations; 
	BOOL _userJustRegistered; 
	BOOL _userJustRegisteredOrLoggedIn; 
	BOOL _optIn; 
	BOOL _shouldSendMatchingIQ; 
	BOOL _canSendMatchingIQ; 
	BOOL _shouldSetAddressBookStatus; 
	NSLayoutConstraint* _imageTopLayoutConstraint; 
	UIButton* _settingsButton; 
	UIButton* _talkToButton; 
	ThresholdTimer* _updateMissedConversationsCountThresholdTimer; 
	BOOL _makeFooterHighlighted; 
	TalkedToConversationListViewController* _conversationListController; 
	KikAPIMessage* _messageAttach; 
}
@property (nonatomic,retain) TalkedToConversationListViewController* conversationListController; 				//@synthesize conversationListController=_conversationListController - In the implementation block
@property (nonatomic,retain) KikAPIMessage* messageAttach; 				//@synthesize messageAttach=_messageAttach - In the implementation block
-(void)leftNavigationButtonPressed:(id)arg1;
-(void)setMessageAttach:(id)arg1;
-(void)setConversationListController:(id)arg1;
-(float)updateConversationListInsetsInOrientation:(int)arg1;
-(void)messageReceived:(id)arg1;
-(void)didSelectChat:(id)arg1;
-(void)didDeleteChat:(id)arg1 atIndexPath:(id)arg2;
-(void)didUpdateContent;
-(void)didTapFooter;
-(void)rightNavigationButtonPressed:(id)arg1;
-(void)onXmppConnected:(id)arg1;
-(void)onUserRegisteredOrJustLoggedIn:(id)arg1;
-(void)onMissedConversationsCountUpdated:(id)arg1;
-(void)qosProcessed:(id)arg1;
-(void)connectionStateChanged:(id)arg1;
-(void)showLowCoverageAlert;
-(void)hideLowCoverageAlert;
-(void)onUserDetailsLoaded:(id)arg1;
-(void)listenForUserDetails:(BOOL)arg1;
-(void)updateMissedConversationsCount;
-(void)showWelcomeScreenIfNecessary;
-(void)showInitialMatchingAlertView;
-(void)sendMatchingIQ;
-(void)determineFooterVisibilityWithTalkedToCount:(unsigned)arg1 andNewPeopleCount:(unsigned)arg2 andSpamCount:(unsigned)arg3;
-(void)forceUpdateMissedConversationsCount;
-(void)showMissedConversationsButton;
-(void)hideMissedConversationsButton;
-(void)showDontAllowMatchingAlertView;
-(unsigned)supportedInterfaceOrientations;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(void).cxx_destruct;
@end