/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, July 6, 2014 at 2:43:34 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import "AuthorizationHandler.h"
 #import "KikHttpClientController.h"
 #import "KikStorage.h"
 #import "KikNetwork.h"
 #import "UserManager.h"
 #import "AccountManager.h"
 #import "ChatManager.h"
 #import "AttachmentManager.h"
 #import "Config.h"
 #import "ContentManager.h"
 #import "CardManager.h"
 #import "CardWhitelistManager.h"
 #import "CertificateManager.h"
 #import "MetricsManager.h"
 #import "CardsPushManager.h"
 #import "KikTickerManager.h"
 #import "NetworkNotifier.h"
 #import "SecureXDataManager.h"
 #import "IAPManager.h"
 #import "StickerManager.h"
 #import "CoreDataMessageManager.h"
 #import "CoreDataConversationManager.h"
 #import "URLDataManager.h"
 #import "AddressBookManager.h"
 #import "CardsSearchManager.h"
 #import "DeviceManager.h"

@interface Core : NSObject <AuthorizationHandler> {
	KikHttpClientController* _http; 
	KikNetwork* _network; 
	KikStorage* _storage; 
	UserManager* _userManager; 
	AccountManager* _accountManager; 
	ChatManager* _chatManager; 
	AttachmentManager* _attachmentManager; 
	AudioManager* _audioManager; 
	Config* _config; 
	ContentManager* _contentManager; 
	CardManager* _cardManager; 
	CardWhitelistManager* _cardWhitelistManager; 
	CertificateManager* _certificateManager; 
	MetricsManager* _metricsManager; 
	CardsPushManager* _cardsPushManager; 
	KikTickerManager* _tickerManager; 
	NetworkNotifier* _networkNotifier; 
	SecureXDataManager* _xDataManager; 
	IAPManager* _iapManager; 
	StickerManager* _stickerManager; 
	CoreDataMessageManager* _messageManager; 
	CoreDataConversationManager* _coreDataConversationManager; 
	URLDataManager* _urlDataManager; 
	AddressBookManager* _addressBookManager; 
	CardsSearchManager* _cardsSearchManager; 
	DeviceManager* _deviceManager; 
	NSData* _token; 
	BOOL _firstRunAfterLogin; 
}
@property (nonatomic,retain) KikHttpClientController* http; 				//@synthesize http=_http - In the implementation block
@property (nonatomic,retain) KikNetwork* network; 				//@synthesize network=_network - In the implementation block
@property (nonatomic,retain) NetworkNotifier* networkNotifier; 				//@synthesize networkNotifier=_networkNotifier - In the implementation block
@property (nonatomic,retain) KikStorage* storage; 				//@synthesize storage=_storage - In the implementation block
@property (nonatomic,retain) UserManager* userManager; 				//@synthesize userManager=_userManager - In the implementation block
@property (nonatomic,retain) AccountManager* accountManager; 				//@synthesize accountManager=_accountManager - In the implementation block
@property (nonatomic,retain) ChatManager* chatManager; 				//@synthesize chatManager=_chatManager - In the implementation block
@property (nonatomic,retain) AttachmentManager* attachmentManager; 				//@synthesize attachmentManager=_attachmentManager - In the implementation block
@property (nonatomic,retain) AudioManager* audioManager; 				//@synthesize audioManager=_audioManager - In the implementation block
@property (nonatomic,retain) Config* config; 				//@synthesize config=_config - In the implementation block
@property (nonatomic,retain) ContentManager* contentManager; 				//@synthesize contentManager=_contentManager - In the implementation block
@property (nonatomic,retain) CardManager* cardManager; 				//@synthesize cardManager=_cardManager - In the implementation block
@property (nonatomic,retain) CardWhitelistManager* cardWhitelistManager; 				//@synthesize cardWhitelistManager=_cardWhitelistManager - In the implementation block
@property (nonatomic,retain) CertificateManager* certificateManager; 				//@synthesize certificateManager=_certificateManager - In the implementation block
@property (nonatomic,retain) MetricsManager* metricsManager; 				//@synthesize metricsManager=_metricsManager - In the implementation block
@property (nonatomic,retain) CardsPushManager* cardsPushManager; 				//@synthesize cardsPushManager=_cardsPushManager - In the implementation block
@property (nonatomic,retain) KikTickerManager* tickerManager; 				//@synthesize tickerManager=_tickerManager - In the implementation block
@property (nonatomic,retain) SecureXDataManager* xDataManager; 				//@synthesize xDataManager=_xDataManager - In the implementation block
@property (nonatomic,retain) IAPManager* iapManager; 				//@synthesize iapManager=_iapManager - In the implementation block
@property (nonatomic,retain) StickerManager* stickerManager; 				//@synthesize stickerManager=_stickerManager - In the implementation block
@property (nonatomic,retain) id<ConversationManagerProvider> conversationManager; 				//@synthesize coreDataConversationManager=_coreDataConversationManager - In the implementation block
@property (nonatomic,retain) URLDataManager* urlDataManager; 				//@synthesize urlDataManager=_urlDataManager - In the implementation block
@property (nonatomic,retain) AddressBookManager* addressBookManager; 				//@synthesize addressBookManager=_addressBookManager - In the implementation block
@property (nonatomic,retain) CardsSearchManager* cardsSearchManager; 				//@synthesize cardsSearchManager=_cardsSearchManager - In the implementation block
@property (nonatomic,retain) DeviceManager* deviceManager; 				//@synthesize deviceManager=_deviceManager - In the implementation block
+(id)setUp:(id)arg1 token:(id)arg2;
+(id)sharedInstance;
-()onAuthorized:(id)arg1;
-(void)upgradeToCurrentVersion;
-(void)authorize:(id)arg1;
-(void)onPasswordChanged:(id)arg1;
-(void)authorizationRevoked;
-(void)setStorage:(id)arg1;
-(id)initWithConfig:(id)arg1 token:(id)arg2;
-(void)setCardManager:(id)arg1;
-(void)setCardsPushManager:(id)arg1;
-(void)setContentManager:(id)arg1;
-(void)resetEverything;
-(void)resetStorage;
-(void)resetEverythingForReason:(id)arg1 withTitle:(id)arg2;
-(void)setNetworkNotifier:(id)arg1;
-(void)setUserManager:(id)arg1;
-(void)setAccountManager:(id)arg1;
-(void)setChatManager:(id)arg1;
-(void)setAudioManager:(id)arg1;
-(void)setCertificateManager:(id)arg1;
-(void)setHttp:(id)arg1;
-(void)setXDataManager:(id)arg1;
-(void)setIapManager:(id)arg1;
-(void)setStickerManager:(id)arg1;
-(void)setConversationManager:(id)arg1;
-(void)setUrlDataManager:(id)arg1;
-(void)setAddressBookManager:(id)arg1;
-(void)setCardsSearchManager:(id)arg1;
-(void)setCardWhitelistManager:(id)arg1;
-(void)setMetricsManager:(id)arg1;
-(void)setTickerManager:(id)arg1;
-(void)tearDown;
-(void)setNetwork:(id)arg1;
-(void)setConfig:(id)arg1;
-(void)setDeviceManager:(id)arg1;
-(void)setAttachmentManager:(id)arg1;
-(void)setup;
@end