/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:45 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MessageManagerProvider.h>

@interface CoreDataMessageManager : NSObject <MessageManagerProvider> {
	KikNetwork* _network; 
	KikStorage* _storage; 
	KikAckQueueHelper* _ackQueue; 
	AttachmentManager* _attachmentManager; 
	MetricsManager* _metricsManager; 
	NSMutableDictionary* _messageRetryCountDict; 
	BOOL _justRegistered; 
}
-(void)onEventXmppConnected:(id)arg1;
-(void)onUserJustRegistered:(id)arg1;
-(id)initWithNetwork:(id)arg1 andStorage:(id)arg2 andAckQueue:(id)arg3 andAttachmentManager:(id)arg4 andMetricsManager:(id)arg5;
-(void)processQosFlush:(id)arg1;
-(void)onEventXmppPreconnect:(id)arg1;
-(void)onEventMessageReceived:(id)arg1;
-(void)onFirstRosterFetched:(id)arg1;
-(void)flushQoS;
-(void)processMessages:(id)arg1 fromQoS:(BOOL)arg2;
-(void)sendAckQueueWithHistoryFetch:(BOOL)arg1;
-(void)sendUnsentMessages;
-(void)sendContentMessage:(id)arg1 withUserInfo:(id)arg2 andCallback:(id)arg3;
-(void)sendTextMessage:(id)arg1 withCallback:(id)arg2;
-(void)sendReadReceiptsForConversation:(id)arg1;
-(void)setup;
@end