/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:38 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import "ConversationManagerProvider.h"
 #import "KikStorage.h"
 #import "KikNetwork.h"
 #import "UserManager.h"
 #import "AttachmentManager.h"
 #import "ContentManager.h"
 #import "ChatManager.h"
 #import "AccountManager.h"
 #import "BloomFilter.h"
 #import "MessageManagerProvider.h"

@interface CoreDataConversationManager : NSObject <ConversationManagerProvider> {
	KikStorage* _storage; 
	KikNetwork* _network; 
	UserManager* _userManager; 
	AttachmentManager* _attachmentManager; 
	ContentManager* _contentManager; 
	ChatManager* _chatManager; 
	AccountManager* _accountManager; 
	id<MessageManagerProvider> _messageManager; 
	NSMutableDictionary* _conversationMap; 
	BloomFilter* _incomingMessagesFilter; 
	BOOL _notifyAfterQos; 
	BOOL _isFirstQos; 
}
@property (nonatomic,retain) ContentManager* contentManager; 				//@synthesize contentManager=_contentManager - In the implementation block
-(void)qosFinished:(id)arg1;
-(id)conversationForID:(id)arg1;
-(id)createConversationForID:(id)arg1;
-(void)sendContentMessage:(id)arg1 toConversation:(id)arg2;
-(void)sendTextMessage:(id)arg1 toConversation:(id)arg2;
-(void)sendReadReceiptsForConversationID:(id)arg1;
-(id)changeConversationID:(id)arg1 toID:(id)arg2;
-(id)initWithStorage:(id)arg1 andNetwork:(id)arg2 andUserManager:(id)arg3 andMessageManager:(id)arg4 andChatManager:(id)arg5 andAccountManager:(id)arg6 andAttachmentManager:(id)arg7;
-(void)setContentManager:(id)arg1;
-(void)messagesReceived:(id)arg1;
-(BOOL)conversationIsNewForBinJid:(id)arg1 stanzaId:(id)arg2;
-(BOOL)conversationIsIgnoredForCurrentChat:(id)arg1 andSender:(id)arg2;
-(id)createConversationMapUsingChats:(id)arg1;
-(void)createConversationMapIfNeeded;
-(void)storeParsedMessages:(id)arg1 forQoS:(BOOL)arg2;
-(BOOL)notifyUserOfParsedMessage:(id)arg1;
-(BOOL)incomingMessageExistsWithStanzaId:(id)arg1;
-(void)handleReadReceiptsAndErrorsWithParsedMessage:(id)arg1 andKikMessage:(id)arg2;
-(id)createKikMessageFromParsedMessage:(id)arg1;
-(BOOL)applyParsedMessageFlags:(id)arg1 toUser:(id)arg2;
-(id)createConversationForKikChat:(id)arg1 andUpdateDictionary:(id)arg2;
-(void)handleAttachmentWithUserInfo:(id)arg1 andKikMessage:(id)arg2 andConversation:(id)arg3;
-(BOOL)deleteConversationForID:(id)arg1;
-(void)setup;
@end