/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:29 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextFieldDelegate.h>

@interface DebuggableCardsViewController : CardsViewController <UITextFieldDelegate> {
	UITextField* _injectionField; 
	UITextView* _syncOutput; 
	UITextView* _asyncOutput; 
	UITextView* _consoleLog; 
}
@property (nonatomic,retain) UITextField* injectionField; 				//@synthesize injectionField=_injectionField - In the implementation block
@property (nonatomic,retain) UITextView* syncOutput; 				//@synthesize syncOutput=_syncOutput - In the implementation block
@property (nonatomic,retain) UITextView* asyncOutput; 				//@synthesize asyncOutput=_asyncOutput - In the implementation block
@property (nonatomic,retain) UITextView* consoleLog; 				//@synthesize consoleLog=_consoleLog - In the implementation block
+(id)controllerWithCardDescriptor:(id)arg1 url:(id)arg2 sidebar:(id)arg3 pickerRequest:(id)arg4 historyManager:(id)arg5 popupManager:(id)arg6;
+(id)controllerWithCardDescriptor:(id)arg1 url:(id)arg2 sidebar:(id)arg3 historyManager:(id)arg4 popupManager:(id)arg5;
-(void)setAutomationAsynchronousOutput:(id)arg1;
-(void)setInjectionField:(id)arg1;
-(void)setSyncOutput:(id)arg1;
-(void)setAsyncOutput:(id)arg1;
-(void)setConsoleLog:(id)arg1;
-(void)cardLoggingEvent:(id)arg1;
-(void)makeDebuggable;
-(void)executeJavascript;
-(BOOL)textFieldShouldReturn:(id)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void).cxx_destruct;
@end