/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:43 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "KikMessage.h"

@protocol ConversationProvider
@property (copy) NSString* jid; 
@property (copy) NSString* title; 
@property (copy) KikMessage* lastMessage; 
@property (copy) NSDate* timestamp; 
@property (copy) NSArray* participants; 
@property (copy) NSArray* participantsByUsername; 
@property BOOL isTyping; 
@property BOOL isGroup; 
@property BOOL isBlocked; 
//@property (copy) id<DialogProvider> dialog; 
@required
-(id)jid;
-(BOOL)isTyping;
-(void)addMessages:(id)arg1 ;
-(id)participantsByUsername;
-(BOOL)isBlocked;
-(id)participants;
-(id)dialog;
-(id)timestamp;
-(id)title;
-(BOOL)isGroup;
-(void)addMessage:(id)arg1 ;
-(id)lastMessage;
-(void)addParticipant:(id)arg1 ;
-(void)removeParticipant:(id)arg1 ;
-(id)jid;
-(BOOL)isTyping;
-(void)addMessages:(id)arg1 ;
-(id)participantsByUsername;
-(BOOL)isBlocked;
-(id)participants;
-(id)dialog;
-(id)timestamp;
-(id)title;
-(BOOL)isGroup;
-(void)addMessage:(id)arg1 ;
-(id)lastMessage;
-(void)addParticipant:(id)arg1 ;
-(void)removeParticipant:(id)arg1 ;
@end

@protocol DialogProvider
@property (copy) NSSet* messages; 
@property (copy) NSArray* sortedMessages; 
@required
-(id)sortedMessages;
-(id)messages;
-(id)sortedMessages;
-(id)messages;
@end
