/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:48 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <KikWorkItemDelegate.h>

@interface DispatchQueueWorker : NSObject <KikWorkItemDelegate> {
	NSCondition* _workLock; 
	NSMutableArray* _workQueue; 
	BOOL _finished; 
	BOOL _freeToWork; 
}
-(void)executeNextWorkItem;
-(void)workItemCompleted;
-(void)enqueueWorkItem:(id)arg1;
-(id)init;
-(void).cxx_destruct;
@end