/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:45 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "DoublyLinkedListNode.h"

@interface DoublyLinkedList : NSObject {
	unsigned _count; 
	DoublyLinkedListNode* _head; 
	DoublyLinkedListNode* _tail; 
}
@property (copy) DoublyLinkedListNode* head; 				//@synthesize head=_head - In the implementation block
@property (copy) DoublyLinkedListNode* tail; 				//@synthesize tail=_tail - In the implementation block
@property unsigned count; 				//@synthesize count=_count - In the implementation block
-(void)moveNode:(id)arg1 before:(id)arg2;
-(void)insertNode:(id)arg1 after:(id)arg2;
-(void)moveNode:(id)arg1 after:(id)arg2;
-(void)removeAllNodes;
-(void)insertNode:(id)arg1 before:(id)arg2;
-(void)dealloc;
-(id)initWithArray:(id)arg1;
-(void)removeNode:(id)arg1;
-(id)stringRepresentation;
@end