/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 23106 PM Mountain Daylight Time
 * Operating System Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "DownloadManagerDelegate.h"

@protocol DownloadManager
@property (nonatomic,retain) id<DownloadManagerDelegate> delegate; 
@required
-(id)contentItemForID:(id)arg1 ;
-(id)downloadFileWithUrl:(id)arg1 contentID:(id)arg2 appID:(id)arg3 ;
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
-(id)contentItemForID:(id)arg1 ;
-(id)downloadFileWithUrl:(id)arg1 contentID:(id)arg2 appID:(id)arg3 ;
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
@end
