/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:16 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UserFSFile.h>

@interface ExFATFile : ExFATItem <UserFSFile> {
}
@property (nonatomic,retain) ExFATVolume* volume; 
@property (nonatomic,copy) NSString* name; 
@property (nonatomic,copy) BOOL isDirectory; 
@property (getter=isLocked,nonatomic,copy) BOOL locked; 
@property (nonatomic,copy) unsigned long long length; 
@property (nonatomic,copy) long long createdDate; 
@property (nonatomic,copy) long long modifiedDate; 
-(id)debugDescription;
-(id)openStream;
@end