/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:15 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UserFSVolume.h>

@interface ExFATVolume : NSObject <UserFSVolume> {
	int _fd; 
	int _dirty; 
	UserFSBufferCache* _bufferCache; 
	BOOL _locked; 
	NSString* _deviceName; 
	unsigned _dev_block_size; 
	unsigned _bytesPerSectorShift; 
	unsigned _bytesPerClusterShift; 
	unsigned _maxCluster; 
	unsigned _rootCluster; 
	unsigned _rootNumClusters; 
	unsigned long _dirBlockSize; 
	unsigned short* _upcase; 
	ExFATFile* _bitmap; 
	ExFATFolder* __cachedRootDir; 
	unsigned long long _fatOffset; 
	unsigned long long _fatSize; 
	unsigned long long _clusterOffset; 
}
@property (assign,nonatomic) unsigned dev_block_size; 				//@synthesize dev_block_size=_dev_block_size - In the implementation block
@property (assign,nonatomic) unsigned bytesPerSectorShift; 				//@synthesize bytesPerSectorShift=_bytesPerSectorShift - In the implementation block
@property (assign,nonatomic) unsigned bytesPerClusterShift; 				//@synthesize bytesPerClusterShift=_bytesPerClusterShift - In the implementation block
@property (assign,nonatomic) unsigned maxCluster; 				//@synthesize maxCluster=_maxCluster - In the implementation block
@property (assign,nonatomic) unsigned rootCluster; 				//@synthesize rootCluster=_rootCluster - In the implementation block
@property (assign,nonatomic) unsigned rootNumClusters; 				//@synthesize rootNumClusters=_rootNumClusters - In the implementation block
@property (assign,nonatomic) unsigned long long fatOffset; 				//@synthesize fatOffset=_fatOffset - In the implementation block
@property (assign,nonatomic) unsigned long long fatSize; 				//@synthesize fatSize=_fatSize - In the implementation block
@property (assign,nonatomic) unsigned long long clusterOffset; 				//@synthesize clusterOffset=_clusterOffset - In the implementation block
@property (nonatomic,copy) unsigned long dirBlockSize; 				//@synthesize dirBlockSize=_dirBlockSize - In the implementation block
@property (assign,getter=isLocked,nonatomic) BOOL locked; 				//@synthesize locked=_locked - In the implementation block
@property (assign,nonatomic) unsigned short* upcase; 				//@synthesize upcase=_upcase - In the implementation block
@property (nonatomic,copy) NSString* deviceName; 				//@synthesize deviceName=_deviceName - In the implementation block
@property (nonatomic,retain) ExFATFile* bitmap; 				//@synthesize bitmap=_bitmap - In the implementation block
@property (assign,nonatomic,__weak) ExFATFolder* _cachedRootDir; 				//@synthesize _cachedRootDir=__cachedRootDir - In the implementation block
-(id)rootDirectory;
-(void)dealloc;
-(BOOL)flush;
-(void)setLocked:(BOOL)arg1;
-(BOOL)close;
-(void).cxx_destruct;
-(void)releaseBuffer:(id)arg1;
-(id)getBufferAtOffset:(unsigned long long)arg1 ofLength:(unsigned long)arg2 error:(int*)arg3;
-(unsigned)contiguousClustersInChain:(unsigned)arg1 nextCluster:(unsigned*)arg2;
-(void)setRootNumClusters:(unsigned)arg1;
-(id)rootDir;
-(BOOL)readUpcaseTable:(struct exfat_direntry_upcase*)arg1;
-(void)setBitmap:(id)arg1;
-(void)setUpcase:(unsigned short*)arg1;
-(BOOL)freeExtentAt:(unsigned)arg1 count:(unsigned)arg2;
-(void)set_cachedRootDir:(id)arg1;
-(id)itemAtPath:(id)arg1;
-(BOOL)deleteFiles:(id)arg1;
-(long)readBytes:(void*)arg1 ofLength:(unsigned long)arg2 atOffset:(unsigned long long)arg3;
-(long)writeBytes:(void*)arg1 ofLength:(unsigned long)arg2 atOffset:(unsigned long long)arg3;
-(unsigned long long)physicalOffsetForCluster:(unsigned)arg1;
-(id)initWithDeviceName:(id)arg1 fileDescriptor:(int)arg2 writable:(BOOL)arg3;
-(BOOL)freeChainAt:(unsigned)arg1;
-(void)setDev_block_size:(unsigned)arg1;
-(void)setBytesPerSectorShift:(unsigned)arg1;
-(void)setBytesPerClusterShift:(unsigned)arg1;
-(void)setMaxCluster:(unsigned)arg1;
-(void)setRootCluster:(unsigned)arg1;
-(void)setFatOffset:(unsigned long long)arg1;
-(void)setFatSize:(unsigned long long)arg1;
-(void)setClusterOffset:(unsigned long long)arg1;
-(void)setDeviceName:(id)arg1;
-(int)setDirty:(BOOL)arg1;
@end