/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:11:27 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "TimedRetryStrategy.h"

@interface ExponentialBackoffRetryStrategy : TimedRetryStrategy {
	int _maximumRetries; 
	int _retriesRemaining; 
	double _initialBackoffInterval; 
	double _currentBackoffInterval; 
	float _exponentBase; 
}
@property (assign,nonatomic) BOOL isBackoffReset; 
-(id)initWithMaximumRetries:(unsigned)arg1 initialBackoffInterval:(double)arg2 exponentBase:(float)arg3;
-(BOOL)scheduleRetry;
-(double)nextRetryInterval;
-(void)setDelegate:(id)arg1;
-(id)delegate;
-(void)reset;
-(id)initWithDefaults;
@end