/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:36 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "LinkedDictionary.h"

@interface FastLRUCache : NSObject {
	unsigned _maxItemsInMemory; 
	unsigned long long _diskCapacity; 
	LinkedDictionary* _memoryCache; 
	NSFileManager* _fileManager; 
	id _diskUsage; 
	id _updateDiskUsage; 
	NSString* _cachePath; 
}
-(id)dataForToken:(id)arg1;
-(void)printCacheDetails;
-(void)pruneDiskCache;
-(void)pruneMemoryCache;
-(void)deleteDataForToken:(id)arg1;
-(id)initWithPath:(id)arg1 maxItemsInMemory:(unsigned)arg2 diskCapacity:(unsigned long long)arg3 withDiskUsage:(id)arg4 andDiskUsageUpdate:(id)arg5;
-(void)saveData:(id)arg1 forToken:(id)arg2;
-(void)dealloc;
-(void)deleteAllData;
@end