/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 2:19:48 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "ContentDownloadDescriptor.h"

@interface FileDownload : NSObject {
	int _expectedFileSize; 
	int _numRetries; 
	NSString* _url; 
	NSDictionary* _params; 
	ContentDownloadDescriptor* _descriptor; 
	int _downloadStartingOffset; 
	int _maxBytesToDownload; 
	int _totalBytesReceived; 
	NSString* _contentType; 
	NSString* _contentId; 
	NSTimer* _nextChunkTimer; 
	double _backoffInterval; 
	NSURLConnection* _connection; 
	int _lastResponse; 
	double _connectionTimeout; 
	BOOL _gotDownloadAll; 
	BOOL _goodNewsFromServer; 
	BOOL _reset; 
	BOOL _preemptive; 
	BOOL _contentChanged; 
	NSString* contentId; 
	NSDate* _requestStartTime; 
}
@property (copy) NSString* contentId; 
@property (assign) int expectedFileSize; 				//@synthesize expectedFileSize=_expectedFileSize - In the implementation block
@property (assign) int numRetries; 				//@synthesize numRetries=_numRetries - In the implementation block
@property (assign) int downloadStartingOffset; 				//@synthesize downloadStartingOffset=_downloadStartingOffset - In the implementation block
@property (assign) int maxBytesToDownload; 				//@synthesize maxBytesToDownload=_maxBytesToDownload - In the implementation block
@property (assign) int totalBytesReceived; 				//@synthesize totalBytesReceived=_totalBytesReceived - In the implementation block
@property (assign) int lastResponse; 				//@synthesize lastResponse=_lastResponse - In the implementation block
@property (copy) NSString* url; 				//@synthesize url=_url - In the implementation block
@property (nonatomic,retain) NSDictionary* params; 				//@synthesize params=_params - In the implementation block
@property (nonatomic,retain) ContentDownloadDescriptor* descriptor; 				//@synthesize descriptor=_descriptor - In the implementation block
@property (assign,nonatomic) double connectionTimeout; 				//@synthesize connectionTimeout=_connectionTimeout - In the implementation block
@property (nonatomic,copy) NSString* contentType; 				//@synthesize contentType=_contentType - In the implementation block
@property (nonatomic,retain) NSDate* requestStartTime; 				//@synthesize requestStartTime=_requestStartTime - In the implementation block
@property (assign,nonatomic) BOOL goodNewsFromServer; 				//@synthesize goodNewsFromServer=_goodNewsFromServer - In the implementation block
@property (assign,nonatomic) BOOL gotDownloadAll; 				//@synthesize gotDownloadAll=_gotDownloadAll - In the implementation block
@property (assign,nonatomic) BOOL contentChanged; 				//@synthesize contentChanged=_contentChanged - In the implementation block
@property (assign,nonatomic) BOOL preemptive; 				//@synthesize preemptive=_preemptive - In the implementation block
-(void)downloadAll;
-(id)initWithParams:(id)arg1 downloadDescriptor:(id)arg2 fileSize:(int)arg3 chunkSize:(int)arg4 isPreemptiveDownload:(BOOL)arg5;
-(void)setNumRetries:(int)arg1;
-(void)setContentChanged:(BOOL)arg1;
-(void)setPreemptive:(BOOL)arg1;
-(void)setParams:(id)arg1;
-(void)setExpectedFileSize:(int)arg1;
-(void)setDownloadStartingOffset:(int)arg1;
-(void)setMaxBytesToDownload:(int)arg1;
-(void)setConnectionTimeout:(double)arg1;
-(void)getNextChunk;
-(void)setGotDownloadAll:(BOOL)arg1;
-(void)notifyDownloadError;
-(void)getNextChunkWithTimeInterval:(double)arg1;
-(void)fetchNextChunk;
-(void)setGoodNewsFromServer:(BOOL)arg1;
-(void)onRequestTimeout;
-(void)cleanUpConnection;
-(void)setLastResponse:(int)arg1;
-(void)resetDownloadRetryBackoff;
-(int)getExpectedFileSizeFromRangeString:(id)arg1;
-(void)retryDownload;
-(void)onContentChangedOnServer;
-(void)notifyDataReceived:(id)arg1 startOffset:(int)arg2;
-(void)notifyDownloadComplete;
-(void)notifyPartialDownloadComplete;
-(void)preDownload:(int)arg1;
-(void)updateMaxBytesToDownload:(unsigned)arg1;
-(void)setContentId:(id)arg1;
-(void)killTimer;
-(void)dealloc;
-(void)setUrl:(id)arg1;
-(void)connection:(id)arg1 didFailWithError:(id)arg2;
-(void)connection:(id)arg1 didReceiveData:(id)arg2;
-(void)connectionDidFinishLoading:(id)arg1;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2;
-(void)setTotalBytesReceived:(int)arg1;
-(void)setContentType:(id)arg1;
-(void)setDescriptor:(id)arg1;
-(void)setRequestStartTime:(id)arg1;
-(id)getDictionary;
@end