/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:14 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FileUtils : NSObject {
}
+(void)touchFileAtPath:(id)arg1 withFileManager:(id)arg2;
+(unsigned long long)diskSpaceInUseForFileAtPath:(id)arg1 withFileManager:(id)arg2;
+(id)contentsOfDirectory:(id)arg1 withFileManager:(id)arg2;
+(id)lastModifiedDateForFileAtPath:(id)arg1 withFileManager:(id)arg2;
+(unsigned long long)totalDiskSpaceInUseForContents:(id)arg1 inDirectory:(id)arg2 withFileManager:(id)arg3;
+(id)documentPath;
@end