/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, July 6, 2014 at 12:18:59 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSURLConnectionDelegate.h>
#import <RetryStrategyDelegate.h>

@interface FileUploadMetricsDataHandler : FileMetricsDataHandler <NSURLConnectionDelegate, RetryStrategyDelegate> {
	KikNetwork* _network; 
	NSString* _url; 
	int _networkBatchSize; 
	NSMutableDictionary* _uploadingCachedUploadRequests; 
	NSURLConnection* _activeURLConnection; 
	BOOL _uploadSuccess; 
	ExponentialBackoffRetryStrategy* _retryStrategy; 
	BOOL _waitingForRetry; 
}
-(void)retryStrategyDidAdviseRetry:(id)arg1;
-(void)onXmppConnected:(id)arg1;
-(id)initWithNetwork:(id)arg1 andURL:(id)arg2;
-(id)initWithNetwork:(id)arg1 andURL:(id)arg2 andNetworkBatchSize:(int)arg3;
-(void)flushAllEventData;
-(void)processEventData:(id)arg1 withUserID:(id)arg2 andDevicePrefix:(id)arg3 andUserUUID:(id)arg4;
-(void)uploadRemainingMetrics;
-(void)maybeScheduleRetry;
-(void)connection:(id)arg1 didFailWithError:(id)arg2;
-(void)connectionDidFinishLoading:(id)arg1;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2;
-(void)setBatchSize:(int)arg1;
-(int)batchSize;
@end