/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:05 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FlatButtonHelper : NSObject {
}
+(id)flatButtonWithText:(id)arg1 andColor:(id)arg2;
+(id)flatButtonWithText:(id)arg1;
+(id)flatNavigationBackButtonWithText:(id)arg1;
+(id)blueFlatNavigationBackButtonWithText:(id)arg1;
@end