/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:38:56 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "KikFetchedResultsController.h"

@interface FRCAllContacts : KikFetchedResultsController {
}
-(BOOL)generateSearchPredicateForText:(id)arg1;
-(id)initWithContext:(id)arg1;
@end