/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:18 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FRCBlockAvailable : KikFetchedResultsController {
}
-(BOOL)generateSearchPredicateForText:(id)arg1;
-(id)initWithContext:(id)arg1;
@end