/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:02:03 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <ViewHitProtocol.h>
#import <UIAlertViewDelegate.h>
#import <ContactSelectedCallback.h>
#import <UIActionSheetDelegate.h>

@interface GroupChatScreenController : LoadingSpinnerKikViewController <ViewHitProtocol, UIAlertViewDelegate, ContactSelectedCallback, UIActionSheetDelegate> {
	GroupPageAttribs* _pageAttribs; 
	UIView* _groupMembers; 
	UIView* _groupActionView; 
	UIView* _outterView; 
	UIScrollView* _scrollView; 
	SettingsButtonSingle* _deleteConversation; 
	SettingsButtonSingle* _leaveConversation; 
	KikUser* _user; 
	KikChat* _chat; 
	BOOL _isGroup; 
	int _numActualMembers; 
	int _numInGroup; 
	BOOL _animate; 
	NSMutableArray* _sysMessage; 
	NSMutableArray* _memberViews; 
	NSObject<ViewHitProtocol>* _callBack; 
	UIAlertView* _alertSenderLeave; 
	KikUser* _userToAddToChat; 
	BOOL _gotUnsupportedJid; 
	int _numIconsWide; 
}
@property (nonatomic,retain) KikUser* user; 				//@synthesize user=_user - In the implementation block
@property (nonatomic,retain) KikChat* chat; 				//@synthesize chat=_chat - In the implementation block
@property (assign,nonatomic) BOOL isGroup; 				//@synthesize isGroup=_isGroup - In the implementation block
@property (nonatomic,copy) int numInGroup; 				//@synthesize numInGroup=_numInGroup - In the implementation block
@property (nonatomic,retain) NSObject<ViewHitProtocol>* viewCallback; 				//@synthesize callBack=_callBack - In the implementation block
@property (assign,nonatomic) BOOL gotUnsupportedJid; 				//@synthesize gotUnsupportedJid=_gotUnsupportedJid - In the implementation block
+(id)controller;
-(void)contactSelected:(id)arg1 view:(id)arg2;
-(void)setIsGroup:(BOOL)arg1;
-(void)onLeftChat:(id)arg1;
-(void)userToAdd:(id)arg1;
-(void)userWasClicked:(id)arg1;
-(id)addUsertoView:(id)arg1;
-(void)changeOrientation;
-(void)recalculateViews;
-(void)onChatUpdated:(id)arg1;
-(void)onUnsupportedClient:(id)arg1;
-(void)onUnknownError:(id)arg1;
-(void)onTimeoutError:(id)arg1;
-(void)changeOrientation:(BOOL)arg1;
-(void)setGotUnsupportedJid:(BOOL)arg1;
-(void)recalculateViews:(BOOL)arg1;
-(void)createGroup;
-(void)listenForGroupLeaveEvents:(BOOL)arg1;
-(void)popToHomeOrMissedScreen;
-(void)callback:(id)arg1;
-(int)titleViewWidth;
-(void)notificationSwitch:(id)arg1;
-(void)leaveGroupPressed:(id)arg1;
-(void)setViewCallback:(id)arg1;
-(void)didCancel;
-(void)setUser:(id)arg1;
-(void)dealloc;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(void)setupForOrientation:(BOOL)arg1;
-(void).cxx_destruct;
-(BOOL)isLandscape;
-(void)deleteConversation:(id)arg1;
-(void)setChat:(id)arg1;
@end