/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:02:03 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

typedef struct{
	int value1;
	int value2;
	int value3;
	int value4;
	int value5;
	int value6;
} WCStruct_iiiiii;


@interface GroupPageAttribs : NSObject {
	struct {
	} _portraitProfile; 
	struct {
	} _landscapeProfile; 
	BOOL _hasLandscape; 
	BOOL _hasPortrait; 
}
@property (assign,nonatomic) BOOL hasLandscape; 				//@synthesize hasLandscape=_hasLandscape - In the implementation block
@property (assign,nonatomic) BOOL hasPortrait; 				//@synthesize hasPortrait=_hasPortrait - In the implementation block
@property (nonatomic,copy) WCStruct_iiiiii* portraitProfile; 				//@synthesize portraitProfile=_portraitProfile - In the implementation block
@property (nonatomic,copy) WCStruct_iiiiii* landscapeProfile; 				//@synthesize landscapeProfile=_landscapeProfile - In the implementation block
-(WCStruct_iiiiii*)readSizeProfileFromDictionary:(id)arg1;
-(void)setHasPortrait:(BOOL)arg1;
-(void)setHasLandscape:(BOOL)arg1;
-(void)dealloc;
-(id)init;
@end