/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:58 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface GroupsMemberView : KikViewController {
	NSString* _labelText; 
	NSObject<ViewHitProtocol>* _callbackOnPress; 
	KikUser* _user; 
	DelayedUnhighlightButton* _buttonAdd; 
	UIImageView* _outerImageWell; 
	UILabel* _userLabel; 
}
@property (assign,nonatomic,__weak) DelayedUnhighlightButton* buttonAdd; 				//@synthesize buttonAdd=_buttonAdd - In the implementation block
@property (assign,nonatomic,__weak) UIImageView* outerImageWell; 				//@synthesize outerImageWell=_outerImageWell - In the implementation block
@property (assign,nonatomic,__weak) UILabel* userLabel; 				//@synthesize userLabel=_userLabel - In the implementation block
@property (nonatomic,retain) KikUser* user; 				//@synthesize user=_user - In the implementation block
@property (nonatomic,copy) NSString* displayedText; 
-(int)greaterThan:(id)arg1;
-(id)initWithKikUser:(id)arg1 callback:(id)arg2;
-(void)updateUIForCurrentUser;
-(void)setProfilePicture;
-(void)setLabel;
-(void)setButtonAdd:(id)arg1;
-(void)setOuterImageWell:(id)arg1;
-(void)setUserLabel:(id)arg1;
-(void)setUser:(id)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)buttonPressed:(id)arg1;
-(void).cxx_destruct;
@end