/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:37 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIGestureRecognizerDelegate.h>

@interface HorizontalPanGestureRecognizer : UIPanGestureRecognizer <UIGestureRecognizerDelegate> {
	BOOL _touchSequenceIsInHitRect; 
	CGRect hitRect; 
}
@property (assign,nonatomic) CGRect hitRect; 
-(void)setHitRect:(CGRect)arg1;
-(BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
-(id)initWithTarget:(id)arg1 action:(SEL)arg2;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(BOOL)canBePreventedByGestureRecognizer:(id)arg1;
-(BOOL)canPreventGestureRecognizer:(id)arg1;
@end