/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 2:14:44 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface HybridViewController : UIViewController {
	BOOL _keyboardShowing; 
	NSString* _backTitle; 
	unsigned _orientationMask; 
}
@property (nonatomic,copy) NSString* backTitle; 				//@synthesize backTitle=_backTitle - In the implementation block
@property (assign,nonatomic) unsigned orientationMask; 				//@synthesize orientationMask=_orientationMask - In the implementation block
-(void)setLeftNavigationButtonWithTitle:(id)arg1 andIsBack:(BOOL)arg2;
-(void)leftNavigationButtonPressed:(id)arg1;
-(void)setRightNavigationButtonWithTitle:(id)arg1;
-(void)rightNavigationButtonPressed:(id)arg1;
-(void)setRightNavigationButtonWithView:(id)arg1;
-(void)updateBackButton;
-(void)showLoadingSpinner;
-(void)hideLoadingSpinner;
-(void)setOrientationMask:(unsigned)arg1;
-(void)setBackTitle:(id)arg1;
-(void)showLoadingSpinnerWithTimeout:(double)arg1;
-(void)stopObservingKeyboard;
-(void)setLeftNavigationButtonWithView:(id)arg1 andIsBack:(BOOL)arg2;
-(void)dealloc;
-(int)preferredStatusBarStyle;
-(BOOL)shouldAutorotate;
-(unsigned)supportedInterfaceOrientations;
-(void)setTitleView:(id)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(void)keyboardDidShow:(id)arg1;
-(void)keyboardDidHide:(id)arg1;
-(void)keyboardWillShow:(id)arg1;
-(void)keyboardWillHide:(id)arg1;
@end