/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:35 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IAPiTunesProductCallback : NSObject {
	SKProductsRequest* _productRequest; 
	id _callback; 
	NSString* _key; 
}
@property (nonatomic,retain) SKProductsRequest* productRequest; 				//@synthesize productRequest=_productRequest - In the implementation block
@property (nonatomic,copy) id callback; 				//@synthesize callback=_callback - In the implementation block
@property (nonatomic,retain) NSString* key; 				//@synthesize key=_key - In the implementation block
-(void)setProductRequest:(id)arg1;
-(void)setCallback:(id)arg1;
-(void)setKey:(id)arg1;
-(void).cxx_destruct;
@end