/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:35 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol IAPItemFetchProvider
@required
-(void)fetchSKUs(id):arg1 withCallback(id):arg2 ;
-(void)fetchSKUs(id):arg1 withCallback(id):arg2 ;
@end
