/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:07 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ImageUtilities : NSObject {
}
+(id)imageDataToDataUrl:(id)arg1 mimeType:(id)arg2;
+(id)loadImageURL:(id)arg1 relativeTo:(id)arg2 callback:(id)arg3 timeout:(double)arg4;
+(id)imageToDataUrl:(id)arg1 quality:(float)arg2;
+(id)loadImageURL:(id)arg1 relativeTo:(id)arg2 callback:(id)arg3;
@end