/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:08 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikAttachmentContainer : NSObject {
	NSDictionary* userInfo; 
	NSString* _appName; 
	NSString* _appId; 
	NSString* _titleText; 
	NSString* _messageText; 
}
@property (nonatomic,retain) NSDictionary* userInfo; 
@property (nonatomic,copy) UIImage* previewImage; 
@property (nonatomic,copy) UIImage* iconImage; 
@property (nonatomic,copy) NSString* appName; 				//@synthesize appName=_appName - In the implementation block
@property (nonatomic,copy) NSString* appId; 				//@synthesize appId=_appId - In the implementation block
@property (nonatomic,copy) NSData* previewData; 
@property (nonatomic,copy) NSString* titleText; 				//@synthesize titleText=_titleText - In the implementation block
@property (nonatomic,copy) NSArray* urls; 
@property (nonatomic,copy) NSString* messageText; 				//@synthesize messageText=_messageText - In the implementation block
-(id)stringForTypeName:(id)arg1;
-(id)imageForTypeName:(id)arg1;
-(id)dataForTypeName:(id)arg1;
-(id)initWithAttachmentUserInfo:(id)arg1;
-(void)setMessageText:(id)arg1;
-(void)setTitleText:(id)arg1;
-(void).cxx_destruct;
-(void)setUserInfo:(id)arg1;
-(void)setAppId:(id)arg1;
-(void)setAppName:(id)arg1;
@end