/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:36:55 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikAckQueueHelper : NSObject {
	NSMutableDictionary* _queue; 
}
@property (nonatomic,copy) NSDictionary* ackDictionary; 
@property (nonatomic) int ackCount; 
-(void)addParsedMessage:(id)arg1;
-(id)popAckDictionary;
-(id)init;
@end