/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:28 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikBlockContact : KikIQ {
	KikUser* _pertainingUserJid; 
	BOOL _shouldBlock; 
}
@property (nonatomic,retain) KikUser* pertainingUserJid; 				//@synthesize pertainingUserJid=_pertainingUserJid - In the implementation block
@property (assign,nonatomic) BOOL shouldBlock; 				//@synthesize shouldBlock=_shouldBlock - In the implementation block
-(id)initWithUser:(id)arg1 blockStatus:(BOOL)arg2;
-(void)setPertainingUserJid:(id)arg1;
-(void)setShouldBlock:(BOOL)arg1;
-(void).cxx_destruct;
@end