/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:27 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikBlockedMessageStanza : KikIQ {
	NSString* _blockedStanza; 
}
@property (nonatomic,retain) NSString* blockedStanza; 				//@synthesize blockedStanza=_blockedStanza - In the implementation block
-(void)setBlockedStanza:(id)arg1;
-(id)initWithStanzaText:(id)arg1;
-(void).cxx_destruct;
@end