/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:16 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <ContactSelectedCallback.h>
#import <UIActionSheetDelegate.h>
#import <UIAlertViewDelegate.h>

@interface KikBlockUser : ComposeScreenController <ContactSelectedCallback, UIActionSheetDelegate, UIAlertViewDelegate> {
	KikUser* _userSelected; 
	BOOL rotatingSpinner; 
}
+(void)blockUser:(id)arg1;
+(void)reportUserAsSpam:(id)arg1;
+(id)maxName:(id)arg1;
+(id)getBlockUserPrompt:(id)arg1;
+(id)getBlockUserDescription:(id)arg1;
+(void)showBlockUserConfirmationDialog:(id)arg1 title:(id)arg2 description:(id)arg3 delegate:(id)arg4;
+(id)getUnblockUserPrompt:(id)arg1;
+(id)getBlockUserButtonText:(id)arg1;
+(void)unblockUser:(id)arg1;
+(id)controller;
-(void)contactSelected:(id)arg1 view:(id)arg2;
-(id)getFRC;
-(BOOL)showHaveNotTalkedToAnyoneYetHintView:(unsigned)arg1 searchText:(id)arg2;
-(void)reloadRecents;
-(void)goAheadAndBlockTheUser;
-(void)addRightNavBarButton;
-(id)blockConfirmationMessage:(id)arg1;
-(void)onContactDeleted;
-(unsigned)supportedInterfaceOrientations;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(void).cxx_destruct;
@end