/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:02:05 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "KikUser.h"
 #import "KikMessage.h"

@interface KikChat : KikManagedObject {
	int _flags; 
	NSDate* _lastAmTypingSent; 
	NSDate* _lastIsTypingReceived; 
	BOOL _isTyping; 
	KikUser* _isTypingUser; 
	NSString* _chatIdentifier; 
	NSString* _friendlyDate; 
	BOOL _amTyping; 
	BOOL _blockUserAction; 
}
@property (assign,nonatomic) BOOL amTyping; 				//@synthesize amTyping=_amTyping - In the implementation block
@property (nonatomic,retain) NSDate* lastAmTypingSent; 				//@synthesize lastAmTypingSent=_lastAmTypingSent - In the implementation block
@property (nonatomic,retain) NSDate* lastIsTypingReceived; 				//@synthesize lastIsTypingReceived=_lastIsTypingReceived - In the implementation block
@property (assign,nonatomic) BOOL isTyping; 				//@synthesize isTyping=_isTyping - In the implementation block
@property (nonatomic,retain) KikUser* isTypingUser; 				//@synthesize isTypingUser=_isTypingUser - In the implementation block
@property (nonatomic,copy) NSString* friendlyDate; 
@property (assign,nonatomic) int flags; 
@property (nonatomic,retain) NSDate* dateUpdated; 
@property (assign,nonatomic) BOOL isGroup; 
@property (assign,nonatomic) BOOL blockUserAction; 				//@synthesize blockUserAction=_blockUserAction - In the implementation block
@property (assign,nonatomic) BOOL isDeleted; 
@property (assign,nonatomic) BOOL isRead; 
@property (assign,nonatomic) BOOL hasOnlyBlockedMessages; 
@property (assign,nonatomic) BOOL allMembersInRoster; 
@property (assign,nonatomic) BOOL isLeaving; 
@property (nonatomic,copy,copy) NSString* chatIdentifier; 
@property (nonatomic,retain) KikMessage* draftMessage; 
@property (nonatomic,retain) NSSet* messages; 
@property (nonatomic,retain) KikMessage* lastMessage; 
@property (nonatomic,retain) KikUser* user; 
-(void)setIsGroup:(BOOL)arg1;
-(void)updateFlagAllMembersInRoster;
-(void)setHasOnlyBlockedMessages:(BOOL)arg1;
-(void)setAllMembersInRoster:(BOOL)arg1;
-(void)setFriendlyDate:(id)arg1;
-(void)setIsTyping:(BOOL)arg1;
-(void)setAmTyping:(BOOL)arg1;
-(void)setLastAmTypingSent:(id)arg1;
-(void)setLastIsTypingReceived:(id)arg1;
-(void)setUserManually:(id)arg1;
-(void)setIsLeaving:(BOOL)arg1;
-(void)setBlockUserAction:(BOOL)arg1;
-(void)setIsTypingUser:(id)arg1;
-(id)initWithEntity:(id)arg1 insertIntoManagedObjectContext:(id)arg2;
-(void)setUser:(id)arg1;
-(void)setIsDeleted:(BOOL)arg1;
-(void)setIsRead:(BOOL)arg1;
-(void)setFlags:(int)arg1;
@end