/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:08 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikContentMessageStanza : KikMessageStanzaRequest {
	NSDictionary* _userInfo; 
}
@property (nonatomic,retain) NSDictionary* userInfo; 				//@synthesize userInfo=_userInfo - In the implementation block
-(void)buildXML;
-(void)addSubcontentFromDict:(id)arg1 toContentXml:(id)arg2 dictKey:(id)arg3 nameAsNodeName:(BOOL)arg4 groupName:(id)arg5 itemName:(id)arg6;
-(id)initWithMessage:(id)arg1 andUserInfo:(id)arg2;
-(void).cxx_destruct;
-(void)setUserInfo:(id)arg1;
@end