/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:39 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <ZUUIRevealControllerDelegate.h>
#import <UIGestureRecognizerDelegate.h>
#import <SidebarProtocol.h>
#import <SidebarStateProtocol.h>
#import <PopupManagerDelegate.h>

@interface KikCardViewController : HybridViewController <ZUUIRevealControllerDelegate, UIGestureRecognizerDelegate, SidebarProtocol, SidebarStateProtocol, PopupManagerDelegate> {
	HybridNavigationController* _currentHybridNavigationController; 
	CardHistoryManager* _historyManager; 
	HorizontalPanGestureRecognizer* _horizontalPanGestureRecognizer; 
	OverridingTapGestureRecognizer* _overridingTapGestureRecognizer; 
	int _sidebarHandleColourState; 
	CALayer* _smallHandleLayer; 
	CALayer* _sidebarLineLayer; 
	CALayer* _handleMaskLayer; 
	CALayer* _regionALayer; 
	CALayer* _regionBLayer; 
	UIView* _restrictWebViewTapView; 
	NSString* _selectedCardURL; 
	BOOL _viewDidAppear; 
	BOOL _sidebarDidHide; 
	BOOL _alreadyPassedBadgeThreshold; 
	BOOL _isRotating; 
	BOOL _statusBarHidden; 
	float _handleBottomOffset; 
	PopupManagerViewController* _popupManagerViewController; 
	HybridNavigationController* _webNavigationController; 
	HybridNavigationController* _conversationsNavigationController; 
	ConversationsViewController* _conversationsViewController; 
	HybridNavigationController* _currentNavigationController; 
	UIView* _backButtonOverlay; 
	UIButton* _backButton; 
	UIButton* _dismissButton; 
	CardURLDataImageView* _backButtonIcon; 
	UIImageView* _backButtonIconUnderlay; 
	SidebarViewController* _sidebarViewController; 
	RevealController* _revealController; 
}
@property (nonatomic,copy) HybridNavigationController* webNavigationController; 				//@synthesize webNavigationController=_webNavigationController - In the implementation block
@property (nonatomic,retain) HybridNavigationController* conversationsNavigationController; 				//@synthesize conversationsNavigationController=_conversationsNavigationController - In the implementation block
@property (nonatomic,retain) ConversationsViewController* conversationsViewController; 				//@synthesize conversationsViewController=_conversationsViewController - In the implementation block
@property (nonatomic,copy) HybridNavigationController* currentNavigationController; 				//@synthesize currentNavigationController=_currentNavigationController - In the implementation block
@property (nonatomic,copy) id<PopupViewManagerProvider> popupViewManager; 				//@synthesize popupManagerViewController=_popupManagerViewController - In the implementation block
@property (assign,nonatomic,__weak) UIView* backButtonOverlay; 				//@synthesize backButtonOverlay=_backButtonOverlay - In the implementation block
@property (assign,nonatomic,__weak) UIButton* backButton; 				//@synthesize backButton=_backButton - In the implementation block
@property (assign,nonatomic,__weak) UIButton* dismissButton; 				//@synthesize dismissButton=_dismissButton - In the implementation block
@property (assign,nonatomic,__weak) CardURLDataImageView* backButtonIcon; 				//@synthesize backButtonIcon=_backButtonIcon - In the implementation block
@property (assign,nonatomic,__weak) UIImageView* backButtonIconUnderlay; 				//@synthesize backButtonIconUnderlay=_backButtonIconUnderlay - In the implementation block
@property (nonatomic,retain) SidebarViewController* sidebarViewController; 				//@synthesize sidebarViewController=_sidebarViewController - In the implementation block
@property (nonatomic,retain) RevealController* revealController; 				//@synthesize revealController=_revealController - In the implementation block
@property (copy) HorizontalPanGestureRecognizer* horizontalPanGestureRecognizer; 				//@synthesize horizontalPanGestureRecognizer=_horizontalPanGestureRecognizer - In the implementation block
@property (nonatomic,copy) OverridingTapGestureRecognizer* overridingTapGestureRecognizer; 				//@synthesize overridingTapGestureRecognizer=_overridingTapGestureRecognizer - In the implementation block
@property (assign,nonatomic) BOOL sidebarDidHide; 				//@synthesize sidebarDidHide=_sidebarDidHide - In the implementation block
-(void)hideSidebar:(BOOL)arg1;
-(id)selectedCardURL;
-(id)initWithHistoryManager:(id)arg1;
-(void)setSidebarViewController:(id)arg1;
-(void)setRevealController:(id)arg1;
-(void)switchToCard:(id)arg1 withAnimation:(BOOL)arg2;
-(void)switchToCard:(id)arg1 usingURL:(id)arg2 skipNavigation:(BOOL)arg3;
-(void)setUserInteractionOfChildViewControllersTo:(BOOL)arg1;
-(void)switchToCard:(id)arg1 usingURL:(id)arg2;
-(void)popupCard:(id)arg1 fullURL:(id)arg2 requestUrl:(id)arg3 requestData:(id)arg4 fromHost:(id)arg5 callback:(id)arg6;
-(BOOL)sidebarIsFullyClosed;
-(void)resetSidebar;
-(void)showSidebar:(BOOL)arg1;
-(void)updateStatusBarState:(BOOL)arg1;
-(void)willPushView;
-(void)willPopView;
-(BOOL)isContentShowing;
-(void)switchToCard:(id)arg1 usingURL:(id)arg2 andController:(id)arg3 withForce:(BOOL)arg4 withAnimation:(BOOL)arg5 skipNavigation:(BOOL)arg6;
-(void)showSidebar;
-(void)switchToCard:(id)arg1;
-(void)revealController:(id)arg1 willRevealRearViewController:(id)arg2;
-(void)revealController:(id)arg1 didRevealRearViewController:(id)arg2 usingGesture:(BOOL)arg3;
-(void)revealController:(id)arg1 willHideRearViewController:(id)arg2;
-(void)revealController:(id)arg1 didHideRearViewController:(id)arg2;
-(void)revealController:(id)arg1 didChangeFrontViewPosition:(int)arg2;
-(void)revealControllerWillBounce:(id)arg1;
-(void)revealControllerFinishedBounce:(id)arg1;
-(void)revealController:(id)arg1 didDragFrontViewToPosition:(float)arg2;
-(void)statusBarVisibilityChanged:(id)arg1;
-(void)showFullscreenSidebar:(BOOL)arg1;
-(void)switchToCard:(id)arg1 withOffscreenDelay:(double)arg2;
-(void)measureViewDidLoad;
-(void)createHandle;
-(void)onCardNavigation:(id)arg1;
-(void)onCardHistoryCleared:(id)arg1;
-(void)onUserRegisteredOrJustLoggedIn:(id)arg1;
-(void)cardDowngradedToWebPage:(id)arg1;
-(void)updateBackNavigation;
-(void)removeAndAddPopupContainerViewAndWebTapView;
-(void)measureViewWillAppear:(BOOL)arg1;
-(void)tapGestureHideOrBounce:(id)arg1;
-(void)updateHitRectInOrientation:(int)arg1;
-(void)switchToCard:(id)arg1 usingURL:(id)arg2 andController:(id)arg3 withForce:(BOOL)arg4 withAnimation:(BOOL)arg5 skipNavigation:(BOOL)arg6 andOffscreenDelay:(double)arg7;
-(void)switchToCard:(id)arg1 usingURL:(id)arg2 withForce:(BOOL)arg3 withAnimation:(BOOL)arg4;
-(void)updateCardLastUpdated:(id)arg1;
-(void)updateSidebarHandleColour:(int)arg1;
-(void)switchToCard:(id)arg1 usingURL:(id)arg2 navigateBack:(BOOL)arg3;
-(void)switchToCard:(id)arg1 withForce:(BOOL)arg2;
-(void)switchToCard:(id)arg1 usingURL:(id)arg2 withForce:(BOOL)arg3;
-(void)makeSidebarBlue;
-(void)backButtonPressed:(id)arg1;
-(void)dismissButtonPressed:(id)arg1;
-(void)hideDragHandleAndDisableGestures;
-(void)showDragHandleAndEnableGestures;
-(void)setConversationsNavigationController:(id)arg1;
-(void)setConversationsViewController:(id)arg1;
-(void)setBackButtonOverlay:(id)arg1;
-(void)setBackButton:(id)arg1;
-(void)setBackButtonIcon:(id)arg1;
-(void)setBackButtonIconUnderlay:(id)arg1;
-(void)setSidebarDidHide:(BOOL)arg1;
-(BOOL)isSearching;
-(int)preferredStatusBarStyle;
-(BOOL)prefersStatusBarHidden;
-(BOOL)shouldAutorotate;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(void).cxx_destruct;
-(void)setDismissButton:(id)arg1;
@end