/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:57 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "KikStorageHelper.h"

@interface KikChatHelper : KikStorageHelper {
	NSMutableDictionary* _chatHash; 
	NSMutableDictionary* _chatIdentifierLookup; 
	NSTimer* _conversationsDotTimer; 
	NSPredicate* _unreadPredicate; 
	NSPredicate* _chatsWithMessagePredicate; 
	NSPredicate* _unreadMissedPredicate; 
	NSPredicate* _unreadNewPeoplePredicate; 
}
-(id)newChatForUser:(id)arg1;
-(id)initWithManagedObjectContext:(id)arg1;
-(id)chatForID:(id)arg1;
-(int)countUnreadChats;
-(id)chatForUser:(id)arg1;
-(void)updateInRosterFlagForAllChatsForUser:(id)arg1;
-(void)pruneMessagesForChat:(id)arg1;
-(void)deleteMessagesForChat:(id)arg1;
-(void)setUser:(id)arg1 forChat:(id)arg2;
-(void)createChatListIDS;
-(id)allChats;
-(id)newChat;
-(void)pruneMessagesForChat:(id)arg1 isIgnored:(BOOL)arg2;
-(void)pruneMessagesForChat:(id)arg1 overUpperBound:(int)arg2;
-(void)pruneMessagesThatAreOldForChat:(id)arg1;
-(void)updateConversationsDotFromRosterChange;
-(void)dirtyChats:(id)arg1;
-(id)allOnetoOneChatsSortedByRecency;
-(id)allChatsForUser:(id)arg1;
-(id)allFirstNamesForChat:(id)arg1;
-(void)deleteChat:(id)arg1;
@end