/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 2:13:32 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import <CoreData/NSFetchRequest.h>
 #import <CoreData/NSFetchedResultsController.h>

@interface KikFetchedResultsController : NSFetchedResultsController {
	NSString* _hash; 
	NSPredicate* _predicate; 
	NSPredicate* _searchPredicate; 
	NSFetchRequest* _request; 
	NSDate* _lastFetch; 
	double throttlingInterval; 
}
@property (nonatomic,copy) NSString* hash; 				//@synthesize hash=_hash - In the implementation block
@property (nonatomic,retain) NSPredicate* predicate; 				//@synthesize predicate=_predicate - In the implementation block
@property (nonatomic,retain) NSPredicate* searchPredicate; 				//@synthesize searchPredicate=_searchPredicate - In the implementation block
@property (nonatomic,retain) NSFetchRequest* request; 				//@synthesize request=_request - In the implementation block
@property (assign,nonatomic) double throttlingInterval; 
-(BOOL)fetch;
-(BOOL)search:(id)arg1 allowEmpty:(BOOL)arg2;
-(BOOL)generateSearchPredicateForText:(id)arg1;
-(void)clearSearch;
-(void)setThrottlingInterval:(double)arg1;
-(void)setSearchPredicate:(id)arg1;
-(void)setHash:(id)arg1;
-(void)setRequest:(id)arg1;
-(id)initWithContext:(id)arg1;
-(void)setPredicate:(id)arg1;
-(BOOL)search:(id)arg1;
-(BOOL)filter;
@end