/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 2:11:43 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikHttpClientController : NSObject {
	NSMutableDictionary* _callbacks; 
	NSString* _jid; 
	NSString* _password; 
	NSString* _httpHost; 
}
@property (nonatomic,copy) NSString* jid; 				//@synthesize jid=_jid - In the implementation block
@property (nonatomic,copy) NSString* password; 				//@synthesize password=_password - In the implementation block
@property (nonatomic,copy) NSString* httpHost; 				//@synthesize httpHost=_httpHost - In the implementation block
-(void)setJid:(id)arg1;
-(void)sendRequestOnTimer:(id)arg1;
-(void)killRequestsOfClass:(Class)arg1;
-(id)currentRequestsOfClass:(Class)arg1;
-(void)setHttpHost:(id)arg1;
-(void)connection:(id)arg1 didSendBodyData:(int)arg2 totalBytesWritten:(int)arg3 totalBytesExpectedToWrite:(int)arg4;
-(void)setPassword:(id)arg1;
-(id)init;
-(void)connection:(id)arg1 didFailWithError:(id)arg2;
-(void)connection:(id)arg1 didReceiveData:(id)arg2;
-(void)connectionDidFinishLoading:(id)arg1;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2;
-(BOOL)sendRequest:(id)arg1;
@end