/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:01 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "Config.h"

@interface KikHttpUploadChunk : KikContentULDL {
	SEL _progressCallback; 
	id _progressObject; 
	Config* _config; 
}
-(void)didSendBytes:(int)arg1;
-(id)initWithConfig:(id)arg1 data:(id)arg2 appId:(id)arg3 contentId:(id)arg4 totalChunks:(int)arg5 currentChunk:(int)arg6 totalSize:(int)arg7 mimeType:(id)arg8 contentType:(id)arg9 notifyWithProgress:(SEL)arg10 onObject:(id)arg11;
-(void)dealloc;
-(id)url;
@end