/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:04 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikIQNewPassword : KikIQ {
}
-(id)initWithEmail:(id)arg1 andUsername:(id)arg2 andPassword:(id)arg3;
@end