/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:42 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikLRUCache : NSObject {
	NSObject* _cacheLock; 
	id _callback; 
	SEL _tokenFromFilename; 
	SEL _filenameForToken; 
	SEL _shouldCacheExist; 
	int _maximumCacheElements; 
	NSMutableArray* _cachedItems; 
	NSString* _rootPath; 
}
@property (nonatomic,retain) NSString* rootPath; 				//@synthesize rootPath=_rootPath - In the implementation block
-(void)setRootPath:(id)arg1;
-(void)loadFileSystemTokens;
-(id)lastAccessForFile:(id)arg1;
-(void)trimCacheToSize;
-(id)tokenToFilename:(id)arg1;
-(id)filenameToFilePath:(id)arg1;
-(id)tokenToFilePath:(id)arg1;
-(id)findCacheItemForToken:(id)arg1;
-(void)insertCacheItem:(id)arg1 withData:(id)arg2;
-(void)clearCacheItem:(id)arg1;
-(id)initAtRootPath:(id)arg1 withSize:(int)arg2 withCallback:(id)arg3 onTokenFromFilename:(SEL)arg4 onCacheRequiredCheck:(SEL)arg5 onFilenameForToken:(SEL)arg6;
-(id)filenameToToken:(id)arg1;
-(void)writeToCacheItem:(id)arg1 withData:(id)arg2 atOffset:(int)arg3;
-(id)filePathForCacheItem:(id)arg1;
-(int)sizeOfCacheItem:(id)arg1;
-(void)touchCacheItem:(id)arg1;
-(void)removeCacheItem:(id)arg1;
-(id)dataForToken:(id)arg1;
-(BOOL)hasCacheForToken:(id)arg1;
@end