/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:36:42 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikMessageHelper : KikStorageHelper {
	NSMutableDictionary* _heightCache; 
}
-(void)saveHeightCache;
-(int)numberOfMessagesWithState:(int)arg1 unchecked:(BOOL)arg2 type:(int)arg3;
-(int)numberOfMessagesWithState:(int)arg1 unchecked:(BOOL)arg2 type:(int)arg3 forUser:(id)arg4;
-(void)removeCachedBubbleHeightForMessage:(id)arg1;
-(id)newMessage;
-(id)messagesWithStanzaIds:(id)arg1;
-(id)allIncomingMessagesSince:(id)arg1;
-(id)incomingMessagesWithStanzaIds:(id)arg1;
-(id)messageWithStanzaId:(id)arg1;
-(id)incomingMessageWithStanzaId:(id)arg1;
-(int)numberOfMessagesWithState:(int)arg1 unchecked:(BOOL)arg2;
-(id)messagesWithState:(int)arg1 unchecked:(BOOL)arg2 type:(int)arg3;
-(id)messagesWithPicturesToReupload;
-(id)messagesWithSystemState:(int)arg1 unchecked:(BOOL)arg2 flag:(int)arg3 unchecked:(BOOL)arg4 type:(int)arg5;
-(int)unreadMessagesForAllUsers;
-(float)cachedBubbleHeightForMessage:(id)arg1;
-(void)setCachedBubbleHeight:(float)arg1 forMessage:(id)arg2;
-(void)clearAllCachedBubbleHeights;
-(int)unreadMessagesForUser:(id)arg1;
-(void)deleteMessagesWithUser:(id)arg1;
-(id)heightCache;
@end