/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 12:57:29 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import <CoreData/NSManagedObject.h>

@interface KikManagedObject : NSManagedObject {
}
@end