/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:36:38 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikMediaHelper : KikStorageHelper {
}
-(id)attachmentsForMessage:(id)arg1;
-(int)numberOfLocallyCachedAttachments;
-(id)attachmentsRequringReupload;
-(void)deleteAttachment:(id)arg1;
-(id)newAttachmentWithToken:(id)arg1 andType:(int)arg2;
@end