/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 30041 AM Mountain Daylight Time
 * Operating System Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol KikProfilePictureStorage
@required
-(id)initWithDirectory:(id)arg1 andFileName:(id)arg2 ;
-(BOOL)saveProfilePicture:(id)arg1 forUserJid:(id)arg2 ;
-(id)loadProfilePictureForUserJid:(id)arg1 ;
-(BOOL)pictureExistsForUserJid:(id)arg1 ;
-(BOOL)deleteProfilePictureForUserJid:(id)arg1 ;
-(BOOL)clearAllProfilePictures;
-(id)allProfilePictureJids;
-(id)initWithDirectory:(id)arg1 andFileName:(id)arg2 ;
-(BOOL)saveProfilePicture:(id)arg1 forUserJid:(id)arg2 ;
-(id)loadProfilePictureForUserJid:(id)arg1 ;
-(BOOL)pictureExistsForUserJid:(id)arg1 ;
-(BOOL)deleteProfilePictureForUserJid:(id)arg1 ;
-(BOOL)clearAllProfilePictures;
-(id)allProfilePictureJids;
@end
