/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:04 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikPersistentCache : NSObject {
	NSObject* _cacheLock; 
	NSMutableArray* _cachedItems; 
	NSString* _rootPath; 
	NSString* _rawDataPath; 
	NSString* _userDataPath; 
	NSMutableDictionary* _userDataCache; 
}
@property (nonatomic,retain) NSString* rootPath; 				//@synthesize rootPath=_rootPath - In the implementation block
@property (nonatomic,retain) NSString* rawDataPath; 				//@synthesize rawDataPath=_rawDataPath - In the implementation block
@property (nonatomic,retain) NSString* userDataPath; 				//@synthesize userDataPath=_userDataPath - In the implementation block
-(void)setRootPath:(id)arg1;
-(void)loadFileSystemTokens;
-(id)findCacheItemForToken:(id)arg1;
-(void)clearCacheItem:(id)arg1;
-(void)removeCacheItem:(id)arg1;
-(id)dataForToken:(id)arg1;
-(id)initAtRootPath:(id)arg1;
-(id)allTokens;
-(void)clearAllItems;
-(void)updateUserData:(id)arg1 forToken:(id)arg2;
-(id)userDataForToken:(id)arg1;
-(void)insertCacheItem:(id)arg1 withUserData:(id)arg2 withData:(id)arg3;
-(void)setUserDataPath:(id)arg1;
-(void)setRawDataPath:(id)arg1;
-(id)loadUserDataFromFile:(id)arg1;
-(id)tokenForFilename:(id)arg1;
-(id)filenameForToken:(id)arg1;
-(void)saveUserData:(id)arg1 ToFile:(id)arg2;
-(void)updateContent:(id)arg1 forToken:(id)arg2;
@end