/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:36:24 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikPictureHelper : NSObject {
	NSMutableDictionary* _tempTokens; 
	NSMutableArray* _uploadedTempTokens; 
	NSMutableDictionary* _profilePictureThumbCache; 
	NSMutableDictionary* _mediaSource; 
	UIImage* profilePicture; 
	UIImage* temporaryProfilePicture; 
}
@property (nonatomic,retain) UIImage* profilePicture; 
@property (nonatomic,copy) NSData* profilePictureData; 
@property (nonatomic,retain) UIImage* temporaryProfilePicture; 
@property (nonatomic,copy) NSData* temporaryProfilePictureData; 
@property (nonatomic,copy) UIImage* profilePictureThumb; 
-(id)originalDataForJid:(id)arg1;
-(id)thumbForJid:(id)arg1;
-(void)clearMemoryCache;
-(void)setPictureData:(id)arg1 forJid:(id)arg2 sizeIdentifier:(int)arg3;
-(id)conversationPictureThumbDataWithId:(id)arg1;
-(id)originalForJid:(id)arg1;
-(void)setPicture:(id)arg1 forJid:(id)arg2 sizeIdentifier:(int)arg3;
-(void)writePictureData:(id)arg1 forJid:(id)arg2 sizeIdentifier:(int)arg3;
-(void)writePicture:(id)arg1 forJid:(id)arg2 sizeIdentifier:(int)arg3;
-(id)thumbForJid:(id)arg1 allowFileLoading:(BOOL)arg2;
-(void)writeTempConversationPictureData:(id)arg1 forJid:(id)arg2 pictureId:(int)arg3;
-(void)writeConversationPictureData:(id)arg1 withStanzaId:(id)arg2;
-(id)tempConversationPictureForJid:(id)arg1 pictureId:(int)arg2;
-(id)tempConversationThumbPictureForJid:(id)arg1 pictureId:(int)arg2;
-(void)deleteTempConversationPictures;
-(BOOL)tokenIsLoaded:(id)arg1;
-(void)setProfilePicture:(id)arg1;
-(void)setTemporaryProfilePicture:(id)arg1;
-(id)thumbForGroup:(id)arg1;
-(void)clearCachedProfilePictures;
-(void)clearCachedAttachmentsDir;
-(void)writeTempConversationPicture:(id)arg1 forJid:(id)arg2 pictureId:(int)arg3;
-(void)writeConversationPicture:(id)arg1 withStanzaId:(id)arg2;
-(void)writeConversationPictureThumbData:(id)arg1 withStanzaId:(id)arg2;
-(id)conversationPictureThumbWithId:(id)arg1;
-(void)removeTempConversationPictureForJid:(id)arg1 pictureId:(int)arg2;
-(id)tempConversationPictureDataForJid:(id)arg1 pictureId:(int)arg2;
-(id)conversationPictureWithStanzaId:(id)arg1;
-(id)conversationPictureDataWithStanzaId:(id)arg1;
-(id)conversationPictureToUploadDataWithStanzaId:(id)arg1;
-(id)tempConversationThumbPictureDataForJid:(id)arg1 pictureId:(int)arg2;
-(void)moveTempPictureForJid:(id)arg1 pictureIndex:(int)arg2 toToken:(id)arg3;
-(void)copyTempPictureForUploadForJid:(id)arg1 pictureIndex:(int)arg2 toToken:(id)arg3;
-(id)tokenForJid:(id)arg1 tempPictureId:(int)arg2;
-(id)mediaSourceForJid:(id)arg1 tempPictureId:(int)arg2;
-(void)setMediaSource:(id)arg1 forJid:(id)arg2 tempPictureId:(int)arg3;
-(void)removeTempTokensForJid:(id)arg1;
-(void)removeTempTokenForJid:(id)arg1 pictureId:(int)arg2;
-(void)markTokenAsLoaded:(id)arg1;
-(id)init;
@end