/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:36:13 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "KikStorage.h"
 #import "HybridViewController.h"
 #import "KikProfilePictureStorage.h"
@class KikStorage;

@interface KikProfilePictureHelper : NSObject {
	id _callback; 
	NSTimer* _uploadTimer; 
	KikStorage* _storage; 
	HybridViewController* _controller; 
	UIImagePickerController* _picker; 
	NSObject* _profilePictureCacheLock; 
	NSObject* _profilePictureUpdateLock; 
	NSMutableDictionary* _profilePictureCache; 
	UIImage* _defaultProfileImage; 
	UIImage* _defaultBlurredProfileImage; 
	UIImage* _defaultGroupImage; 
	UIImage* _defaultRawBlurredProfileImage; 
	id<KikProfilePictureStorage> _profilePictureStorage; 
	BOOL _applyBlurToUsersNotInRoster; 
}
@property (assign,nonatomic) BOOL applyBlurToUsersNotInRoster; 				//@synthesize applyBlurToUsersNotInRoster=_applyBlurToUsersNotInRoster - In the implementation block
-(void)blockStatusChanged:(id)arg1;
-(id)defaultProfileImage;
-(id)profilePictureForUser:(id)arg1;
-(id)initWithStorage:(id)arg1 andProfilePictureStorage:(id)arg2;
-(void)updateProfilePicturesForUser:(id)arg1 withForce:(BOOL)arg2;
-(void)setProfilePicture:(id)arg1 andController:(id)arg2 andCallback:(id)arg3 andPicker:(id)arg4;
-(void)generatePictureForUser:(id)arg1 withCallback:(id)arg2;
-(void)setApplyBlurToUsersNotInRoster:(BOOL)arg1;
-(void)generateDefaultProfileImages;
-(void)inRosterChanged:(id)arg1;
-(void)updateProfilePicturesForUserJids:(id)arg1 withForce:(BOOL)arg2;
-(void)doUploadPicture;
-(void)callbackUploadPicture:(id)arg1;
-(void)uploadTimedOut;
-(void)generatePictureForUser:(id)arg1;
-(void)createProfilePictureForUser:(id)arg1 withSize:(CGSize)arg2 withCallback:(id)arg3;
-(id)defaultGroupImage;
-(void)dealloc;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(void)reset;
@end