/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 2:12:54 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikRetryCountStore : NSObject {
	NSString* _filename; 
	NSString* _filePath; 
	NSMutableDictionary* _retryCountMap; 
}
@property (nonatomic,copy,copy) NSString* filename; 				//@synthesize filename=_filename - In the implementation block
@property (nonatomic,copy) NSString* filePath; 				//@synthesize filePath=_filePath - In the implementation block
@property (nonatomic,retain) NSMutableDictionary* retryCountMap; 				//@synthesize retryCountMap=_retryCountMap - In the implementation block
-(id)retryCountEntryForId:(id)arg1 operationType:(id)arg2;
-(void)deleteRetryCountForEntry:(id)arg1;
-(void)saveRetryCountEntry:(id)arg1;
-(void)deleteRetryCountForId:(id)arg1 operationType:(id)arg2;
-(void)deleteAllRetryCounts;
-(void)setRetryCountMap:(id)arg1;
-(BOOL)retryCountExistsForId:(id)arg1 operationType:(id)arg2;
-(void)save;
-(id)init;
-(void)load;
-(id)initWithFilename:(id)arg1;
@end