/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 11450 AM Mountain Daylight Time
 * Operating System Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol RetryStrategyDelegate
@required
-(void)retryStrategyDidAdviseRetry:(id)arg1 ;
-(void)retryStrategyDidAdviseRetry:(id)arg1 ;
@end

@protocol XmppStreamDelegate
@required
-(void)xmppStream:(id)arg1 didReceiveError:(id)arg2 ;
-(void)xmppStream:(id)arg1 didReceiveXml:(id)arg2 ;
-(void)xmppStreamDidWriteData:(id)arg1 ;
-(void)xmppStream:(id)arg1 didReceiveError:(id)arg2 ;
-(void)xmppStream:(id)arg1 didReceiveXml:(id)arg2 ;
-(void)xmppStreamDidWriteData:(id)arg1 ;
@end

@protocol KikStanzaManagerDelegate
@required
-(id)stanzasReadyToSend:(id)arg1 ;
-(void)stanzaTimedOut;
-(id)stanzasReadyToSend:(id)arg1 ;
-(void)stanzaTimedOut;
@end
