/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:00:24 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol KikStanzaAckManagerDelegate
@required
-(void)ackTimeout;
-(void)ackTimeout;
@end
