/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:06:57 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikStanzaAckManager : NSObject {
	id<KikStanzaAckManagerDelegate> _ackDelegate; 
	NSMutableDictionary* _stanzasWaitingForAck; 
	NSTimer* _ackTimer; 
	NSObject* _ackTimerLockObject; 
	double _ackTimeoutInterval; 
}
@property (assign) double ackTimeoutInterval; 				//@synthesize ackTimeoutInterval=_ackTimeoutInterval - In the implementation block
-(void)clearAllStanzasWaitingForAcks;
-(id)receivedStanzaAckWithID:(id)arg1;
-(BOOL)stanzaIsWaitingForAck:(id)arg1;
-(void)queueAckForStanza:(id)arg1;
-(id)unackedStanzas;
-(void)removeStanzaWaitingForAck:(id)arg1;
-(void)refreshAckTimer;
-(void)ackTimedOut;
-(void)setAckTimeoutInterval:(double)arg1;
-(id)initWithDelegate:(id)arg1;
@end