/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:14 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikSendMessageTask : NSObject {
	id _completed; 
	id _cancelled; 
	id _error; 
	BOOL _isDone; 
	NSObject* _doneLock; 
	KikAPIMessage* _message; 
	NSString* _convoId; 
}
@property (nonatomic,copy) id completed; 				//@synthesize completed=_completed - In the implementation block
@property (nonatomic,copy) id cancelled; 				//@synthesize cancelled=_cancelled - In the implementation block
@property (nonatomic,copy) id error; 				//@synthesize error=_error - In the implementation block
@property (nonatomic,@dynamic,retain) KikAPIMessage* message; 
@property (nonatomic,@dynamic,copy) NSString* convoId; 
-(void)setConvoId:(id)arg1;
-(void)fail:(id)arg1;
-(void)checkCompletion;
-(void)setCompleted:(id)arg1;
-(void)setError:(id)arg1;
-(id)init;
-(void)setCancelled:(id)arg1;
-(void)setMessage:(id)arg1;
-(void).cxx_destruct;
@end