/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:00:24 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import "KikStanzaAckManagerDelegate.h"
 #import "KikStanzaAckManager.h"
 #import "KikStanzaManager.h"
 #import "ChallengeProblemSolver.h"

@interface KikStanzaManager : NSObject <KikStanzaAckManagerDelegate> {
	KikStanzaAckManager* _ackManager; 
	NSMutableArray* _stanzasWaitingToSend; 
	NSMutableDictionary* _stanzasWaitingForResponse; 
	NSMutableArray* _stanzasSent; 
	NSMutableDictionary* _stanzasOnHold; 
	NSTimer* _stanzaExpiryTimer; 
	NSObject* _stanzasStateLock; 
	ChallengeProblemSolver* _problemSolver; 
	id<KikStanzaManagerDelegate> _stanzaDelegate; 
}
@property (copy) NSMutableArray* stanzasWaitingToSend; 				//@synthesize stanzasWaitingToSend=_stanzasWaitingToSend - In the implementation block
@property (copy) NSMutableDictionary* stanzasWaitingForResponse; 				//@synthesize stanzasWaitingForResponse=_stanzasWaitingForResponse - In the implementation block
-(id)initWithStanzaDelegate:(id)arg1 problemSolver:(id)arg2;
-(void)clearAllStanzas;
-(void)sendStanza:(id)arg1;
-(void)sendAllWaitingStanzas;
-(void)prepareUnackedStanzasForSending;
-(void)expireUnrespondedStanzas;
-(void)clearAllStanzasWaitingForAcks;
-(void)clearPendingChallenges;
-(void)receivedStanzaWithXMLElement:(id)arg1;
-(void)receivedStanzaAckWithID:(id)arg1;
-(void)receivedChallengeWithXMLElement:(id)arg1;
-(void)receivedHoldOnStanza:(id)arg1 forChallenge:(id)arg2;
-(void)updateStanzaExpiryTimer;
-(void)sendStanzasInQueue:(id)arg1;
-(void)receivedStanzaWithXMLElement:(id)arg1 elementId:(id)arg2;
-(void)expiryTimerHandler;
-(void)challengeCompleted:(id)arg1 solution:(id)arg2;
-(void)ackTimeout;
@end