/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:14:43 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIKit/UIAlertView.h>
#import "Config.h"
 #import "KikMessageHelper.h"
 #import "KikUserDefaultsHelperBackend.h"
 #import "KikUserDefaultsHelperProxy.h"
 #import "KikProfilePictureHelper.h"
 #import "KikPictureHelper.h"
 #import "KikMediaHelper.h"
 #import "KikAckQueueHelper.h"
 #import "FRCBlockedMessagesUnflaggedChats.h"
 #import "FRCAllContacts.h"
 #import "KikMessageHelper.h"

@interface KikStorage : NSObject <UIAlertViewDelegate> {
	NSBundle* _bundle; 
	Config* _config; 
	NSManagedObjectContext* _managedObjectContext; 
	NSPersistentStoreCoordinator* _persistentStoreCoordinator; 
	NSObject* _persistentStoreLock; 
	NSManagedObjectModel* _managedObjectModel; 
	NSManagedObjectID* _managedObjectId; 
	NSMutableDictionary* _fetchedResultsControllerCache; 
	KikMessageHelper* _messages; 
	KikUserHelper* _users; 
	KikUserDefaultsHelperBackend* _defaultsBackend; 
	KikUserDefaultsHelperProxy* _defaultsProxy; 
	KikProfilePictureHelper* _profilePicture; 
	KikPictureHelper* _pictures; 
	KikChatHelper* _chats; 
	KikMediaHelper* _media; 
	KikAckQueueHelper* _ackQueue; 
	NSTimer* _autoSaveTimer; 
	FRCBlockedMessagesUnflaggedChats* _blockedMessagesUnflaggedChats; 
	FRCAllContacts* _allContacts; 
	BOOL _pendingSave; 
	NSException* _deathException; 
}
@property (nonatomic,copy) NSManagedObjectContext* managedObjectContext; 
@property (nonatomic,copy) NSManagedObjectModel* managedObjectModel; 
@property (nonatomic,copy) KikMessageHelper* messages; 
@property (nonatomic,copy) KikUserHelper* users; 
@property (nonatomic,copy) KikUserDefaultsHelperProxy* defaults; 
@property (nonatomic,copy) KikAckQueueHelper* ackQueue; 
@property (nonatomic,copy) KikPictureHelper* pictures; 
@property (nonatomic,copy) KikProfilePictureHelper* profilePicture; 
@property (nonatomic,copy) KikChatHelper* chats; 
@property (nonatomic,copy) KikMediaHelper* media; 
@property (nonatomic,copy) NSString* jid; 
-(id)openChatsIgnoringNewPeople;
-(id)initWithBundle:(id)arg1 config:(id)arg2;
-(void)flagCoreDataWipeNextBootWithMessage:(id)arg1 andTitle:(id)arg2;
-(void)saveImmediately:(BOOL)arg1;
-(void)doSave;
-(void)showCoreDataError:(id)arg1;
-(void)enableAutoSaveWithInterval:(double)arg1;
-(void)wipeCoreDataNow;
-(id)getStorePath;
-(BOOL)hasMultitasking;
-(void)enableAutoSave;
-(void)disableAutoSave;
-(id)openChats;
-(id)openChatsIgnoringNewPeopleSearch;
-(id)openChatsIgnoringServerIgnored;
-(id)openServerIgnoredChats;
-(id)openChatsNewPeople;
-(id)leavingOpenGroupChats;
-(id)blockedMessagesUnflaggedChats;
-(id)allContacts;
-(id)allContactsExceptYourself;
-(id)exclusiveContacts:(id)arg1;
-(id)chatMessages:(id)arg1;
-(id)availableToBeBlocked;
-(id)composeContacts;
-(id)composeContactsWithUserFilter:(id)arg1;
-(void)deleteAllObjects:(id)arg1;
-(void)wipeLocalStorage;
-(void)save;
-(void)dealloc;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(id)lock;
-(id)blockList;
-(id)persistentStoreCoordinator;
-(id)initWithConfig:(id)arg1;
@end