/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:33:33 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "NSUserDefaultsHelperBackend.h"
 #import "KikUserDefaultsHelperProxy.h"

@interface KikUserDefaultsHelperBackend : NSUserDefaultsHelperBackend {
	KikUserDefaultsHelperProxy* _proxy; 
}
@property (assign,nonatomic) KikUserDefaultsHelperProxy* proxy; 				//@synthesize proxy=_proxy - In the implementation block
-(id)lastFullRosterRequestDate;
-(id)lastPushResendDate;
-(id)displayName;
-(void)setProxy:(id)arg1;
@end