/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 5:38:04 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "KikManagedObject.h"
#import "KikUserExtra.h"
 #import "KikMessage.h"

@interface KikUser : KikManagedObject {
	int _flags; 
	int _localFlags; 
	int _internalId; 
	int _presence; 
	int _type; 
	BOOL _profilePictureNeedsRerender; 
	BOOL _ackQueued; 
}
@property (nonatomic,copy) NSString* nameForDisplay; 
@property (nonatomic,copy) NSString* shortNameForDisplay; 
@property (assign,nonatomic) BOOL profilePictureNeedsRerender; 				//@synthesize profilePictureNeedsRerender=_profilePictureNeedsRerender - In the implementation block
@property (nonatomic,retain) NSNumber* addressBookId; 
@property (nonatomic,retain) NSString* displayName; 
@property (nonatomic,retain) NSString* displayNameAscii; 
@property (nonatomic,retain) NSString* firstName; 
@property (assign,nonatomic) int flags; 
@property (assign,nonatomic) int localFlags; 
@property (assign,nonatomic) int internalId; 
@property (nonatomic,retain) NSString* jid; 
@property (nonatomic,retain) NSString* lastName; 
@property (assign,nonatomic) int presence; 
@property (nonatomic,retain) NSString* status; 
@property (assign,nonatomic) int type; 
@property (nonatomic,retain) NSString* username; 
@property (nonatomic,retain) NSString* email; 
@property (nonatomic,retain) NSString* ppUrl; 
@property (nonatomic,retain) NSString* ppTimestamp; 
@property (nonatomic,retain) KikUserExtra* extra; 
@property (nonatomic,copy) NSString* displayNameInitial; 
@property (nonatomic,retain) NSSet* messages; 
@property (nonatomic,retain) NSSet* members; 
@property (nonatomic,retain) NSSet* membersInverse; 
@property (nonatomic,retain) KikMessage* lastMessage; 
@property (nonatomic) BOOL isKik; 
@property (assign,nonatomic) BOOL inRoster; 
@property (assign,nonatomic) BOOL isStub; 
@property (assign,nonatomic) BOOL shouldUpdatePicture; 
@property (assign,nonatomic) BOOL isGroup; 
@property (assign,nonatomic) BOOL ackRequired; 
@property (assign,nonatomic) BOOL isBlocked; 
@property (assign,nonatomic) BOOL isServerIgnored; 
@property (assign,nonatomic) BOOL ackQueued; 				//@synthesize ackQueued=_ackQueued - In the implementation block
-(void)setServerFlag:(int)arg1 value:(BOOL)arg2;
-(void)setInRoster:(BOOL)arg1;
-(void)setIsGroup:(BOOL)arg1;
-(void)setAckRequired:(BOOL)arg1;
-(void)removeMembers:(id)arg1;
-(void)addMembersObject:(id)arg1;
-(void)removeMembersObject:(id)arg1;
-(void)setIsStub:(BOOL)arg1;
-(void)setShouldUpdatePicture:(BOOL)arg1;
-(void)generateAsciiDisplayName;
-(void)setAckQueued:(BOOL)arg1;
-(void)setLocalFlags:(int)arg1;
-(void)setInternalId:(int)arg1;
-(void)setPresence:(int)arg1;
-(id)firstNameForDisplay;
-(id)getDisplayName;
-(void)setFlag:(int)arg1 value:(BOOL)arg2;
-(void)setProfilePictureNeedsRerender:(BOOL)arg1;
-(id)getUsername;
-(void)setIsServerIgnored:(BOOL)arg1;
-(void)addMembers:(id)arg1;
-(id)groupMembersString;
-(void)setType:(int)arg1;
-(BOOL)isFlagSet:(int)arg1;
-(void)setDisplayName:(id)arg1;
-(void)setFlags:(int)arg1;
-(void)setIsBlocked:(BOOL)arg1;
@end