/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 5:39:11 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "KikStorageHelper.h"

@interface KikUserHelper : KikStorageHelper {
	NSMutableDictionary* _jidsHash; 
	NSMutableDictionary* _usernamesHash; 
}
-(id)userWithJid:(id)arg1;
-(void)updateUser:(id)arg1 inRoster:(BOOL)arg2;
-(id)initWithManagedObjectContext:(id)arg1;
-(id)userWithUsername:(id)arg1;
-(id)newUserWithJid:(id)arg1;
-(id)firstUnsynchronizedUser;
-(void)updateUser:(id)arg1 inRoster:(BOOL)arg2 commitChanges:(BOOL)arg3;
-(id)allUsers;
-(id)usersWithJids:(id)arg1;
-(id)newUserExtra;
-(id)newUser;
-(unsigned)nonGroupUsersCount;
-(id)usersWithMessages;
-(id)recentUsersWithIgnored:(BOOL)arg1;
-(unsigned)groupsCount;
@end