/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 12:59:39 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "KikUser.h"
 @class KikUser;

@interface KikUserExtra : KikManagedObject {
	int _localFlags; 
}
@property (assign,nonatomic) int localFlags; 
@property (nonatomic,retain) KikUser* user; 
-(void)setLocalFlags:(int)arg1;
@end