/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:55 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KikViewController : UIViewController {
	NSString* _lastControllerTitle; 
	int _leftNavBarSize; 
	int _rightNavBarSize; 
	UIButton* _rightButton; 
	unsigned _orientationMask; 
}
@property (nonatomic,copy) NSString* lastControllerTitle; 				//@synthesize lastControllerTitle=_lastControllerTitle - In the implementation block
@property (nonatomic,copy) BOOL isLandscape; 
@property (assign,nonatomic) unsigned orientationMask; 				//@synthesize orientationMask=_orientationMask - In the implementation block
+(id)createNavigationBarButtonWithLabel:(id)arg1 andTarget:(id)arg2 andSelector:(SEL)arg3 andNormalButtonImageName:(id)arg4 andHighlightedButtonImageName:(id)arg5;
+(id)getNavigationTitleTextColour;
+(id)constructPaddedView:(id)arg1;
+(id)createDarkNavigationBarButtonWithLabel:(id)arg1 andTarget:(id)arg2 andSelector:(SEL)arg3;
+(id)createBlueNavigationBarButtonWithLabel:(id)arg1 andTarget:(id)arg2 andSelector:(SEL)arg3;
+(void)setBackgroundImage:(id)arg1 forView:(id)arg2;
-(void)setOrientationMask:(unsigned)arg1;
-(void)fixNavigationItemTitleColour:(id)arg1 title:(id)arg2;
-(id)navigationTitleFont;
-(int)titleViewWidth;
-(void)setNavigationItem:(id)arg1 withBackGround:(id)arg2 onPressCallback:(SEL)arg3 navItem:(int)arg4 buttonType:(int)arg5 textColor:(int)arg6 contentInset:(int)arg7 withIconPadding:(CGSize)arg8;
-(id)makeNavigationItem:(id)arg1 withBackGround:(id)arg2 onPressCallback:(SEL)arg3 navItem:(int)arg4 buttonType:(int)arg5 textColor:(int)arg6 contentInset:(int)arg7 andIconPadding:(CGSize)arg8;
-(void)leftBarButtonCallback;
-(void)setNavigationItem:(id)arg1 withBackGround:(id)arg2 onPressCallback:(SEL)arg3 navItem:(int)arg4 buttonType:(int)arg5 textColor:(int)arg6 contentInset:(int)arg7;
-(void)setRightNavigationBarBlueButton:(id)arg1 type:(int)arg2;
-(void)rightBarButtonCallback;
-(void)updateTitleFrame;
-(void)setLeftNavigationBarBackButton:(id)arg1;
-(void)fixNavigationItemTitleColour:(id)arg1 title:(id)arg2 min:(BOOL)arg3;
-(void)setBackButton;
-(void)setRightNavigationBarBlueButton:(id)arg1;
-(void)setRightNavigationBarBlueButton:(id)arg1 type:(int)arg2 withIconPadding:(CGSize)arg3;
-(void)setNavigationButton:(id)arg1 navItem:(int)arg2 type:(int)arg3;
-(void)enableRightNavigationBarButton:(BOOL)arg1;
-(void)setLastControllerTitle:(id)arg1;
-(id)init;
-(unsigned)supportedInterfaceOrientations;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(BOOL)textFieldShouldBeginEditing:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewDidLoad;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(void).cxx_destruct;
-(void)setLeftNavigationBarButton:(id)arg1;
-(void)setup;
@end