/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:30 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol MediaTrayApp
@optional
-(id)iconURL;
-(id)icon;
@required
-(int)appType;
-(id)appName;
-(id)appID;
-(int)appType;
-(id)appName;
-(id)appID;
@end
