/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:11 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MessageListTableView : TouchableTableView {
}
-(void)setScrollIndicatorInsets:(struct UIEdgeInsets)arg1 withForce:(BOOL)arg2;
-(void)setContentInset:(struct UIEdgeInsets)arg1 withForce:(BOOL)arg2;
-(void)setContentInset:(struct UIEdgeInsets)arg1;
-(void)setScrollIndicatorInsets:(struct UIEdgeInsets)arg1;
@end