/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:02:01 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <HPGrowingTextViewDelegate.h>
#import <ContentMessageViewDelegate.h>
#import <UIActionSheetDelegate.h>

@interface MessageTextBarController : UIViewController <HPGrowingTextViewDelegate, ContentMessageViewDelegate, UIActionSheetDelegate> {
	BOOL _contentReplaceConfirmed; 
	BOOL _keyboardShown; 
	BOOL _isLayingOut; 
	BOOL _mediaIconRotated; 
	BOOL _avoidAnimation; 
	id<MessageTextBarDelegate> _delegate; 
	KikAPIMessage* _content; 
	KikAPIMessage* _pendingContent; 
	ContentMessageView* _contentMessageView; 
	int _contentContext; 
	UIView* _contentViewWrapper; 
	UIView* _textFieldWrapper; 
	HPGrowingTextView* _textView; 
	TwoLayerButton* _mediaButton; 
	UIButton* _smileyButton; 
	UIButton* _sendButton; 
	BlurryUIView* _blurryBackground; 
	UIActionSheet* _confirmReplaceSheet; 
	id _keyboardNotificationIdentifier; 
}
@property (assign,nonatomic,__weak) id<MessageTextBarDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) KikAPIMessage* content; 				//@synthesize content=_content - In the implementation block
@property (nonatomic,retain) KikAPIMessage* pendingContent; 				//@synthesize pendingContent=_pendingContent - In the implementation block
@property (nonatomic,retain) ContentMessageView* contentMessageView; 				//@synthesize contentMessageView=_contentMessageView - In the implementation block
@property (assign,nonatomic) BOOL contentReplaceConfirmed; 				//@synthesize contentReplaceConfirmed=_contentReplaceConfirmed - In the implementation block
@property (assign,nonatomic) int contentContext; 				//@synthesize contentContext=_contentContext - In the implementation block
@property (assign,nonatomic,__weak) UIView* contentViewWrapper; 				//@synthesize contentViewWrapper=_contentViewWrapper - In the implementation block
@property (assign,nonatomic,__weak) UIView* textFieldWrapper; 				//@synthesize textFieldWrapper=_textFieldWrapper - In the implementation block
@property (assign,nonatomic,__weak) HPGrowingTextView* textView; 				//@synthesize textView=_textView - In the implementation block
@property (assign,nonatomic,__weak) TwoLayerButton* mediaButton; 				//@synthesize mediaButton=_mediaButton - In the implementation block
@property (assign,nonatomic,__weak) UIButton* smileyButton; 				//@synthesize smileyButton=_smileyButton - In the implementation block
@property (assign,nonatomic,__weak) UIButton* sendButton; 				//@synthesize sendButton=_sendButton - In the implementation block
@property (assign,nonatomic,__weak) BlurryUIView* blurryBackground; 				//@synthesize blurryBackground=_blurryBackground - In the implementation block
@property (assign,nonatomic) BOOL keyboardShown; 				//@synthesize keyboardShown=_keyboardShown - In the implementation block
@property (assign,nonatomic) BOOL isLayingOut; 				//@synthesize isLayingOut=_isLayingOut - In the implementation block
@property (nonatomic,retain) UIActionSheet* confirmReplaceSheet; 				//@synthesize confirmReplaceSheet=_confirmReplaceSheet - In the implementation block
@property (assign,nonatomic) BOOL mediaIconRotated; 				//@synthesize mediaIconRotated=_mediaIconRotated - In the implementation block
@property (assign,nonatomic) BOOL avoidAnimation; 				//@synthesize avoidAnimation=_avoidAnimation - In the implementation block
@property (nonatomic,retain) id keyboardNotificationIdentifier; 				//@synthesize keyboardNotificationIdentifier=_keyboardNotificationIdentifier - In the implementation block
+(id)controller;
-(void)setTextFieldWrapper:(id)arg1;
-(void)layoutSubviewsAnimated:(BOOL)arg1;
-(void)rotateMediaButton;
-(void)unrotateMediaButton;
-(void)confirmContentReplacement;
-(void)smileyTouched:(id)arg1;
-(void)setContentContext:(int)arg1;
-(void)setMediaIconRotated:(BOOL)arg1;
-(void)setAvoidAnimation:(BOOL)arg1;
-(void)setContentMessageView:(id)arg1;
-(void)registerNotifications;
-(void)updateKeyboardReturnKey;
-(void)setKeyboardNotificationIdentifier:(id)arg1;
-(void)configureContentViewWrapper;
-(void)configureTextFieldWrapper;
-(void)configureTextView;
-(void)setKeyboardShown:(BOOL)arg1;
-(void)setIsLayingOut:(BOOL)arg1;
-(void)sizeContentWrapper;
-(void)layoutTextView;
-(void)actuallySetContent:(id)arg1;
-(void)setPendingContent:(id)arg1;
-(BOOL)returnKeyPressed;
-(void)actionSheet:(id)arg1 didClickWithButtonIndex:(int)arg2;
-(void)setConfirmReplaceSheet:(id)arg1;
-(BOOL)growingTextViewShouldBeginEditing:(id)arg1;
-(BOOL)growingTextViewShouldEndEditing:(id)arg1;
-(void)growingTextViewDidBeginEditing:(id)arg1;
-(BOOL)growingTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
-(void)growingTextViewDidChange:(id)arg1;
-(void)growingTextViewDidChangeText:(id)arg1;
-(void)growingTextView:(id)arg1 didChangeHeight:(float)arg2;
-(void)contentMessageViewButtonClicked:(id)arg1;
-(void)hideMediaTrayButton;
-(void)mediaButtonTouched:(id)arg1;
-(void)smileyButtonTouched:(id)arg1;
-(void)sendButtonTouched:(id)arg1;
-(void)setContentReplaceConfirmed:(BOOL)arg1;
-(void)setContentViewWrapper:(id)arg1;
-(void)setMediaButton:(id)arg1;
-(void)setSmileyButton:(id)arg1;
-(void)setBlurryBackground:(id)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(void)layoutSubviews;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(void)setTextView:(id)arg1;
-(void)clearText;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(float)preferredHeight;
-(void).cxx_destruct;
-(BOOL)isLandscape;
-(void)setSendButton:(id)arg1;
-(void)resetState;
-(void)keyboardWillShow:(id)arg1;
-(void)keyboardWillHide:(id)arg1;
-(void)setContent:(id)arg1;
@end