/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 9:16:34 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import "RetryStrategyDelegate.h"

@interface MetricsManager : NSObject <RetryStrategyDelegate> {
	NSString* _userID; 
	NSString* _devicePrefix; 
	NSString* _userUUID; 
	KikStorage* _storage; 
	id<MetricsDataHandler> _dataHandler; 
	BOOL _enabled; 
	NSObject* _lockObject; 
	ExponentialBackoffRetryStrategy* _retryStrategy; 
	SecureXDataManager* _xDataManager; 
}
@property (nonatomic,retain) NSString* userID; 				//@synthesize userID=_userID - In the implementation block
@property (nonatomic,retain) NSString* userUUID; 				//@synthesize userUUID=_userUUID - In the implementation block
@property (nonatomic,retain) NSString* devicePrefix; 				//@synthesize devicePrefix=_devicePrefix - In the implementation block
//@property (nonatomic,copy) id<MetricsDataHandler> dataHandler; 				//@synthesize dataHandler=_dataHandler - In the implementation block
-(void)addUserEvent:(int)arg1 withExtraData:(id)arg2;
-(void)addPacketEvent:(int)arg1 withPacketID:(id)arg2 andExtraData:(id)arg3;
-(void)retryStrategyDidAdviseRetry:(id)arg1;
-(void)addUserEvent:(int)arg1;
-(void)authenticationDidChange:(id)arg1;
-(id)initWithStorage:(id)arg1 andDataHandler:(id)arg2 andXDataManager:(id)arg3;
-(void)onUserRegisteredOrJustLoggedIn:(id)arg1;
-(void)setDevicePrefix:(id)arg1;
-(void)setUserUsingStorage:(id)arg1;
-(void)addUserEvent:(int)arg1 withExtraData:(id)arg2 andRelatedUser:(id)arg3;
-(void)processEventData:(id)arg1;
-(BOOL)userIsEnabled:(id)arg1;
-(void)getMetricAnonID;
-(void)setMetricsAnonID:(id)arg1;
-(void)addUserEvent:(int)arg1 withRelatedUser:(id)arg2;
-(void)addPacketEvent:(int)arg1 withPacketID:(id)arg2;
-(void)setUserUUID:(id)arg1;
-(void)flush;
-(void)reset;
-(void)setBatchSize:(int)arg1;
-(void)setUserID:(id)arg1;
-(int)batchSize;
@end