/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, July 6, 2014 at 120829 AM Mountain Daylight Time
 * Operating System Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol MetricsDataHandler
@required
-(void)flushAllEventData;
-(void)clearAllEventData;
-(void)processEventData:(id)arg1 withUserID:(id)arg2 andDevicePrefix:(id)arg3 andUserUUID:(id)arg4 ;
-(void)setBatchSize:(int)arg1 ;
-(int)batchSize;
-(void)flushAllEventData;
-(void)clearAllEventData;
-(void)processEventData:(id)arg1 withUserID:(id)arg2 andDevicePrefix:(id)arg3 andUserUUID:(id)arg4 ;
-(void)setBatchSize:(int)arg1 ;
-(int)batchSize;
@end
