/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:12 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Misc : NSObject {
}
+(void)runOnMain:(id)arg1;
+(BOOL)isiPad;
+(BOOL)isUnitTesting;
+(void)runOnMainLater:(id)arg1;
+(void)showMemoryUsage;
+(id)getPlatform;
+(void)runOnMain:(id)arg1 after:(double)arg2;
+(BOOL)isThirdGenerationiPod;
+(BOOL)isiPhone5;
+(BOOL)isiPhone;
+(BOOL)isEnglishLanguage;
+(id)currentLocaleBasedOnLanguage;
+(id)bundleVersion;
+(BOOL)isMainThread;
@end