/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:18 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIAlertViewDelegate.h>
#import <MPSurveyNavigationControllerDelegate.h>
#import <MPNotificationViewControllerDelegate.h>

@interface Mixpanel : NSObject <UIAlertViewDelegate, MPSurveyNavigationControllerDelegate, MPNotificationViewControllerDelegate> {
	unsigned _flushInterval; 
	BOOL _flushOnBackground; 
	BOOL _showNetworkActivityIndicator; 
	BOOL _checkForSurveysOnActive; 
	BOOL _showSurveyOnActive; 
	BOOL _checkForNotificationsOnActive; 
	BOOL _showNotificationOnActive; 
	MixpanelPeople* _people; 
	NSString* _distinctId; 
	NSString* _nameTag; 
	NSString* _serverURL; 
	id<MixpanelDelegate> _delegate; 
	NSString* _apiToken; 
	NSDictionary* _superProperties; 
	NSDictionary* _automaticProperties; 
	NSTimer* _timer; 
	NSMutableArray* _eventsQueue; 
	NSMutableArray* _peopleQueue; 
	unsigned _taskId; 
	NSObject<OS_dispatch_queue>* _serialQueue; 
	struct __SCNetworkReachability* _reachability; 
	CTTelephonyNetworkInfo* _telephonyInfo; 
	NSDateFormatter* _dateFormatter; 
	NSArray* _surveys; 
	MPSurvey* _currentlyShowingSurvey; 
	NSMutableSet* _shownSurveyCollections; 
	NSArray* _notifications; 
	MPNotification* _currentlyShowingNotification; 
	MPNotificationViewController* _notificationViewController; 
	NSMutableSet* _shownNotifications; 
}
@property (retain) MixpanelPeople* people; 				//@synthesize people=_people - In the implementation block
@property (copy) NSString* distinctId; 				//@synthesize distinctId=_distinctId - In the implementation block
@property (copy) NSString* nameTag; 				//@synthesize nameTag=_nameTag - In the implementation block
@property (copy) NSString* serverURL; 				//@synthesize serverURL=_serverURL - In the implementation block
@property (assign) unsigned flushInterval; 
@property (assign) BOOL flushOnBackground; 				//@synthesize flushOnBackground=_flushOnBackground - In the implementation block
@property (assign) BOOL showNetworkActivityIndicator; 				//@synthesize showNetworkActivityIndicator=_showNetworkActivityIndicator - In the implementation block
@property (assign) BOOL checkForSurveysOnActive; 				//@synthesize checkForSurveysOnActive=_checkForSurveysOnActive - In the implementation block
@property (assign) BOOL showSurveyOnActive; 				//@synthesize showSurveyOnActive=_showSurveyOnActive - In the implementation block
@property (assign) BOOL checkForNotificationsOnActive; 				//@synthesize checkForNotificationsOnActive=_checkForNotificationsOnActive - In the implementation block
@property (assign) BOOL showNotificationOnActive; 				//@synthesize showNotificationOnActive=_showNotificationOnActive - In the implementation block
@property (__weak) id<MixpanelDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString* apiToken; 				//@synthesize apiToken=_apiToken - In the implementation block
@property (retain) NSDictionary* superProperties; 				//@synthesize superProperties=_superProperties - In the implementation block
@property (retain) NSDictionary* automaticProperties; 				//@synthesize automaticProperties=_automaticProperties - In the implementation block
@property (nonatomic,retain) NSTimer* timer; 				//@synthesize timer=_timer - In the implementation block
@property (nonatomic,retain) NSMutableArray* eventsQueue; 				//@synthesize eventsQueue=_eventsQueue - In the implementation block
@property (nonatomic,retain) NSMutableArray* peopleQueue; 				//@synthesize peopleQueue=_peopleQueue - In the implementation block
@property (assign,nonatomic) unsigned taskId; 				//@synthesize taskId=_taskId - In the implementation block
@property (nonatomic,retain) NSObject<OS_dispatch_queue>* serialQueue; 				//@synthesize serialQueue=_serialQueue - In the implementation block
@property (assign,nonatomic) struct __SCNetworkReachability* reachability; 				//@synthesize reachability=_reachability - In the implementation block
@property (nonatomic,retain) CTTelephonyNetworkInfo* telephonyInfo; 				//@synthesize telephonyInfo=_telephonyInfo - In the implementation block
@property (nonatomic,retain) NSDateFormatter* dateFormatter; 				//@synthesize dateFormatter=_dateFormatter - In the implementation block
@property (nonatomic,retain) NSArray* surveys; 				//@synthesize surveys=_surveys - In the implementation block
@property (nonatomic,retain) MPSurvey* currentlyShowingSurvey; 				//@synthesize currentlyShowingSurvey=_currentlyShowingSurvey - In the implementation block
@property (nonatomic,retain) NSMutableSet* shownSurveyCollections; 				//@synthesize shownSurveyCollections=_shownSurveyCollections - In the implementation block
@property (nonatomic,retain) NSArray* notifications; 				//@synthesize notifications=_notifications - In the implementation block
@property (nonatomic,retain) MPNotification* currentlyShowingNotification; 				//@synthesize currentlyShowingNotification=_currentlyShowingNotification - In the implementation block
@property (nonatomic,retain) MPNotificationViewController* notificationViewController; 				//@synthesize notificationViewController=_notificationViewController - In the implementation block
@property (nonatomic,retain) NSMutableSet* shownNotifications; 				//@synthesize shownNotifications=_shownNotifications - In the implementation block
+(BOOL)inBackground;
+(void)assertPropertyTypes:(id)arg1;
+(id)topPresentedViewController;
+(id)sharedInstanceWithToken:(id)arg1;
+(id)sharedInstance;
-(void)track:(id)arg1 properties:(id)arg2;
-(void)notificationController:(id)arg1 wasDismissedWithStatus:(BOOL)arg2;
-(void)surveyController:(id)arg1 wasDismissedWithAnswers:(id)arg2;
-(id)initWithToken:(id)arg1 andFlushInterval:(unsigned)arg2;
-(void)setApiToken:(id)arg1;
-(void)setFlushOnBackground:(BOOL)arg1;
-(void)setShowNetworkActivityIndicator:(BOOL)arg1;
-(void)setShowNotificationOnActive:(BOOL)arg1;
-(void)setCheckForNotificationsOnActive:(BOOL)arg1;
-(id)defaultDistinctId;
-(void)setDistinctId:(id)arg1;
-(void)setSuperProperties:(id)arg1;
-(id)collectAutomaticProperties;
-(void)setAutomaticProperties:(id)arg1;
-(void)setEventsQueue:(id)arg1;
-(void)setPeopleQueue:(id)arg1;
-(void)setSerialQueue:(id)arg1;
-(void)setDateFormatter:(id)arg1;
-(void)setShowSurveyOnActive:(BOOL)arg1;
-(void)setCheckForSurveysOnActive:(BOOL)arg1;
-(void)setSurveys:(id)arg1;
-(void)setCurrentlyShowingSurvey:(id)arg1;
-(void)setShownSurveyCollections:(id)arg1;
-(void)setShownNotifications:(id)arg1;
-(void)setCurrentlyShowingNotification:(id)arg1;
-(void)setNotifications:(id)arg1;
-(void)setReachability:(struct __SCNetworkReachability*)arg1;
-(void)setCurrentRadio;
-(void)unarchive;
-(id)currentRadio;
-(id)IFA;
-(id)JSONSerializableObjectForObject:(id)arg1;
-(id)JSONSerializeObject:(id)arg1;
-(void)archivePeople;
-(void)archiveProperties;
-(void)archiveEvents;
-(void)setNameTag:(id)arg1;
-(void)startFlushTimer;
-(void)stopFlushTimer;
-(void)flushEvents;
-(void)flushPeople;
-(void)flushQueue:(id)arg1 endpoint:(id)arg2;
-(id)encodeAPIData:(id)arg1;
-(id)apiRequestWithEndpoint:(id)arg1 andBody:(id)arg2;
-(void)updateNetworkActivityIndicator:(BOOL)arg1;
-(id)filePathForData:(id)arg1;
-(id)eventsFilePath;
-(id)peopleFilePath;
-(id)propertiesFilePath;
-(void)unarchiveEvents;
-(void)unarchivePeople;
-(void)unarchiveProperties;
-(void)showNotificationWithObject:(id)arg1;
-(void)showSurveyWithObject:(id)arg1 withAlert:(BOOL)arg2;
-(void)checkForDecideResponseWithCompletion:(id)arg1;
-(void)presentSurveyWithRootViewController:(id)arg1;
-(void)showSurveyWithObject:(id)arg1;
-(void)checkForSurveysWithCompletion:(id)arg1;
-(void)markSurvey:(id)arg1 shown:(BOOL)arg2 withAnswerCount:(unsigned)arg3;
-(void)checkForNotificationsWithCompletion:(id)arg1;
-(BOOL)showMiniNotificationWithObject:(id)arg1;
-(BOOL)showTakeoverNotificationWithObject:(id)arg1;
-(void)markNotificationShown:(id)arg1;
-(void)setNotificationViewController:(id)arg1;
-(void)trackNotification:(id)arg1 event:(id)arg2;
-(void)identify:(id)arg1;
-(void)createAlias:(id)arg1 forDistinctID:(id)arg2;
-(void)registerSuperProperties:(id)arg1;
-(void)registerSuperPropertiesOnce:(id)arg1;
-(void)registerSuperPropertiesOnce:(id)arg1 defaultValue:(id)arg2;
-(void)unregisterSuperProperty:(id)arg1;
-(void)clearSuperProperties;
-(id)currentSuperProperties;
-(void)setFlushInterval:(unsigned)arg1;
-(void)reachabilityChanged:(unsigned)arg1;
-(void)showSurveyWithID:(unsigned)arg1;
-(void)showNotificationWithType:(id)arg1;
-(void)showNotificationWithID:(unsigned)arg1;
-(void)setTelephonyInfo:(id)arg1;
-(void)setPeople:(id)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(id)description;
-(void)applicationWillTerminate:(id)arg1;
-(void)applicationDidBecomeActive:(id)arg1;
-(void)applicationWillResignActive:(id)arg1;
-(void)applicationDidEnterBackground:(id)arg1;
-(void)applicationWillEnterForeground:(id)arg1;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(void)reset;
-(void).cxx_destruct;
-(void)setTimer:(id)arg1;
-(void)setServerURL:(id)arg1;
-(void)track:(id)arg1;
-(void)setTaskId:(unsigned)arg1;
-(void)archive;
-(id)deviceModel;
@end