/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:14 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MPSurveyMultipleChoiceQuestion : MPSurveyQuestion {
	NSArray* _choices; 
}
@property (nonatomic,retain) NSArray* choices; 				//@synthesize choices=_choices - In the implementation block
-(id)initWithID:(unsigned)arg1 type:(id)arg2 prompt:(id)arg3 andChoices:(id)arg4;
-(void).cxx_destruct;
-(void)setChoices:(id)arg1;
@end