/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:12 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MPSurveyQuestion : NSObject {
	unsigned _ID; 
	NSString* _type; 
	NSString* _prompt; 
}
@property (assign,nonatomic) unsigned ID; 				//@synthesize ID=_ID - In the implementation block
@property (nonatomic,retain) NSString* type; 				//@synthesize type=_type - In the implementation block
@property (nonatomic,retain) NSString* prompt; 				//@synthesize prompt=_prompt - In the implementation block
+(id)questionWithJSONObject:(id)arg1;
-(id)initWithID:(unsigned)arg1 type:(id)arg2 andPrompt:(id)arg3;
-(void)setType:(id)arg1;
-(void)setPrompt:(id)arg1;
-(void).cxx_destruct;
-(void)setID:(unsigned)arg1;
@end