/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:18 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIAlertViewDelegate
@optional
-(void)alertView(id):arg1 clickedButtonAtIndex(int):arg2 ;
-(void)alertView(id):arg1 didDismissWithButtonIndex(int):arg2 ;
-(void)alertViewCancel(id):arg1 ;
-(BOOL)alertViewShouldEnableFirstOtherButton(id):arg1 ;
-(void)didPresentAlertView(id):arg1 ;
-(void)willPresentAlertView(id):arg1 ;
-(void)alertView(id):arg1 willDismissWithButtonIndex(int):arg2 ;
@end

@protocol MPSurveyNavigationControllerDelegate
@required
-(void)surveyController(id):arg1 wasDismissedWithAnswers(id):arg2 ;
-(void)surveyController(id):arg1 wasDismissedWithAnswers(id):arg2 ;
@end
