/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:47 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol NavigationListener
@required
-(void)shouldLoadUrl(id):arg1 ;
-(void)shouldLoadUrl(id):arg1 ;
@end
