/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:36 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NewPeopleFooterButton : UIButton {
	UIButton* _titleButton; 
	unsigned _cachedNumberOfMissedConversations; 
	BOOL _missedConversationViewVisible; 
	NSNumberFormatter* _numberFormatter; 
	BOOL _hasUnseenNewConversations; 
}
@property (assign,nonatomic) BOOL hasUnseenNewConversations; 				//@synthesize hasUnseenNewConversations=_hasUnseenNewConversations - In the implementation block
+(float)height;
-(void)setHasUnseenNewConversations:(BOOL)arg1;
-(void)onMissedConversationViewOpened:(id)arg1;
-(void)onMissedConversationViewDismissed:(id)arg1;
-(void)setHasUnseenNewConversations:(BOOL)arg1 withIncreasingNumberChange:(BOOL)arg2;
-(void)wiggleTitleWithAnimations:(id)arg1;
-(void)updateConversationCount:(unsigned)arg1;
-(void)setConversationCount:(unsigned)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)setHighlighted:(BOOL)arg1;
-(void).cxx_destruct;
-(void)setup;
@end