/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:01 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIWebViewDelegate
@optional
-(void)webView(id):arg1 didFailLoadWithError(id):arg2 ;
-(BOOL)webView(id):arg1 shouldStartLoadWithRequest(id):arg2 navigationType(int):arg3 ;
-(void)webViewDidStartLoad(id):arg1 ;
-(void)webViewDidFinishLoad(id):arg1 ;
@end

@protocol NJKWebViewProgressDelegate
@required
-(void)webViewProgress(id):arg1 updateProgress(float):arg2 ;
-(void)webViewProgress(id):arg1 updateProgress(float):arg2 ;
@end
