/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:14 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol NSCacheDelegate
@optional
-(void)cache(id):arg1 willEvictObject(id):arg2 ;
@end
