/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:44 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol NSURLConnectionDelegate
@optional
-(void)connection(id):arg1 didFailWithError(id):arg2 ;
-(BOOL)connectionShouldUseCredentialStorage(id):arg1 ;
-(void)connection(id):arg1 willSendRequestForAuthenticationChallenge(id):arg2 ;
-(BOOL)connection(id):arg1 canAuthenticateAgainstProtectionSpace(id):arg2 ;
-(void)connection(id):arg1 didReceiveAuthenticationChallenge(id):arg2 ;
-(void)connection(id):arg1 didCancelAuthenticationChallenge(id):arg2 ;
@end

@protocol NSURLConnectionDataDelegate
@optional
-(id)connection(id):arg1 willSendRequest(id):arg2 redirectResponse(id):arg3 ;
-(id)connection(id):arg1 willCacheResponse(id):arg2 ;
-(void)connection(id):arg1 didSendBodyData(int):arg2 totalBytesWritten(int):arg3 totalBytesExpectedToWrite(int):arg4 ;
-(id)connection(id):arg1 needNewBodyStream(id):arg2 ;
-(void)connection(id):arg1 didReceiveData(id):arg2 ;
-(void)connectionDidFinishLoading(id):arg1 ;
-(void)connection(id):arg1 didReceiveResponse(id):arg2 ;
@end
