/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:31:14 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import "OS_object.h"

@interface OS_dispatch_object : OS_object {
}
-(void)_dispose;
-(id)init;
-(id)debugDescription;
-(void)_xref_dispose;
@end