/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:29:39 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import "OS_dispatch_object.h"

@interface OS_dispatch_queue : OS_dispatch_object {
}
+(void)load;
-(id)description;
@end