/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:06 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PersistentCacheItem : NSObject {
	NSString* _token; 
	NSDictionary* _userdata; 
}
@property (nonatomic,retain) NSString* token; 				//@synthesize token=_token - In the implementation block
@property (nonatomic,retain) NSDictionary* userdata; 				//@synthesize userdata=_userdata - In the implementation block
-(void)setUserdata:(id)arg1;
-(id)initWithToken:(id)arg1 andUserData:(id)arg2;
-(void).cxx_destruct;
-(void)setToken:(id)arg1;
@end