/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:08 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PhotoPlugin : CardsPlugin {
	id<BrowserImplementation> _browser; 
	BOOL _savePhotoIsPending; 
	BOOL _getPhotoIsPending; 
	NSString* _cardUrl; 
	SavePhotoTask* _savePhotoTask; 
	id<PhotoHandler> _photoHandler; 
}
@property (nonatomic,copy) NSString* cardUrl; 				//@synthesize cardUrl=_cardUrl - In the implementation block
@property (nonatomic,retain) SavePhotoTask* savePhotoTask; 				//@synthesize savePhotoTask=_savePhotoTask - In the implementation block
@property (assign,nonatomic,__weak) id<PhotoHandler> photoHandler; 				//@synthesize photoHandler=_photoHandler - In the implementation block
@property (assign,nonatomic) BOOL savePhotoIsPending; 				//@synthesize savePhotoIsPending=_savePhotoIsPending - In the implementation block
@property (assign,nonatomic) BOOL getPhotoIsPending; 				//@synthesize getPhotoIsPending=_getPhotoIsPending - In the implementation block
-(id)initWithHandler:(id)arg1 browser:(id)arg2;
-(void)setCardUrl:(id)arg1;
-(id)getPhoto:(id)arg1 callback:(id)arg2;
-(id)savePhoto:(id)arg1 callback:(id)arg2;
-(void)raisePhotoEventForImage:(id)arg1 maxWidth:(int)arg2 maxHeight:(int)arg3 quality:(float)arg4 fromSource:(int)arg5 photoId:(id)arg6;
-(void)setSavePhotoTask:(id)arg1;
-(void)setSavePhotoIsPending:(BOOL)arg1;
-(void)setPhotoHandler:(id)arg1;
-(void)setGetPhotoIsPending:(BOOL)arg1;
-(void).cxx_destruct;
@end