/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:37 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol PopupViewProtocol
@optional
-(void)didBecomeTopMostPopupView;
-(void)viewWillPop;
@required
-(void)dismissPopupAnimated(BOOL):arg1 ;
-(id)popupViewURL;
-(BOOL)isTopMostPopupView;
-(id)view;
-(void)dismissPopupAnimated(BOOL):arg1 ;
-(id)popupViewURL;
-(BOOL)isTopMostPopupView;
-(id)view;
@end
