/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:17 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PopupSendToViewController : SendToViewController {
	BOOL _hasAppearedOnceBefore; 
}
+(id)controllerWithDelegate:(id)arg1 andContent:(id)arg2;
-(void)completeCallbackWithChat:(id)arg1;
-(void)contactSelected:(id)arg1 view:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
@end