/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:37 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PopupViewProtocol.h>

@interface PopupViewController : UIViewController <PopupViewProtocol> {
	UIView* _popupView; 
	UIButton* _popButton; 
	CGSize _xButtonSize; 
	id<PopupViewManagerProvider> _provider; 
	float _bottomVerticalSpacing; 
}
@property (nonatomic,copy) id<PopupViewManagerProvider> provider; 				//@synthesize provider=_provider - In the implementation block
-(void)dismissPopupAnimated:(BOOL)arg1;
-(void)viewDidFinishAnimating:(BOOL)arg1;
-(id)popupViewURL;
-(BOOL)isTopMostPopupView;
-(void)observeKeyboard:(BOOL)arg1;
-(void)closeButtonClicked;
-(void)viewDidPop;
-(void)dealloc;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)keyboardDidShow:(id)arg1;
-(void).cxx_destruct;
-(id)initWithProvider:(id)arg1;
-(void)keyboardWillHide:(id)arg1;
@end