/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:37 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PreloginSplashViewController : HybridViewController {
	UIButton* _registerButton; 
	UIButton* _loginButton; 
}
@property (assign,nonatomic,__weak) UIButton* registerButton; 				//@synthesize registerButton=_registerButton - In the implementation block
@property (assign,nonatomic,__weak) UIButton* loginButton; 				//@synthesize loginButton=_loginButton - In the implementation block
+(id)controller;
-(void)registerClicked:(id)arg1;
-(void)loginClicked:(id)arg1;
-(void)registerTouchDown:(id)arg1;
-(void)loginTouchDown:(id)arg1;
-(void)setRegisterButton:(id)arg1;
-(void)setLoginButton:(id)arg1;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void).cxx_destruct;
@end