/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 4:40:40 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "Config.h"

@interface ProductionConfig : Config {
}
-(id)init;
@end