/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:27 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ProfilePhotoView : UIView {
	KikUser* _user; 
	BlurredRawProfilePictureImageView* _profilePictureBackground; 
	ProfilePictureImageView* _profilePicture; 
	UILabel* _fullNameLabel; 
	UILabel* _usernameLabel; 
	UIButton* _actionButton; 
	id<ProfilePhotoViewDelegate> _delegate; 
	UIButton* _usernameButton; 
}
@property (nonatomic,retain) BlurredRawProfilePictureImageView* profilePictureBackground; 				//@synthesize profilePictureBackground=_profilePictureBackground - In the implementation block
@property (nonatomic,retain) ProfilePictureImageView* profilePicture; 				//@synthesize profilePicture=_profilePicture - In the implementation block
@property (nonatomic,retain) UILabel* fullNameLabel; 				//@synthesize fullNameLabel=_fullNameLabel - In the implementation block
@property (nonatomic,retain) UILabel* usernameLabel; 				//@synthesize usernameLabel=_usernameLabel - In the implementation block
@property (nonatomic,retain) UIButton* actionButton; 				//@synthesize actionButton=_actionButton - In the implementation block
@property (assign,nonatomic,__weak) id<ProfilePhotoViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UIButton* usernameButton; 				//@synthesize usernameButton=_usernameButton - In the implementation block
+(float)defaultHeight;
-(id)initWithFrame:(CGRect)arg1 andUser:(id)arg2;
-(void)setActionTitle:(id)arg1 withNormalTitleColor:(id)arg2 andHighlightedTitleColor:(id)arg3 andNormalBackground:(id)arg4 andHighlightedBackground:(id)arg5;
-(void)forceUpdateUI;
-(void)setProfilePicture:(id)arg1;
-(void)profilePictureTapped:(id)arg1;
-(void)setProfilePictureBackground:(id)arg1;
-(void)setFullNameLabel:(id)arg1;
-(void)setUsernameButton:(id)arg1;
-(void)usernameButtonTapped;
-(void)setActionButton:(id)arg1;
-(void)setUsernameLabel:(id)arg1;
-(void)actionButtonTapped:(id)arg1;
-(void)setDelegate:(id)arg1;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2;
-(void)setFrame:(CGRect)arg1;
-(void).cxx_destruct;
-(void)setUsername:(id)arg1;
-(void)setup;
@end