/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:00 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ProgressBarView : UIView {
	float _progress; 
	UIView* _progressOverlay; 
}
@property (assign,nonatomic) float progress; 				//@synthesize progress=_progress - In the implementation block
@property (nonatomic,retain) UIView* progressOverlay; 				//@synthesize progressOverlay=_progressOverlay - In the implementation block
-(void)setProgressOverlay:(id)arg1;
-(void)setProgressOverlayWidth:(float)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)setProgress:(float)arg1;
-(void)setProgressTintColor:(id)arg1;
-(void)setProgress:(float)arg1 animated:(BOOL)arg2;
-(void).cxx_destruct;
-(void)setup;
@end