/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:37:24 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Reachability : NSObject {
	BOOL localWiFiRef; 
	struct __SCNetworkReachability* reachabilityRef; 
}
+(id)reachabilityWithHostName:(id)arg1;
+(id)reachabilityWithAddress:(struct rsockaddr_in*)arg1;
+(id)reachabilityForInternetConnection;
+(id)reachabilityForLocalWiFi;
-(BOOL)startNotifier;
-(void)stopNotifier;
-(void)dealloc;
-(BOOL)connectionRequired;
-(int)localWiFiStatusForFlags:(unsigned)arg1;
-(int)networkStatusForFlags:(unsigned)arg1;
-(int)currentReachabilityStatus;
@end