/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:12:12 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol RetryStrategy
@property (nonatomic,retain) id<RetryStrategyDelegate> delegate; 
@required
-(BOOL)scheduleRetry;
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
-(void)reset;
-(BOOL)scheduleRetry;
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
-(void)reset;
@end
