/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:58 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SBJsonTokeniser : NSObject {
	SBJsonUTF8Stream* _stream; 
	NSString* _error; 
}
@property (copy) NSString* error; 				//@synthesize error=_error - In the implementation block
-(int)getToken:(id*)arg1;
-(BOOL)decodeHexQuad:(unsigned short*)arg1;
-(BOOL)decodeEscape:(unsigned short)arg1 into:(unsigned short*)arg2;
-(int)match:(r*)arg1 length:(unsigned)arg2 retval:(int)arg3;
-(int)getStringToken:(id*)arg1;
-(int)getNumberToken:(id*)arg1;
-(void)setError:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)appendData:(id)arg1;
@end