/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:02:05 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SBJsonStreamWriterState : NSObject {
}
+(id)sharedInstance;
-(BOOL)isInvalidState:(id)arg1;
-(BOOL)expectingKey:(id)arg1;
-(void)appendSeparator:(id)arg1;
-(void)appendWhitespace:(id)arg1;
-(void)transitionState:(id)arg1;
@end