/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:38 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol CardListDelegate
@required
-(void)cardListViewController(id):arg1 didSelectCard(id):arg2 ;
-(void)cardListViewController(id):arg1 didSelectCard(id):arg2 ;
@end

@protocol UITextFieldDelegate
@optional
-(BOOL)textFieldShouldBeginEditing(id):arg1 ;
-(void)textFieldDidBeginEditing(id):arg1 ;
-(BOOL)textFieldShouldEndEditing(id):arg1 ;
-(void)textFieldDidEndEditing(id):arg1 ;
-(BOOL)textField(id):arg1 shouldChangeCharactersInRange({):arg2 replacementString(_):arg3 ;
-(BOOL)textFieldShouldClear(id):arg1 ;
-(BOOL)textFieldShouldReturn(id):arg1 ;
@end

@protocol SearchResultsSidebarDelegate
@required
-(void)searchResultsSidebarTable(id):arg1 didSelectSearchResult(id):arg2 andIsWebPage(BOOL):arg3 ;
-(void)searchResultsDidScroll(id):arg1 ;
-(void)searchResultsSidebarTable(id):arg1 didSelectSearchResult(id):arg2 andIsWebPage(BOOL):arg3 ;
-(void)searchResultsDidScroll(id):arg1 ;
@end
