/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:02:05 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <RetryStrategyDelegate.h>

@interface ServerWithDiskCacheXDataProvider : DiskCacheXDataProvider <RetryStrategyDelegate> {
	KikNetwork* _network; 
	NSMutableDictionary* _recordsToUpload; 
	NSObject* _recordsToUploadLock; 
	NSObject* _retryRemainingRecordsLock; 
	BOOL _retryingRemainingRecords; 
	ExponentialBackoffRetryStrategy* _retryStrategy; 
}
-(void)retryStrategyDidAdviseRetry:(id)arg1;
-(void)onXmppConnected:(id)arg1;
-(id)initWithFileName:(id)arg1 andNetwork:(id)arg2;
-(id)promiseForRecordRetrieval:(id)arg1;
-(id)promiseForRecordUpdate:(id)arg1;
-(void)addRecordsToUpdate:(id)arg1;
-(void)recordsUpdated:(id)arg1;
-(void)updateRecordsNotProcessed:(id)arg1;
-(void)retryRemainingRecords;
-(void)reset;
-(void).cxx_destruct;
@end