/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, July 6, 2014 at 12:44:34 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import "RetryStrategyDelegate.h"
 #import "KikNetwork.h"
 #import "ExponentialBackoffRetryStrategy.h"

@interface ServerWithDiskCacheXDataProvider : DiskCacheXDataProvider <RetryStrategyDelegate> {
	KikNetwork* _network; 
	NSMutableDictionary* _recordsToUpload; 
	NSObject* _recordsToUploadLock; 
	NSObject* _retryRemainingRecordsLock; 
	BOOL _retryingRemainingRecords; 
	ExponentialBackoffRetryStrategy* _retryStrategy; 
}
-(void)retryStrategyDidAdviseRetry:(id)arg1;
-(void)onXmppConnected:(id)arg1;
-(id)initWithFileName:(id)arg1 andNetwork:(id)arg2;
-(id)promiseForRecordRetrieval:(id)arg1;
-(id)promiseForRecordUpdate:(id)arg1;
-(void)addRecordsToUpdate:(id)arg1;
-(void)recordsUpdated:(id)arg1;
-(void)updateRecordsNotProcessed:(id)arg1;
-(void)retryRemainingRecords;
-(void)reset;
@end