/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:38 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <CardListDelegate.h>
#import <UITextFieldDelegate.h>
#import <SearchResultsSidebarDelegate.h>

@interface SidebarViewController : KikViewController <CardListDelegate, UITextFieldDelegate, SearchResultsSidebarDelegate> {
	CardListViewController* _cardListViewController; 
	SearchResultsSidebarTableViewController* _searchResultsViewController; 
	id<SidebarProtocol> _sidebarDelegate; 
	BOOL _shouldChangeTableSize; 
	BOOL _singleEditModeEnabled; 
	UIColor* _defaultSidebarTopColour; 
	BOOL _isCancelingSearch; 
	NSTimer* _sidebarSearchDelayTimer; 
	float _lastStatusBarHeight; 
	KikCardViewController* cardViewController; 
	CardListTableView* cardListTableView; 
	KikNavigationBar* navigationBar; 
	UINavigationItem* kikNavigationItem; 
	id<SidebarProtocol> sidebarDelegate; 
	UIView* _topBarView; 
	UIView* _searchControllerWrapper; 
	URLHybridSearchBarController* _searchController; 
	SidebarTableView* _searchResultsTableView; 
	UIView* _searchWrapperView; 
}
@property (nonatomic,copy) CardListTableView* cardListTableView; 
@property (nonatomic,copy) KikNavigationBar* navigationBar; 
@property (nonatomic,copy) UINavigationItem* kikNavigationItem; 
@property (nonatomic,copy) UIView* topBarView; 				//@synthesize topBarView=_topBarView - In the implementation block
@property (nonatomic,retain) KikCardViewController* cardViewController; 
@property (nonatomic,retain) id<SidebarProtocol> sidebarDelegate; 
@property (nonatomic,copy) CardListViewController* cardListViewController; 				//@synthesize cardListViewController=_cardListViewController - In the implementation block
@property (nonatomic,retain) UIView* searchControllerWrapper; 				//@synthesize searchControllerWrapper=_searchControllerWrapper - In the implementation block
@property (nonatomic,retain) URLHybridSearchBarController* searchController; 				//@synthesize searchController=_searchController - In the implementation block
@property (nonatomic,retain) SidebarTableView* searchResultsTableView; 				//@synthesize searchResultsTableView=_searchResultsTableView - In the implementation block
@property (nonatomic,retain) UIView* searchWrapperView; 				//@synthesize searchWrapperView=_searchWrapperView - In the implementation block
-(void)setCardViewController:(id)arg1;
-(void)setSidebarDelegate:(id)arg1;
-(void)updateStatusBarState:(BOOL)arg1;
-(void)setSearchController:(id)arg1;
-(void)textFieldDidChange:(id)arg1;
-(void)updateStatusBarHeight;
-(void)sidebarClosing:(id)arg1;
-(void)sidebarClosed:(id)arg1;
-(void)sidebarEditModeStarting:(id)arg1;
-(void)sidebarEditModeDone:(id)arg1;
-(void)sidebarSingleEditModeStarting:(id)arg1;
-(void)sidebarSingleEditModeFinished:(id)arg1;
-(void)searchBarCancelTapped:(id)arg1;
-(void)appBecameActive:(id)arg1;
-(void)statusBarStyleWillChange:(id)arg1;
-(void)updateViewFrameForOrientation:(int)arg1;
-(void)updateSubviewFramesForOrientation:(int)arg1 andStatusBarHidden:(BOOL)arg2 andEditMode:(BOOL)arg3;
-(void)giveSearchBarFocus;
-(void)cardListViewController:(id)arg1 didSelectCard:(id)arg2;
-(void)searchResultsSidebarTable:(id)arg1 didSelectSearchResult:(id)arg2 andIsWebPage:(BOOL)arg3;
-(void)searchResultsDidScroll:(id)arg1;
-(void)searchInputDelayFired:(id)arg1;
-(void)setSearchControllerWrapper:(id)arg1;
-(void)setSearchResultsTableView:(id)arg1;
-(void)setSearchWrapperView:(id)arg1;
-(BOOL)textFieldShouldBeginEditing:(id)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(void).cxx_destruct;
@end