/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:22 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface StatisticsView : UILabel {
	NSTimer* _timer; 
}
-(void)updateMemoryUsage;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void).cxx_destruct;
-(void)shutdown;
@end