/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:02:06 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <RetryStrategyDelegate.h>

@interface StickerManager : NSObject <RetryStrategyDelegate> {
	ExponentialBackoffRetryStrategy* _retryStrategy; 
	BOOL _justRegistered; 
	BOOL _loadedStickerPacksIntoContainer; 
	id<StickerPackContainer> _container; 
	XDataManager* _xDataManager; 
	KikStorage* _storage; 
}
@property (nonatomic,retain) id<StickerPackContainer> container; 				//@synthesize container=_container - In the implementation block
@property (nonatomic,retain) XDataManager* xDataManager; 				//@synthesize xDataManager=_xDataManager - In the implementation block
@property (assign,nonatomic,__weak) KikStorage* storage; 				//@synthesize storage=_storage - In the implementation block
@property (assign,nonatomic) BOOL loadedStickerPacksIntoContainer; 				//@synthesize loadedStickerPacksIntoContainer=_loadedStickerPacksIntoContainer - In the implementation block
+(id)xStickerPackFromStickerPack:(id)arg1;
+(id)stickerPackFromXStickerPack:(id)arg1;
-(void)retryStrategyDidAdviseRetry:(id)arg1;
-(void)setStorage:(id)arg1;
-(void)onXmppConnected:(id)arg1;
-(id)initWithStickerPackContainer:(id)arg1 andXDataManager:(id)arg2 andStorage:(id)arg3;
-(void)setXDataManager:(id)arg1;
-(void)onJustRegisteredOrLogin:(id)arg1;
-(void)loadAllStickerPacksIntoContainer;
-(id)allStickerPacks;
-(void)xDataAddStickerPack:(id)arg1;
-(id)recordSetFromStickerPack:(id)arg1;
-(void)setLoadedStickerPacksIntoContainer:(BOOL)arg1;
-(void)saveStickerPack:(id)arg1;
-(void)cacheStickerUrls:(id)arg1;
-(void)setContainer:(id)arg1;
-(void)reset;
-(void).cxx_destruct;
@end