/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:02:00 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface StickerImageDescriptor : NSObject {
	NSString* _imageURL; 
	NSData* _imageData; 
}
@property (nonatomic,retain) NSString* imageURL; 				//@synthesize imageURL=_imageURL - In the implementation block
@property (nonatomic,retain) NSData* imageData; 				//@synthesize imageData=_imageData - In the implementation block
-(id)initWithImageURL:(id)arg1 imageData:(id)arg2;
-(void).cxx_destruct;
-(void)setImageData:(id)arg1;
-(void)setImageURL:(id)arg1;
@end