/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:02:02 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <StickerPackContainer.h>

@interface StickerPackContainer : NSObject <StickerPackContainer> {
	NSMutableDictionary* _packs; 
	URLDataManager* _urlDataManager; 
}
@property (nonatomic,retain) NSMutableDictionary* packs; 				//@synthesize packs=_packs - In the implementation block
@property (assign,nonatomic,__weak) URLDataManager* urlDataManager; 				//@synthesize urlDataManager=_urlDataManager - In the implementation block
-(id)initWithURLDataManager:(id)arg1;
-(void)setUrlDataManager:(id)arg1;
-(id)allStickerPacks;
-(void)addStickerPack:(id)arg1;
-(void)cacheImagesForSticker:(id)arg1;
-(void)cacheImages:(id)arg1;
-(void)setPacks:(id)arg1;
-(void)removeStickerPackWithURL:(id)arg1;
-(id)packForURL:(id)arg1;
-(void)reset;
-(void).cxx_destruct;
@end