/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:24 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface StopwatchEvent : NSObject {
	NSString* _eventName; 
	double _timestamp; 
}
@property (nonatomic,copy) NSString* eventName; 				//@synthesize eventName=_eventName - In the implementation block
@property (assign,nonatomic) double timestamp; 				//@synthesize timestamp=_timestamp - In the implementation block
-(void)setTimestamp:(double)arg1;
-(void).cxx_destruct;
-(void)setEventName:(id)arg1;
@end