/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:04 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface TalkedToConversationListViewController : ConversationListViewController {
	TouchThroughUIView* _footerWrapperView; 
	BOOL _newPeopleWasVisible; 
	BOOL _spamWasVisible; 
	NewPeopleFooterButton* _footerButton; 
}
@property (nonatomic,retain) NewPeopleFooterButton* footerButton; 				//@synthesize footerButton=_footerButton - In the implementation block
+(id)controllerWithDelegate:(id)arg1 andFRCs:(id)arg2;
-(void)createFooterView;
-(void)newPeopleButtonTapped:(id)arg1;
-(void)showFooter:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setFooterButton:(id)arg1;
-(void)controllerDidChangeContent:(id)arg1;
-(void)controllerWillChangeContent:(id)arg1;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
-(id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
-(void)scrollViewDidScroll:(id)arg1;
-(void)viewDidLoad;
-(void).cxx_destruct;
@end