/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:48 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface TestUserCell : UITableViewCell {
	UILabel* _TestLabel; 
}
@property (assign,nonatomic,__weak) UILabel* TestLabel; 				//@synthesize TestLabel=_TestLabel - In the implementation block
-(void)setTestLabel:(id)arg1;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
-(void).cxx_destruct;
@end