/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:14:25 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ThreadSafeTimer : NSObject {
	NSCondition* _runLoopStartCondition; 
	BOOL _runLoopHasStarted; 
	int _id; 
	NSTimer* _timer; 
	NSThread* _timerThread; 
	NSRunLoop* _runLoop; 
	SEL _selector; 
	id _target; 
	id _userInfo; 
	NSString* _name; 
	NSObject* _runLoopLock; 
}
-(id)initWithInterval:(double)arg1 target:(id)arg2 andSelector:(SEL)arg3;
-(id)initWithInterval:(double)arg1 target:(id)arg2 andSelector:(SEL)arg3 andUserInfo:(id)arg4;
-(void)performTimerThreadRunLoop:(id)arg1;
-(id)initWithInterval:(double)arg1 target:(id)arg2 selector:(SEL)arg3 andName:(id)arg4;
-(id)initWithInterval:(double)arg1 target:(id)arg2 selector:(SEL)arg3 userInfo:(id)arg4 andName:(id)arg5;
-(void)performTimerCallback:(id)arg1;
-(void)startWithInterval:(double)arg1 target:(id)arg2 andSelector:(SEL)arg3;
-(void)dealloc;
-(void)invalidate;
-(BOOL)isValid;
@end