/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:28 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ThresholdTimer : NSObject {
	id _target; 
	SEL _selector; 
	double _interval; 
	double _thresholdInterval; 
	NSDictionary* _userInfo; 
	NSTimer* _timer; 
	NSTimer* _thresholdTimer; 
}
-(id)initWithInterval:(double)arg1 andThresholdInterval:(double)arg2 target:(id)arg3 selector:(SEL)arg4 userInfo:(id)arg5;
-(id)initWithInterval:(double)arg1 andThresholdInterval:(double)arg2 target:(id)arg3 selector:(SEL)arg4;
-(void)timerHit:(id)arg1;
-(void)thresholdTimerHit:(id)arg1;
-(void)resetAndFireResult;
-(void)dealloc;
-(void)resetTimer;
@end