/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:10:02 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "ExponentialBackoffRetryStrategy.h"

@interface ThrottledExponentialBackoffRetryStrategy : ExponentialBackoffRetryStrategy {
	NSDate* _blockedUntil; 
}
-(void)blockRetriesUntil:(id)arg1;
-(double)nextRetryInterval;
-(void)dealloc;
@end