/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:12:12 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import "RetryStrategy.h"
 #import "ThreadSafeTimer.h"

@interface TimedRetryStrategy : NSObject <RetryStrategy> {
	ThreadSafeTimer* _retryTimer; 
	id<RetryStrategyDelegate> delegate; 
}
@property (nonatomic) BOOL isRetryScheduled; 
@property (nonatomic,retain) id<RetryStrategyDelegate> delegate; 
-(BOOL)scheduleRetry;
-(double)nextRetryInterval;
-(void)suggestRetryToDelegate;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(id)init;
-(void)reset;
@end