/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 11:43:21 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Tokener : NSObject {
	int _component1; 
	int _component2; 
}
-(id)generateTokenFromData:(id)arg1;
-(id)init;
@end