/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:06 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol PhotoHandler
@required
-(void)selectPhotosFromSource(int):arg1 callback(id):arg2 photoCallback(?):arg3 atMost(id):arg4 atLeast(?):arg5 ;
-(void)saveImage(id):arg1 callback(id):arg2 ;
-(void)requestSaveToGalleryAccessCallback(id):arg1 ;
-(void)selectPhotosFromSource(int):arg1 callback(id):arg2 photoCallback(?):arg3 atMost(id):arg4 atLeast(?):arg5 ;
-(void)saveImage(id):arg1 callback(id):arg2 ;
-(void)requestSaveToGalleryAccessCallback(id):arg1 ;
@end

@protocol UIImagePickerControllerDelegate
@optional
-(void)imagePickerControllerDidCancel(id):arg1 ;
-(void)imagePickerController(id):arg1 didFinishPickingMediaWithInfo(id):arg2 ;
-(void)imagePickerController(id):arg1 didFinishPickingImage(id):arg2 editingInfo(id):arg3 ;
@end
