/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:34 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIActionSheetDelegate
@optional
-(void)actionSheet(id):arg1 clickedButtonAtIndex(int):arg2 ;
-(void)actionSheetCancel(id):arg1 ;
-(void)willPresentActionSheet(id):arg1 ;
-(void)didPresentActionSheet(id):arg1 ;
-(void)actionSheet(id):arg1 willDismissWithButtonIndex(int):arg2 ;
-(void)actionSheet(id):arg1 didDismissWithButtonIndex(int):arg2 ;
@end

@protocol UIGestureRecognizerDelegate
@optional
-(BOOL)gestureRecognizerShouldBegin(id):arg1 ;
-(BOOL)gestureRecognizer(id):arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer(id):arg2 ;
-(BOOL)gestureRecognizer(id):arg1 shouldRequireFailureOfGestureRecognizer(id):arg2 ;
-(BOOL)gestureRecognizer(id):arg1 shouldBeRequiredToFailByGestureRecognizer(id):arg2 ;
-(BOOL)gestureRecognizer(id):arg1 shouldReceiveTouch(id):arg2 ;
@end

@protocol UITableViewDataSource
@optional
-(int)numberOfSectionsInTableView(id):arg1 ;
-(id)tableView(id):arg1 titleForHeaderInSection(int):arg2 ;
-(id)tableView(id):arg1 titleForFooterInSection(int):arg2 ;
-(BOOL)tableView(id):arg1 canEditRowAtIndexPath(id):arg2 ;
-(BOOL)tableView(id):arg1 canMoveRowAtIndexPath(id):arg2 ;
-(id)sectionIndexTitlesForTableView(id):arg1 ;
-(int)tableView(id):arg1 sectionForSectionIndexTitle(id):arg2 atIndex(int):arg3 ;
-(void)tableView(id):arg1 commitEditingStyle(int):arg2 forRowAtIndexPath(id):arg3 ;
-(void)tableView(id):arg1 moveRowAtIndexPath(id):arg2 toIndexPath(id):arg3 ;
@required
-(int)tableView(id):arg1 numberOfRowsInSection(int):arg2 ;
-(id)tableView(id):arg1 cellForRowAtIndexPath(id):arg2 ;
-(int)tableView(id):arg1 numberOfRowsInSection(int):arg2 ;
-(id)tableView(id):arg1 cellForRowAtIndexPath(id):arg2 ;
@end
