/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 11524 AM Mountain Daylight Time
 * Operating System Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UploadManagerDelegate
@required
-(void)uploadManager:(id)arg1 didUploadContent:(id)arg2 ;
-(void)uploadManager:(id)arg1 didFailToUploadContent:(id)arg2 ;
-(void)uploadManager:(id)arg1 didUploadContent:(id)arg2 ;
-(void)uploadManager:(id)arg1 didFailToUploadContent:(id)arg2 ;
@end
