/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:06 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSURLConnectionDelegate.h>
#import <NSURLConnectionDataDelegate.h>

@interface URLDataManager : NSObject <NSURLConnectionDelegate, NSURLConnectionDataDelegate> {
	NSMutableDictionary* _urlsToData; 
	NSMutableDictionary* _urlsToConnectionObject; 
	NSMutableArray* _pendingRequests; 
	NSObject* _lockObject; 
	id<URLDataManagerStorageProvider> _storageProvider; 
	BOOL _saveRequested; 
}
-(id)dataForURL:(id)arg1;
-(id)initWithStorageProvider:(id)arg1;
-(void)deleteDataForURL:(id)arg1;
-(void)loadURLDataIfNeeded;
-(void)saveURLDataAsynchronously;
-(void)saveURLDataSynchronously;
-(void)executePendingRequests;
-(void)reset;
-(void)connection:(id)arg1 didFailWithError:(id)arg2;
-(void)connection:(id)arg1 didReceiveData:(id)arg2;
-(void)connectionDidFinishLoading:(id)arg1;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2;
-(void).cxx_destruct;
@end