/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:54 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface URLHybridSearchBarController : HybridSearchBarController {
	BOOL _searchMode; 
	NSLayoutConstraint* _searchBarWidthConstraint; 
	NSLayoutConstraint* _searchBarTrailingConstraint; 
}
@property (nonatomic,retain) NSLayoutConstraint* searchBarWidthConstraint; 				//@synthesize searchBarWidthConstraint=_searchBarWidthConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint* searchBarTrailingConstraint; 				//@synthesize searchBarTrailingConstraint=_searchBarTrailingConstraint - In the implementation block
@property (assign,nonatomic) BOOL searchMode; 				//@synthesize searchMode=_searchMode - In the implementation block
-(void)hideRightButtonWithAnimation:(BOOL)arg1;
-(void)showRightButtonWithAnimation:(BOOL)arg1;
-(void)rightButtonClicked:(id)arg1;
-(void)setSearchBarWidthConstraint:(id)arg1;
-(void)setSearchBarTrailingConstraint:(id)arg1;
-(void)setSearchMode:(BOOL)arg1;
-(void)viewDidLoad;
-(void).cxx_destruct;
@end