/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:14 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCacheDelegate.h>

@interface UserFSBufferCache : NSObject <NSCacheDelegate> {
	NSCache* _cache; 
	NSMutableDictionary* _dirtyBuffers; 
	int _fd; 
}
-(void)cache:(id)arg1 willEvictObject:(id)arg2;
-(void).cxx_destruct;
-(void)releaseBuffer:(id)arg1;
-(int)flushBuffer:(id)arg1;
-(id)getBufferAtOffset:(unsigned long long)arg1 ofLength:(unsigned long)arg2 error:(int*)arg3;
-(int)flushAndReturnError;
-(int)invalidateAllBuffers;
-(id)initWithFileDescriptor:(int)arg1;
@end