/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:02:03 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol ViewHitProtocol
@optional
-(void)userToAdd(id):arg1 ;
-(void)userWasClicked(id):arg1 ;
-(void)didCancel;
@end
