/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:32 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XAddressBookSettings : PBGeneratedMessage {
	unsigned int hasOptedIn_:1; 
	unsigned int optedIn_:1; 
}
@property (assign) BOOL optedIn; 
+(id)builder;
+(id)parseFromData:(id)arg1;
+(id)parseFromData:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromInputStream:(id)arg1;
+(id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromCodedInputStream:(id)arg1;
+(id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)builderWithPrototype:(id)arg1;
+(id)defaultInstance;
+(void)initialize;
-(id)builder;
-(void)writeToCodedOutputStream:(id)arg1;
-(int)serializedSize;
-(BOOL)isInitialized;
-(void)setOptedIn:(BOOL)arg1;
-(BOOL)hasOptedIn;
-(void)setHasOptedIn:(BOOL)arg1;
-(id)defaultInstance;
-(void)dealloc;
-(id)init;
@end