/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:24 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XCardAnonymousKey : PBGeneratedMessage {
	unsigned int hasPublicKey_:1; 
	unsigned int hasPrivateKey_:1; 
	NSData* publicKey; 
	NSData* privateKey; 
}
@property (retain) NSData* publicKey; 
@property (retain) NSData* privateKey; 
+(id)builder;
+(id)parseFromData:(id)arg1;
+(id)parseFromData:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromInputStream:(id)arg1;
+(id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromCodedInputStream:(id)arg1;
+(id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)builderWithPrototype:(id)arg1;
+(id)defaultInstance;
+(void)initialize;
-(id)builder;
-(void)writeToCodedOutputStream:(id)arg1;
-(int)serializedSize;
-(BOOL)isInitialized;
-(void)setPrivateKey:(id)arg1;
-(BOOL)hasPublicKey;
-(BOOL)hasPrivateKey;
-(void)setHasPublicKey:(BOOL)arg1;
-(void)setHasPrivateKey:(BOOL)arg1;
-(id)defaultInstance;
-(void)dealloc;
-(id)init;
-(void)setPublicKey:(id)arg1;
@end