/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:22 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XCardPermission : PBGeneratedMessage {
	unsigned int hasName_:1; 
	unsigned int hasValue_:1; 
	int name; 
	int value; 
}
@property (assign) int name; 
@property (assign) int value; 
+(id)builder;
+(id)parseFromData:(id)arg1;
+(id)parseFromData:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromInputStream:(id)arg1;
+(id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromCodedInputStream:(id)arg1;
+(id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)builderWithPrototype:(id)arg1;
+(id)defaultInstance;
+(void)initialize;
-(id)builder;
-(void)writeToCodedOutputStream:(id)arg1;
-(int)serializedSize;
-(BOOL)isInitialized;
-(void)setHasName:(BOOL)arg1;
-(id)defaultInstance;
-(void)dealloc;
-(id)init;
-(void)setValue:(int)arg1;
-(void)setName:(int)arg1;
-(BOOL)hasValue;
-(void)setHasValue:(BOOL)arg1;
-(BOOL)hasName;
@end