/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:23 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XCardDescriptor : PBGeneratedMessage {
	unsigned int hasDateAdded_:1; 
	unsigned int hasLastAccessed_:1; 
	unsigned int hasUrl_:1; 
	unsigned int hasTitle_:1; 
	unsigned int hasIconUrl_:1; 
	unsigned int hasMediaTrayIconUrl_:1; 
	unsigned int hasTermsOfServiceLink_:1; 
	unsigned int hasPrivacyLink_:1; 
	unsigned int hasPushToken_:1; 
	unsigned int hasWebPageUrl_:1; 
	unsigned int hasAnonymousKey_:1; 
	long long dateAdded; 
	long long lastAccessed; 
	NSString* url; 
	NSString* title; 
	NSString* iconUrl; 
	NSString* mediaTrayIconUrl; 
	NSString* termsOfServiceLink; 
	NSString* privacyLink; 
	NSString* pushToken; 
	NSString* webPageUrl; 
	XCardAnonymousKey* anonymousKey; 
	NSMutableArray* mutablePermissionsList; 
	NSMutableArray* mutableBackStackEntriesList; 
}
@property (retain) NSString* url; 
@property (retain) NSString* title; 
@property (retain) NSString* iconUrl; 
@property (retain) NSString* mediaTrayIconUrl; 
@property (retain) NSString* termsOfServiceLink; 
@property (retain) NSString* privacyLink; 
@property (retain) NSString* pushToken; 
@property (assign) long long dateAdded; 
@property (assign) long long lastAccessed; 
@property (retain) XCardAnonymousKey* anonymousKey; 
@property (retain) NSString* webPageUrl; 
@property (retain) NSMutableArray* mutablePermissionsList; 
@property (retain) NSMutableArray* mutableBackStackEntriesList; 
+(id)builder;
+(id)parseFromData:(id)arg1;
+(id)parseFromData:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromInputStream:(id)arg1;
+(id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromCodedInputStream:(id)arg1;
+(id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)builderWithPrototype:(id)arg1;
+(id)defaultInstance;
+(void)initialize;
-(id)builder;
-(void)setPrivacyLink:(id)arg1;
-(void)setTermsOfServiceLink:(id)arg1;
-(void)setLastAccessed:(long long)arg1;
-(void)writeToCodedOutputStream:(id)arg1;
-(int)serializedSize;
-(BOOL)isInitialized;
-(void)setHasTitle:(BOOL)arg1;
-(void)setIconUrl:(id)arg1;
-(void)setMediaTrayIconUrl:(id)arg1;
-(void)setAnonymousKey:(id)arg1;
-(void)setMutablePermissionsList:(id)arg1;
-(void)setWebPageUrl:(id)arg1;
-(void)setMutableBackStackEntriesList:(id)arg1;
-(BOOL)hasIconUrl;
-(BOOL)hasMediaTrayIconUrl;
-(BOOL)hasTermsOfServiceLink;
-(BOOL)hasPrivacyLink;
-(BOOL)hasPushToken;
-(BOOL)hasDateAdded;
-(BOOL)hasLastAccessed;
-(BOOL)hasAnonymousKey;
-(id)permissionsList;
-(BOOL)hasWebPageUrl;
-(id)backStackEntriesList;
-(void)setHasUrl:(BOOL)arg1;
-(void)setHasIconUrl:(BOOL)arg1;
-(void)setHasMediaTrayIconUrl:(BOOL)arg1;
-(void)setHasTermsOfServiceLink:(BOOL)arg1;
-(void)setHasPrivacyLink:(BOOL)arg1;
-(void)setHasPushToken:(BOOL)arg1;
-(void)setHasDateAdded:(BOOL)arg1;
-(void)setHasLastAccessed:(BOOL)arg1;
-(void)setHasAnonymousKey:(BOOL)arg1;
-(void)setHasWebPageUrl:(BOOL)arg1;
-(id)permissionsAtIndex:(int)arg1;
-(id)backStackEntriesAtIndex:(int)arg1;
-(id)defaultInstance;
-(void)setPushToken:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)setTitle:(id)arg1;
-(void)setUrl:(id)arg1;
-(BOOL)hasTitle;
-(BOOL)hasUrl;
-(void)setDateAdded:(long long)arg1;
@end