/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:12 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XCardPinnedList_Builder : PBGeneratedMessage_Builder {
	XCardPinnedList* result; 
}
@property (retain) XCardPinnedList* result; 
-(id)mergeFromCodedInputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
-(id)mergeFrom:(id)arg1;
-(id)buildPartial;
-(id)internalGetResult;
-(id)clone;
-(id)cardUrlHashList;
-(id)cardUrlHashAtIndex:(int)arg1;
-(id)addCardUrlHash:(id)arg1;
-(id)replaceCardUrlHashAtIndex:(int)arg1 with:(id)arg2;
-(id)addAllCardUrlHash:(id)arg1;
-(id)clearCardUrlHashList;
-(id)defaultInstance;
-(void)dealloc;
-(id)init;
-(id)clear;
-(void)setResult:(id)arg1;
-(id)build;
@end