/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 115830 PM Mountain Daylight Time
 * Operating System Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol XDataRecordProvider
@required
-(id)getAllCachedRecords;
-(id)promiseForRecordRetrieval:(id)arg1 ;
-(id)promiseForRecordUpdate:(id)arg1 ;
-(id)getCachedRecords;
-(void)reset;
-(id)getAllCachedRecords;
-(id)promiseForRecordRetrieval:(id)arg1 ;
-(id)promiseForRecordUpdate:(id)arg1 ;
-(id)getCachedRecords;
-(void)reset;
@end
