/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:08 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XDataPlugin : CardsPlugin {
	SecureXDataManager* _xDataManager; 
}
+(id)dictionaryForRecord:(id)arg1 encrypted:(BOOL)arg2;
+(id)dictionaryForRecordSet:(id)arg1 encrypted:(BOOL)arg2;
-(id)initWithXDataManager:(id)arg1;
-(id)deleteRecord:(id)arg1 callback:(id)arg2;
-(id)getAllRecords:(id)arg1 callback:(id)arg2;
-(id)getPrimaryKeys:(id)arg1 callback:(id)arg2;
-(void).cxx_destruct;
@end