/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 11:56:18 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */
#import "XDataRecordProvider.h"

@interface XDataManager : NSObject {
	id<XDataRecordProvider> _recordProvider; 
}
@property (nonatomic,copy) id<XDataRecordProvider> recordProvider; 				//@synthesize recordProvider=_recordProvider - In the implementation block
-(id)getAllCachedRecords;
-(id)updateRecords:(id)arg1 withXClass:(Class)arg2 secure:(BOOL)arg3;
-(id)retrieveRecord:(id)arg1 withXClass:(Class)arg2 secure:(BOOL)arg3;
-(void)parseRecords:(id)arg1 withXClass:(Class)arg2 secure:(BOOL)arg3;
-(void)parseRecord:(id)arg1 withXClass:(Class)arg2 secure:(BOOL)arg3;
-(id)setupParsingPromise:(id)arg1 withXClass:(Class)arg2 secure:(BOOL)arg3;
-(id)initWithRecordProvider:(id)arg1;
-(void)reset;
@end