/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, July 5, 2014 at 1:04:16 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <Foundation/NSObject.h>

@interface XMPPJID : NSObject <NSCoding, NSCopying> {
	NSString* user; 
	NSString* domain; 
	NSString* resource; 
}
@property (copy) NSString* user; 
@property (copy) NSString* domain; 
@property (copy) NSString* resource; 
+(BOOL)validateDomain:(id)arg1;
+(BOOL)validateResource:(id)arg1;
+(id)limitString:(id)arg1 toLength:(unsigned long)arg2;
+(BOOL)validateUser:(id)arg1 domain:(id)arg2 resource:(id)arg3;
+(BOOL)parse:(id)arg1 outUser:(id*)arg2 outDomain:(id*)arg3 outResource:(id*)arg4;
+(id)jidWithPrevalidatedUser:(id)arg1 prevalidatedDomain:(id)arg2 prevalidatedResource:(id)arg3;
+(id)jidWithPrevalidatedUser:(id)arg1 prevalidatedDomain:(id)arg2 resource:(id)arg3;
+(id)jidWithString:(id)arg1;
+(id)jidWithString:(id)arg1 resource:(id)arg2;
+(id)jidWithUser:(id)arg1 domain:(id)arg2 resource:(id)arg3;
-(BOOL)isEqualToJID:(id)arg1 options:(int)arg2;
-(id)full;
-(id)bareJID;
-(id)domainJID;
-(id)bare;
-(BOOL)isBare;
-(BOOL)isBareWithUser;
-(BOOL)isFullWithUser;
-(BOOL)isServer;
-(id)jidWithNewResource:(id)arg1;
-(BOOL)isEqualToJID:(id)arg1;
-(BOOL)isFull;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(BOOL)isEqual:(id)arg1;
-(unsigned)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1;
@end