/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:56 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XStickerPack : PBGeneratedMessage {
	unsigned int hasTitle_:1; 
	unsigned int hasIcon_:1; 
	unsigned int hasStoreLink_:1; 
	NSString* title; 
	NSString* icon; 
	NSString* storeLink; 
	NSMutableArray* mutableStickerList; 
}
@property (retain) NSString* title; 
@property (retain) NSString* icon; 
@property (retain) NSString* storeLink; 
@property (retain) NSMutableArray* mutableStickerList; 
+(id)builder;
+(id)parseFromData:(id)arg1;
+(id)parseFromData:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromInputStream:(id)arg1;
+(id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromCodedInputStream:(id)arg1;
+(id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)builderWithPrototype:(id)arg1;
+(id)defaultInstance;
+(void)initialize;
-(id)builder;
-(void)writeToCodedOutputStream:(id)arg1;
-(int)serializedSize;
-(BOOL)isInitialized;
-(void)setStoreLink:(id)arg1;
-(id)stickerList;
-(void)setMutableStickerList:(id)arg1;
-(BOOL)hasStoreLink;
-(void)setHasTitle:(BOOL)arg1;
-(void)setHasIcon:(BOOL)arg1;
-(void)setHasStoreLink:(BOOL)arg1;
-(id)stickerAtIndex:(int)arg1;
-(id)defaultInstance;
-(BOOL)hasIcon;
-(void)dealloc;
-(id)init;
-(void)setTitle:(id)arg1;
-(void)setIcon:(id)arg1;
-(BOOL)hasTitle;
@end