/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:56 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XStickerItem_Builder : PBGeneratedMessage_Builder {
	XStickerItem* result; 
}
@property (retain) XStickerItem* result; 
-(id)mergeFromCodedInputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
-(id)mergeFrom:(id)arg1;
-(id)buildPartial;
-(id)internalGetResult;
-(id)clone;
-(id)setPngPreview:(id)arg1;
-(id)setCompatPreview:(id)arg1;
-(id)pngPreview;
-(id)compatPreview;
-(id)clearIcon;
-(BOOL)hasPngPreview;
-(BOOL)hasCompatPreview;
-(id)clearPngPreview;
-(id)clearCompatPreview;
-(id)defaultInstance;
-(BOOL)hasIcon;
-(void)dealloc;
-(id)init;
-(id)setIcon:(id)arg1;
-(id)clear;
-(void)setResult:(id)arg1;
-(id)build;
-(id)icon;
@end