/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:57 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XStickerPack_Builder : PBGeneratedMessage_Builder {
	XStickerPack* result; 
}
@property (retain) XStickerPack* result; 
-(id)mergeFromCodedInputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
-(id)mergeFrom:(id)arg1;
-(id)buildPartial;
-(id)internalGetResult;
-(id)clone;
-(id)addSticker:(id)arg1;
-(id)storeLink;
-(id)setStoreLink:(id)arg1;
-(id)stickerList;
-(BOOL)hasStoreLink;
-(id)stickerAtIndex:(int)arg1;
-(id)clearTitle;
-(id)clearIcon;
-(id)clearStoreLink;
-(id)replaceStickerAtIndex:(int)arg1 with:(id)arg2;
-(id)addAllSticker:(id)arg1;
-(id)clearStickerList;
-(id)defaultInstance;
-(BOOL)hasIcon;
-(void)dealloc;
-(id)init;
-(id)setTitle:(id)arg1;
-(id)title;
-(id)setIcon:(id)arg1;
-(id)clear;
-(void)setResult:(id)arg1;
-(BOOL)hasTitle;
-(id)build;
-(id)icon;
@end