/*
 * This header is generated by weak_classdump 0.2
 * on Friday, July 4, 2014 at 12:01:58 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XStickerItem : PBGeneratedMessage {
	unsigned int hasIcon_:1; 
	unsigned int hasPngPreview_:1; 
	unsigned int hasCompatPreview_:1; 
	NSString* icon; 
	NSString* pngPreview; 
	NSString* compatPreview; 
}
@property (retain) NSString* icon; 
@property (retain) NSString* pngPreview; 
@property (retain) NSString* compatPreview; 
+(id)builder;
+(id)parseFromData:(id)arg1;
+(id)parseFromData:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromInputStream:(id)arg1;
+(id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)parseFromCodedInputStream:(id)arg1;
+(id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
+(id)builderWithPrototype:(id)arg1;
+(id)defaultInstance;
+(void)initialize;
-(id)builder;
-(void)writeToCodedOutputStream:(id)arg1;
-(int)serializedSize;
-(BOOL)isInitialized;
-(void)setPngPreview:(id)arg1;
-(void)setCompatPreview:(id)arg1;
-(void)setHasIcon:(BOOL)arg1;
-(BOOL)hasPngPreview;
-(BOOL)hasCompatPreview;
-(void)setHasPngPreview:(BOOL)arg1;
-(void)setHasCompatPreview:(BOOL)arg1;
-(id)defaultInstance;
-(BOOL)hasIcon;
-(void)dealloc;
-(id)init;
-(void)setIcon:(id)arg1;
@end